import {buildHubEmail,queueAcknowledgement,sendAcknowledgement} from './hub-mail';
import {randomUUID,createHash} from 'node:crypto';
import {hubDb,HubError,openRequest,seal} from './hub-store';
import {vaultKey} from './provider-secrets';
import {audit} from './management';
import {FUNCTION_CUISINES,validFunctionDate} from './function-config';
import {sendEmailMessage} from './email';
export function functionDb(){const db=hubDb();db.exec(`CREATE TABLE IF NOT EXISTS function_bookings(id TEXT PRIMARY KEY,request_key TEXT UNIQUE NOT NULL,fingerprint TEXT NOT NULL,date TEXT NOT NULL,details TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',notification TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE UNIQUE INDEX IF NOT EXISTS one_confirmed_function_per_date ON function_bookings(date) WHERE status='confirmed';`);return db;}
function field(value:unknown,label:string,max:number,required=true){if(typeof value!=='string'||value.trim().length>max||(required&&!value.trim()))throw new HubError(`Enter a valid ${label}.`);return value.trim();}
export function submitFunction(input:Record<string,unknown>,key:string){
 if(!/^[a-zA-Z0-9-]{16,80}$/.test(key))throw new HubError('Refresh the page and try again.');
 if(input.website)throw new HubError('Unable to submit this request.');
 if(input.consent!==true)throw new HubError('Please agree to the use of your details for this enquiry.');
 if(!validFunctionDate(input.date))throw new HubError('Choose a date from today within the next two years.');
 const pax=Number(input.pax);if(!Number.isInteger(pax)||pax<1||pax>10000)throw new HubError('Enter a valid number of guests.');
 if(!FUNCTION_CUISINES.includes(input.cuisine as typeof FUNCTION_CUISINES[number]))throw new HubError('Choose a function style.');
 const budgetRaw=field(input.budget??'','budget',16,false);
 if(budgetRaw&&(!/^\d+(\.\d{1,2})?$/.test(budgetRaw)||Number(budgetRaw)<=0||Number(budgetRaw)>100000000))throw new HubError('Enter a positive budget in rand, with up to two decimal places.');
 const budgetBasis=input.budgetBasis??'total';if(!['total','per-person'].includes(String(budgetBasis)))throw new HubError('Choose total or per-person budget.');
 const details={budget:budgetRaw?Number(budgetRaw).toFixed(2):'',budgetBasis:budgetRaw?String(budgetBasis):'',pax:String(pax),cuisine:String(input.cuisine),contactPerson:field(input.contactPerson,'contact person',120),company:field(input.company??'','company',160,false),theme:field(input.theme??'','theme',300,false),email:field(input.email,'email',254).toLowerCase(),phone:field(input.phone,'contact number',30),consent:true};
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(details.email)||!/^\+?[\d ()-]{7,30}$/.test(details.phone))throw new HubError('Enter a valid email and contact number.');
 const db=functionDb(),date=input.date,fingerprint=createHash('sha256').update(vaultKey()).update(JSON.stringify({date,details})).digest('hex');
 const prior=db.prepare('SELECT id,fingerprint FROM function_bookings WHERE request_key=?').get(key) as {id:string;fingerprint:string}|undefined;
 if(prior){if(prior.fingerprint!==fingerprint)throw new HubError('This request has changed. Refresh and try again.');return prior.id;}
 if(db.prepare("SELECT id FROM function_bookings WHERE date=? AND status='confirmed'").get(date))throw new HubError('That date is already booked. Please choose another date.');
 const now=Date.now(),bucket='function-'+createHash('sha256').update(details.email).digest('hex');db.prepare('DELETE FROM hub_limits WHERE expires_at<=?').run(now);
 for(const [key,max] of [[bucket,5],['functions-all',100]] as const){const row=db.prepare('INSERT INTO hub_limits VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').get(key,now+3600000) as {count:number};if(row.count>max)throw new HubError('Too many requests. Please try again later.');}
 const id=randomUUID(),stamp=new Date(now).toISOString();db.exec('BEGIN IMMEDIATE');try{db.prepare('INSERT INTO function_bookings(id,request_key,fingerprint,date,details,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(id,key,fingerprint,date,seal(details,id),stamp,stamp);queueAcknowledgement(id);db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}return id;
}
export function bookedFunctionDates(){return (functionDb().prepare("SELECT date FROM function_bookings WHERE status='confirmed' AND date>=? ORDER BY date").all(new Date(Date.now()+2*3600000).toISOString().slice(0,10)) as {date:string}[]).map(r=>r.date);}
export function listFunctions(month:string,actor:string){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw new HubError('Choose a valid month.');audit(actor,'function-calendar-viewed',month);return (functionDb().prepare('SELECT id,date,details,status,notification,(SELECT status FROM hub_acknowledgements a WHERE a.id=function_bookings.id) AS acknowledgement,created_at AS createdAt FROM function_bookings WHERE date LIKE ? ORDER BY date,created_at').all(month+'%') as {id:string;date:string;details:string;status:string;notification:string;createdAt:string}[]).map(({details,...r})=>({...r,details:openRequest(details,r.id)}));}
export function updateFunction(id:string,status:unknown,actor:string){if(!['pending','confirmed','declined','cancelled'].includes(String(status)))throw new HubError('Choose a valid booking status.');const db=functionDb();const row=db.prepare('SELECT date FROM function_bookings WHERE id=?').get(id) as {date:string}|undefined;if(!row)throw new HubError('Booking not found.');if(status==='confirmed'&&!validFunctionDate(row.date))throw new HubError('Cannot confirm a past date.');try{db.prepare('UPDATE function_bookings SET status=?,updated_at=? WHERE id=?').run(String(status),new Date().toISOString(),id);}catch(e){if(String(e).includes('UNIQUE'))throw new HubError('Another booking is already confirmed for that date.');throw e;}audit(actor,'function-booking-status',`${id}:${status}`);}
export async function notifyFunction(id:string){if(process.env.MIDPOINT_HUB_EMAIL_ENABLED!=='true')return;const db=functionDb(),stamp=new Date().toISOString();const row=db.prepare('SELECT date,details FROM function_bookings WHERE id=?').get(id) as {date:string;details:string}|undefined;if(row)await sendAcknowledgement('functions',id,{...openRequest(row.details,id),date:row.date});const claim=db.prepare("UPDATE function_bookings SET notification='sending',updated_at=? WHERE id=? AND (notification IN ('pending','failed') OR (notification='sending' AND updated_at<?))").run(stamp,id,new Date(Date.now()-60000).toISOString());if(!claim.changes)return;try{await sendEmailMessage('michelle@midpointhub.com',buildHubEmail('functions',id,{test:!!row&&/^TEST\b/i.test(String(openRequest(row.details,id).contactPerson))},true),`function-${id}`,'Midpoint Hub');db.prepare("UPDATE function_bookings SET notification='sent',updated_at=? WHERE id=?").run(new Date().toISOString(),id);}catch{db.prepare("UPDATE function_bookings SET notification='failed',updated_at=? WHERE id=?").run(new Date().toISOString(),id);}}
