export type LegalSection = { id: string; title: string; paragraphs: string[] };
export const legalEdition = '1 October 2026';
export const privacySections: LegalSection[] = [
 {id:'operator',title:'Who is responsible for your information',paragraphs:[
  'Midpoint Hub and its FOND, Gym, Padel and Functions services are operated by Blend Property 20 (Pty) Ltd, registration 2016/031577/07. In this policy, “we”, “us” and “our” mean that company in respect of information under its control. Our business contact address is Midpoint, 162 Tonetti Street, Halfway House, Midrand, 1685, South Africa.',
  'Our designated privacy contact is Mark Corbishley: legal@blendproperty.co.za. Please identify Midpoint Hub and the relevant service when writing. You can also contact the service team listed below. This notice covers visitors, customers, account holders, membership applicants, event participants and people making enquiries through midpointhub.com and its installed web app.'
 ]},
 {id:'information',title:'What we collect and why',paragraphs:[
  'Optional FOND delivery pin: when you tap Use my location, your browser asks for location permission. You must confirm the pin before it is submitted with your order. FOND stores the coordinates and reported accuracy with the delivery order for authorised staff to fulfil it; this is a single location capture, not continuous tracking. You can remove the pin before ordering and use your business and building details instead. Opening a pin preview or directions in Google Maps shares those coordinates with Google under its own privacy information.',
  'FOND orders: your name, chosen items and options, order notes, collection or delivery selection, time, and relevant telephone, email, company and building details. We use these to prepare and fulfil orders, resolve problems and send the service updates you request. Order and payment references, amounts, status, refunds and reward records support reconciliation and customer service.',
  'FOND accounts: email address, a protected password record, verification and session records, and order history associated with the account. If you enable additional account security, we process the chosen email or mobile destination, verification challenges and recovery records. Loyalty features use qualifying purchase and redemption records; an account does not automatically opt you into marketing.',
  'Gym and Padel signup: first name, surname, email, mobile number, ID or passport number and the relevant company, building or tenant details requested by the form. These help the team review your application, distinguish applicants and arrange the relevant membership or tenant setup. Padel may also ask whether you already have a Playtomic account. Event-interest forms collect the details needed for the chosen event and follow-up.',
  'Functions: requested date, guest count, gathering style, contact person, email and telephone, with optional company, theme and budget details. Michelle’s team uses these to discuss availability, prepare a proposal and manage the enquiry and any agreed function. The public calendar displays unavailable dates, not customer names or event details.',
  'Support and security: correspondence, staff handling notes, changes to requests, notification delivery records and relevant technical logs. Hosting systems may process IP addresses and browser/request information to serve the app, diagnose failures and protect it against misuse. Staff access and changes are recorded for accountability.'
 ]},
 {id:'collection',title:'How information reaches us and your choices',paragraphs:[
  'Most information comes directly from you through forms, orders, account controls and correspondence. We may also receive relevant information from an authorised representative, our service team or a payment or communications provider, such as a transaction result or delivery status. Please only give another person’s details when you are authorised to do so and make this policy available to them.',
  'Required fields are identified on each form. Without those details we may be unable to process the online request or supply the requested service. Company, theme and budget are optional on the Functions form. Contact the relevant team if you need assistance or wish to discuss an alternative to submitting information online.',
  'The Hub signup form asks for an identity number, not an uploaded identity document or facial photograph. Do not put identity copies, banking credentials, passwords, medical histories or other unnecessary sensitive information in free-text fields or ordinary email. The Hub form does not enrol you in facial recognition. Any separate access-control collection needs its own appropriate notice and process.'
 ]},
 {id:'grounds',title:'Purposes and lawful processing',paragraphs:[
  'We process relevant information to take steps you request before an agreement, perform an agreed service, administer orders and accounts, protect legitimate operational and security interests, meet legal obligations, and act on valid consent where that is the appropriate basis. The basis depends on the particular purpose; this policy does not seek unlimited consent for every use.',
  'Submitting a Gym, Padel or Functions enquiry authorises the requested follow-up; it is not marketing consent, proof of payment, a confirmed booking or membership activation. Staff review Hub applications. Automated form validation, duplicate protection and date availability checks help operate the service but do not themselves approve membership or a function.'
 ]},
 {id:'sharing',title:'Who can receive information',paragraphs:[
  'Relevant service staff and authorised administrators can access the information needed for their duties. Hub requests are restricted by service role, with authorised owner oversight. Identity numbers and Functions enquiry details are encrypted in the Hub database. Signup notification emails omit the ID or passport number.',
  'Hosting and technical support, email and message delivery, payment and accounting providers may process information needed for their functions. Depending on the feature in use, these include hosting/mail services, Yoco for hosted payments, and configured email, SMS or WhatsApp delivery services. Card credentials are entered with the hosted payment provider, not into a Hub enquiry form; we use transaction references and status for reconciliation.',
  'Playtomic operates the external court-booking service. Following its link opens a separate service with its own terms and privacy information. Itensity is used for the Gym membership process completed with the team. A Hub request does not itself create a membership or activate access on either platform. The team can explain any further information needed before completing that setup.',
  'Disclosures to advisers, insurers, auditors, regulators, courts or law-enforcement bodies must be justified by the relevant service, legal obligation or claim. Providers acting on our instructions must be subject to appropriate confidentiality and security obligations. We do not sell your personal information or treat use of the Hub as permission for unrelated sharing.'
 ]},
 {id:'storage',title:'Retention, security and overseas processing',paragraphs:[
  'Optional delivery pins remain part of the order record under the order-retention arrangements below. They are not saved in your browser’s recent-order list. That list stores up to ten order references for thirty days on your device to restore tracking after you leave or reload; clearing this site’s browser data removes it. Anyone using the same browser profile may be able to view those saved references and the order status they unlock.',
  'Retention depends on the record and purpose. Enquiries and application details should be kept only for justified handling, follow-up, security and dispute needs. Order, payment and accounting records may need to remain for applicable legal and financial periods. Account and preference records support the ongoing service; limited evidence may remain after closure where lawfully necessary.',
  'There is no promise that every record is automatically deleted after a fixed number of days. Contact Mark for the retention position applicable to your record or to request deletion. Information no longer lawfully needed must be deleted or de-identified. Legal holds and necessary audit evidence are assessed separately. Backup expiry and deletion from external providers are separate from removal from the live Hub.',
  'We use access controls and secure connections and restrict staff handling of personal information. Keep your account credentials private and tell us promptly about suspected misuse. No online system can eliminate every risk. Security incidents must be assessed and reported to affected people and the Information Regulator where required by POPIA.',
  'Hosting, support, payment or communications providers may process information outside South Africa. Any transfer must have a lawful basis and the safeguards required by POPIA. Ask our privacy contact about the recipients, countries and protections relevant to the service you use; this notice does not claim that every provider stores all data in South Africa.'
 ]},
 {id:'device',title:'Cookies, app storage and messages',paragraphs:[
  'The app uses functional session cookies for sign-in and authorised access. Browser session storage helps prevent duplicate submissions and remembers whether an in-app promotion has already appeared. Staff devices can retain sound and notification preferences. Installing the PWA adds a convenient launch icon; it does not by itself subscribe you to marketing or grant access to your contacts or location.',
  'You can clear cookies and site data in your browser, although doing so may sign you out or reset preferences. Device notification permissions can be changed in the browser or operating-system settings. The current app does not include third-party advertising pixels or a cross-site advertising cookie programme. A separate notice and any required choice must accompany such tools if introduced.',
  'Order updates, verification codes and replies to your enquiry are service communications. Available order-notification channels are shown at checkout; an unavailable provider is not a promise of delivery. Promotional messaging requires a separate lawful basis and an opportunity to opt out. You can withdraw a marketing choice through the message instructions or our privacy contact without cancelling your underlying enquiry or account.'
 ]},
 {id:'sensitive',title:'Children and sensitive details',paragraphs:[
  'A parent or guardian should contact the relevant team before supplying a child’s details or arranging participation. Do not use a general enquiry field to submit children’s identity documents, health records or biometric information. If information has been submitted without proper authority, tell our privacy contact so it can be reviewed.',
  'For catering, discuss allergies and dietary requirements directly with FOND or Michelle before confirming an order or event. Give only the information necessary to handle the requirement, and avoid identifying guests where an anonymous dietary count is sufficient. Special personal information requires an appropriate lawful basis and safeguards.'
 ]},
 {id:'rights',title:'Your rights and complaints',paragraphs:[
  'You may request confirmation of information held about you, access, correction, or deletion where permitted; object to applicable processing; and withdraw consent for future consent-based use. Some records may lawfully need to remain. We will explain the reason if a request cannot be met in full. Reasonable identity and authority checks protect your records from disclosure to someone else.',
  'Write to legal@blendproperty.co.za, for Mark Corbishley, stating the service, your request and a safe contact method. Include an order or enquiry reference if available, but do not send passwords or verification codes. We will explain any formal access procedure, permissible fee or applicable extension. This privacy policy is not a PAIA manual; you can request assistance with formal access to records from the same contact.',
  'You may complain to the Information Regulator without first accepting our response. Its current complaint channels and forms are at inforegulator.org.za/complaints/. General enquiries: enquiries@inforegulator.org.za or 010 023 5200.'
 ]},
 {id:'updates',title:'Changes to this policy',paragraphs:[
  'The edition date identifies this notice. Material changes will be communicated through an appropriate channel. Updating a notice does not create consent for a new purpose where consent is required, or retrospectively change an agreement you already accepted.'
 ]},
];

export const termsSections: LegalSection[] = [
 {id:'operator',title:'The business and these terms',paragraphs:[
  'Midpoint Hub is operated by Blend Property 20 (Pty) Ltd, registration 2016/031577/07, at Midpoint, 162 Tonetti Street, Halfway House, Midrand, 1685, South Africa. “We”, “us” and “our” refer to that company for services it supplies through the Hub. “You” means the user or the customer, including an authorised business representative.',
  'These terms cover midpointhub.com and its installed web app, FOND online ordering, Hub enquiries and the information provided for Gym, Padel and Functions. Read them with the specific offer, checkout details, membership agreement or function proposal you accept. South African law applies. Mandatory consumer protections prevail over any inconsistent wording.',
  'General legal and privacy enquiries: legal@blendproperty.co.za, attention Mark Corbishley. Business telephone: +27 11 380 9400. VAT registration: 4720273152. Service enquiries go to Ray for FOND, Christine for Gym, Ali for Padel and Michelle for Functions using the contact links below. A separate provider’s terms apply to services that provider supplies, including Playtomic’s booking platform.'
 ]},
 {id:'using',title:'Using the app and your account',paragraphs:[
  'Provide accurate details and act only for yourself or someone you are authorised to represent. You must have legal capacity to enter the transaction; a parent or guardian should arrange participation for a minor with the relevant team. Keep contact details current so we can resolve order or booking issues.',
  'Protect passwords, sign-in codes and recovery codes. Do not use another person’s account, access private records without authority, bypass security, submit abusive or fraudulent requests or interfere with the service. Report suspected account misuse promptly. We may restrict access reasonably to address misuse or a security incident, without removing statutory rights or lawful access to your transaction records.'
 ]},
 {id:'fond',title:'FOND orders and acceptance',paragraphs:[
  'Check your items, quantities, options, collection or delivery choice, time and contact details before submitting. Menu images are illustrative. Availability and trading times shown in the app may change; placing an order sends it to FOND for handling. A received reference confirms receipt, while staff acceptance and payment status are separate steps.',
  'The app distinguishes received, accepted, preparing, ready and completed orders. A payment-provider redirect alone does not prove a successful payment or kitchen acceptance. Check the displayed order and payment result and contact Ray if it is unclear before paying again.',
  'If an item cannot be supplied, we will discuss an alternative or the appropriate refund for the unavailable item. We will not make a materially different substitution without agreement. Report incorrect, missing or unsafe food promptly with your reference so the team can investigate. Prompt reporting helps us resolve the issue; it does not remove a statutory remedy.',
  'Tell FOND about allergies or dietary requirements before ordering and obtain confirmation that your needs can be accommodated. A menu label or free-text note is not a guarantee that cross-contact is impossible. If the team cannot safely meet a requirement, do not proceed on the assumption that a substitute ingredient will solve it. This does not exclude our responsibility for food safety.'
 ]},
 {id:'payment',title:'Prices, payment and rewards',paragraphs:[
  'Prices are in South African rand. Review the full checkout or written quotation, including applicable tax, delivery charges and selected extras, before committing. Only the methods actually offered for your transaction are available. Where online payment is required, preparation or delivery may depend on payment confirmation.',
  'Hosted card payments are processed through the named payment provider. Never send card security codes, PINs, passwords or one-time codes by email. Report suspected duplicate or incorrect charges with the transaction reference. Refunds are reconciled through a verified appropriate payment method; provider processing time does not remove a legally required refund obligation.',
  'Collection payment applies only where offered. Delivery is limited to the locations, times and conditions offered by FOND and requires the information shown at checkout. A test or sandbox transaction is not a real settlement.',
  'Rewards and promotions apply only to the qualifying purchases, eligibility and redemption conditions disclosed with the offer. They are not cash or an automatic entitlement on every order. Correcting a cancelled, refunded or invalid qualifying transaction may affect the related reward. Offer changes must respect rights already acquired and mandatory law.'
 ]},
 {id:'fulfilment',title:'Collection, delivery and order changes',paragraphs:[
  'Collection estimates depend on the order and kitchen workload and are not a guaranteed minute of completion. Follow the live status and collection instructions. For delivery, supply a reachable telephone number and the correct company and building details. Contact the team promptly if you need to correct an address, time or order.',
  'Changes or cancellation requests should reach FOND as soon as possible. Preparation may already have started, so we must check what can reasonably be changed and explain any lawful charge. These terms do not impose a blanket no-refund rule. If we cannot supply an agreed service, we will address the appropriate alternative, price adjustment or refund.'
 ]},
 {id:'gym',title:'Gym membership, classes and events',paragraphs:[
  'A Hub signup is an application for staff follow-up. It does not take membership payment, conclude an Itensity membership, activate building access or reserve a place in a class. Christine’s team will explain the membership options, applicable charges, eligibility and steps needed to complete registration.',
  'Calendar entries provide the schedule entered by the team. Sending event interest is not a guaranteed place. Confirm availability, instructor arrangements, participation requirements and any charge with the team. Membership duration, renewal and cancellation are governed by the separate agreement presented before you join, subject to applicable law.',
  'Follow reasonable facility and instructor safety directions and use equipment as intended. Discuss any assistance you need privately with the team before participating. Nothing here is an injury waiver or an exclusion of liability that the law does not permit.'
 ]},
 {id:'padel',title:'Padel and Playtomic',paragraphs:[
  '“Book a court” opens Midpoint Padel on Playtomic. Court availability, checkout, payment and booking management take place there under the applicable venue and platform terms displayed before booking. Use the booking reference and the relevant channel for changes or cancellation; a Hub enquiry does not change an existing Playtomic booking.',
  'The Hub tenant form asks Ali’s team to review tenant setup. Submitting it does not create an entitlement to a discount, book a court or activate access. Tenant eligibility and any benefit must be confirmed. Event interest also requires team confirmation. External platform operation does not remove our responsibility for services we supply.'
 ]},
 {id:'functions',title:'Functions enquiries and confirmed arrangements',paragraphs:[
  'Choosing a date and submitting the Functions form sends Michelle’s team an enquiry. It is not a confirmed booking, price commitment or exclusive hold. An available date on the calendar is not a promise of capacity or suitability. Confirmed bookings block dates in the Hub calendar; pending enquiries do not reserve them.',
  'Before a function is agreed, the written proposal should set out the date and times, venue and capacity, guest count, menu and dietary arrangements, included services, price and tax, any deposit, payment dates, cancellation terms and the process for approving changes. A budget or gathering-style selection in the form is a starting point for discussion, not a binding menu or quotation.',
  'Confirm arrangements directly with Michelle and retain the agreed proposal. Additional guests, décor, equipment, entertainment or outside suppliers require agreement where relevant. No deposit percentage, minimum spend, cancellation scale or venue exclusivity is created by these general website terms.',
  'Tell Michelle promptly if you need to change or cancel. Any cancellation charge must be disclosed and lawful, taking account of the circumstances and applicable consumer rights. Where the Consumer Protection Act prohibits a charge because of qualifying death or hospitalisation, that protection applies. We will reconcile amounts paid and any lawful refund.'
 ]},
 {id:'rights',title:'Returns, cancellation and consumer rights',paragraphs:[
  'Your rights under the Consumer Protection Act and applicable electronic-transaction law remain intact. Different rules can apply to perishable or prepared food, personalised goods, and catering or leisure services booked for a specific date. A general change-of-mind cooling-off period should not be assumed to apply to every Hub transaction. This does not remove rights concerning defective, unsafe, incorrect or unsupplied goods or deficient services.',
  'Where a statutory cooling-off right applies, we will honour the applicable notice period and refund requirements. Contact the service team for the circumstances of your transaction. We will not make a statutory remedy dependent on a blanket “no refunds” rule or a manager’s unrestricted discretion. Reasonable proof of the transaction may be requested.',
  'We will explain the basis of any deduction and the handling of a disputed amount. You may pursue an available remedy with a competent regulator, ombud or court. These terms do not require compulsory private arbitration or waive lawful consumer jurisdiction.'
 ]},
 {id:'privacy',title:'Privacy and communications',paragraphs:[
  'Our Privacy policy explains collection, staff and provider access, security, retention and your rights. A request checkbox concerns handling that request. It is not consent to unrelated marketing, biometric enrolment or unrestricted sharing. Separate service-provider notices apply where relevant.',
  'Keep a copy of important requests and agreements. An automated acknowledgement is not a confirmed function, accepted membership or verified payment. If a time-sensitive message fails or you receive no response, contact the relevant team through another available channel. Do not assume an email or calendar invitation has been delivered solely because a form was submitted.'
 ]},
 {id:'availability',title:'Availability, content and responsibility',paragraphs:[
  'We take reasonable care with the app and its content but maintenance, connectivity problems and service interruptions can occur. Contact the team if an outage prevents a time-sensitive action. We will address material errors and interruptions fairly; a website correction does not retrospectively increase an accepted price.',
  'Website software, branding, illustrations and content belong to their respective rights holders. You may use the app and retain material needed for your transaction. Commercial copying or reuse requires permission or another lawful basis.',
  'Responsibility for loss is determined by applicable law and the circumstances. Nothing here excludes fraud, gross negligence, wilful misconduct or any liability or remedy that cannot lawfully be excluded. We do not use these terms to require a blanket indemnity for our own wrongdoing.'
 ]},
 {id:'complaints',title:'Complaints, changes and retained records',paragraphs:[
  'Contact the relevant service team with your reference, a description of the issue and the outcome you seek. Legal or unresolved concerns can be directed to legal@blendproperty.co.za for Mark Corbishley. We will investigate and seek a fair resolution. You may also approach the National Consumer Commission, an applicable ombud or a competent court; privacy complaints may be made to the Information Regulator.',
  'This edition applies to future use and transactions where incorporated. Later website edits do not rewrite an existing accepted agreement or remove accrued rights. A change to a confirmed arrangement must follow that agreement and applicable law. If a provision cannot lawfully operate, the remaining provisions continue only insofar as they can operate fairly. Save or print the terms and your transaction-specific records for reference.'
 ]},
];
