import {createOrder,recordPosEntry,updateOrderStatus,listCustomerOrders} from '../src/lib/orders';
import {prepareCounterOrderReceipt,counterOrderSummary,skipCounterOrder} from '../src/lib/counter-order';
import {recordPayment} from '../src/lib/business-data';
import {reconcileOrderRewards} from '../src/lib/loyalty';
import {test,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {getDb,resetDbForTests} from '../src/lib/db';
import {signUp} from '../src/lib/auth';
import {saveDocument,DEFAULT_SETTINGS} from '../src/lib/management';
import {saveProviderSecret} from '../src/lib/provider-secrets';
import {customerRewards,issueGift,reconcileBalance} from '../src/lib/loyalty';
import {memberCard,configureCounter,counterConfig,counterAvailable,previewCounter,awardCounter,pauseCounter,reverseCounter,rollbackCounter,syncCounterRefunds,type CounterSale} from '../src/lib/counter-rewards';
const realFetch=global.fetch;
let sales:CounterSale[];
const variants=[{id:'coffee-variant',name:'Cappuccino'}];
const date=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function sale(qty=2,patch:Partial<CounterSale>={}):CounterSale{return {id:randomUUID(),order_number:'123',status:'completed',currency:'ZAR',created_at:new Date().toISOString(),closed_at:new Date().toISOString(),location_id:'cafe',amounts:{net_amount:{amount:qty*3000,currency:'ZAR'},tip_amount:{amount:0,currency:'ZAR'}},payments:[{status:'approved',payment_method:'card',amount_excl_tip:{amount:qty*3000,currency:'ZAR'}}],line_items:[{id:'line1',variant_id:'coffee-variant',name:'Cappuccino',quantity:String(qty),net_amount:{amount:qty*3000,currency:'ZAR'}}],refunds:[],returns:[],...patch};}
function user(email='member@example.test'){const u=signUp(email,'safe-test-password').user;getDb().prepare('UPDATE users SET email_verified_at=? WHERE id=?').run(new Date().toISOString(),u.id);return {...u,code:memberCard(u.id).code};}
async function enabled(){await configureCounter({enabled:true,variants},'admin');}
async function quote(code:string){return previewCounter({memberCode:code,date:date(),number:sales[0].order_number});}
beforeEach(()=>{process.env.FOND_DB_PATH=':memory:';process.env.FOND_CREDENTIALS_KEY='a'.repeat(64);process.env.FOND_PUBLIC_URL='https://fond-test.mid-point.co.za';resetDbForTests();saveProviderSecret('yoco-secret','sk_test_fixture','test');saveProviderSecret('yoco-webhook','whsec_fixture','test');saveProviderSecret('yoco-pos-key','personal-business-key-fixture','test');saveDocument('trading',{...DEFAULT_SETTINGS,enforceHours:false,allowTestPayments:true},'test');saveDocument('yoco-pos',{enabled:false,environment:'sandbox',locationId:'cafe',eftMappingVerified:false},'test');sales=[sale()];global.fetch=async(url)=>new Response(JSON.stringify(String(url).includes('/v1/orders/?')?{data:sales,next_cursor:null}:sales.find(s=>String(url).endsWith(s.id))),{status:200});});
afterEach(()=>{global.fetch=realFetch;resetDbForTests();delete process.env.FOND_PUBLIC_URL;delete process.env.FOND_CREDENTIALS_KEY;});
test('trial starts paused; verified members get stable distinct codes; setup requires mapped items',async()=>{const a=user(),b=user('other@example.test');assert.notEqual(a.code,b.code);assert.equal(memberCard(a.id).code,a.code);assert.equal(counterAvailable(),false);await assert.rejects(quote(a.code),/paused/);await assert.rejects(configureCounter({enabled:true,variants:[]},'admin'),/select/);getDb().prepare('UPDATE users SET email_verified_at=NULL WHERE id=?').run(a.id);assert.throws(()=>memberCard(a.id),/Verify/);});
test('verified counter receipt adds item quantity once without creating orders or payments',async()=>{const u=user();await enabled();const q=await quote(u.code);assert.equal(q.quantity,2);const results=await Promise.all([awardCounter(q,'staff:one'),awardCounter(q,'staff:two')]);assert.equal(results.filter(r=>r.alreadyAdded).length,1);assert.equal(customerRewards(u.id,'test').stamps,2);assert.equal(customerRewards(u.id,'live').stamps,0);assert.equal(getDb().prepare('SELECT count(*) n FROM orders').get()?.n,0);assert.equal(getDb().prepare('SELECT count(*) n FROM payment_records').get()?.n,0);await assert.rejects(quote(u.code),/already/);});
test('a receipt cannot move to a second member and tampered confirmation cannot change quantity',async()=>{const a=user(),b=user('b@example.test');await enabled();const q=await quote(a.code);await assert.rejects(awardCounter({...q,quantity:99},'staff'),/changed/);await awardCounter(q,'staff');await assert.rejects(awardCounter({...q,memberCode:b.code},'staff'),/already/);});
test('daily reused display number earns only for distinct Yoco IDs, correct date and location',async()=>{const u=user();await enabled();await awardCounter(await quote(u.code),'staff');sales=[sale()];await awardCounter(await quote(u.code),'staff');assert.equal(customerRewards(u.id,'test').stamps,4);sales[0].location_id='other';await assert.rejects(quote(u.code),/No Yoco/);sales[0].location_id='cafe';sales[0].closed_at='2020-01-01T10:00:00Z';await assert.rejects(quote(u.code),/No Yoco/);});
test('ambiguous receipts, refunds, free and fractional items, EFT closures and FOND notes fail closed',async()=>{const u=user();await enabled();sales.push(sale());await assert.rejects(quote(u.code),/More than one/);for(const patch of [{refunds:[{}]},{returns:[{}]},{note:'FOND 100000'},{external_id:'app-1'},{channel:'uber_eats'},{status:'open'}]){sales=[sale(2,patch)];await assert.rejects(quote(u.code));}sales=[sale()];sales[0].payments![0].payment_method='other';await assert.rejects(quote(u.code),/cash\/card/);sales=[sale()];sales[0].line_items![0].net_amount.amount=0;await assert.rejects(quote(u.code),/No qualifying/);sales=[sale()];sales[0].line_items![0].quantity='1.5';await assert.rejects(quote(u.code),/item details/);});
test('ten stamps issue one reward; reversal revokes unused earned code and keeps gift and app credits',async()=>{const u=user();getDb().prepare('INSERT INTO loyalty_orders (order_id,user_id,environment,quantity,credited) VALUES (?,?,?,?,?)').run('prior-app',u.id,'test',3,3);issueGift({email:u.email,environment:'test',reason:'Gift',requestKey:randomUUID(),emailEnabled:false,smsEnabled:false,phone:''},'admin');sales=[sale(7)];await enabled();const r=await awardCounter(await quote(u.code),'staff');assert.equal(customerRewards(u.id,'test').rewards.filter(r=>r.kind==='earned'&&r.status==='available').length,1);reverseCounter(r.id,'Wrong receipt','admin');assert.equal(customerRewards(u.id,'test').stamps,3);assert.equal(customerRewards(u.id,'test').rewards.find(r=>r.kind==='gift')?.status,'available');assert.equal(customerRewards(u.id,'test').rewards.find(r=>r.kind==='earned')?.status,'revoked');await assert.rejects(quote(u.code),/already/);});
test('rollback pauses and reverses all counter batches while preserving spent reward debt and audit',async()=>{const u=user();sales=[sale(10)];await enabled();await awardCounter(await quote(u.code),'staff');getDb().prepare("UPDATE loyalty_rewards SET status='redeemed' WHERE kind='earned'").run();assert.equal(rollbackCounter('Trial stopped','admin').reversed,1);assert.equal(counterAvailable(),false);assert.equal(customerRewards(u.id,'test').stampsToNext,20);assert.equal(rollbackCounter('Repeated rollback','admin').reversed,0);assert.equal(getDb().prepare("SELECT count(*) n FROM loyalty_events WHERE action='counter-stamps-reversed'").get()?.n,1);await enabled();await assert.rejects(quote(u.code),/already/);});
test('pause and key rotation invalidate an in-flight receipt lookup and existing preview',async()=>{const u=user();await enabled();const q=await quote(u.code);pauseCounter('admin');await assert.rejects(awardCounter(q,'staff'),/paused/);await enabled();const original=global.fetch;global.fetch=async(...args)=>{pauseCounter('admin');return original(...args);};await assert.rejects(quote(u.code),/changed/);global.fetch=original;await enabled();saveProviderSecret('yoco-pos-key','replacement-personal-business-key','admin');assert.equal(counterAvailable(),false);});
test('refund check reverses credits even while paused; failed provider checks retain evidence and credit',async()=>{const u=user();await enabled();const result=await awardCounter(await quote(u.code),'staff');pauseCounter('admin');global.fetch=async()=>new Response('unavailable',{status:503});await syncCounterRefunds();assert.equal(customerRewards(u.id,'test').stamps,2);assert.ok(getDb().prepare('SELECT check_error FROM counter_reward_sales WHERE id=?').get(result.id)?.check_error);sales[0].refunds=[{}];global.fetch=async()=>new Response(JSON.stringify(sales[0]));getDb().prepare('UPDATE counter_reward_sync SET next_run=0').run();await syncCounterRefunds();assert.equal(customerRewards(u.id,'test').stamps,0);});
test('rollback works after email verification is withdrawn and cancels available earned entitlement',async()=>{const u=user();sales=[sale(10)];await enabled();await awardCounter(await quote(u.code),'staff');getDb().prepare('UPDATE users SET email_verified_at=NULL WHERE id=?').run(u.id);rollbackCounter('Account withdrawn','admin');assert.equal(getDb().prepare("SELECT status FROM loyalty_rewards WHERE kind='earned'").get()?.status,'revoked');});
test('failed later page adds nothing and receipt check does not leak provider response',async()=>{const u=user();await enabled();let calls=0;global.fetch=async()=>++calls===1?new Response(JSON.stringify({data:sales,next_cursor:'next'})):new Response('SECRET provider response',{status:500});await assert.rejects(quote(u.code),e=>e instanceof Error&&!e.message.includes('SECRET'));assert.equal(customerRewards(u.id,'test').stamps,0);});
test('an administrator pause wins over an in-flight enable request',async()=>{global.fetch=async()=>{pauseCounter('other-admin');return new Response(JSON.stringify({data:sales}));};await assert.rejects(enabled(),/Settings changed/);assert.equal(counterAvailable(),false);});
test('nested payment refunds are rejected and re-verification during award prevents withdrawn account credit',async()=>{const u=user();await enabled();(sales[0].payments![0] as any).refunded_amount={amount:1,currency:'ZAR'};await assert.rejects(quote(u.code),/refund/);sales=[sale()];const q=await quote(u.code);global.fetch=async()=>{getDb().prepare('UPDATE users SET email_verified_at=NULL WHERE id=?').run(u.id);return new Response(JSON.stringify({data:sales}));};await assert.rejects(awardCounter(q,'staff'),/Membership unavailable/);assert.equal(getDb().prepare('SELECT count(*) n FROM counter_reward_sales').get()?.n,0);});


function linkedOrder(code:string,qty=1){return createOrder({source:'staff',customerName:'Counter practice',contactNumber:'0821234567',collectionTime:'ASAP',membershipCode:code,rewardEnvironment:'test',lines:[{id:'espresso-single',quantity:qty}]});}
function matchingSale(o:ReturnType<typeof linkedOrder>){sales=[sale(o.lines[0].quantity,{note:'FOND '+o.staffNumber,amounts:{net_amount:{amount:o.totalCents,currency:'ZAR'},tip_amount:{amount:0,currency:'ZAR'}},payments:[{status:'approved',payment_method:'card',amount_excl_tip:{amount:o.totalCents,currency:'ZAR'}}]})];}
async function verifyOrder(o:ReturnType<typeof linkedOrder>){recordPosEntry(o.id,sales[0].order_number,'staff',await prepareCounterOrderReceipt(o.id,sales[0].order_number,date(),'staff'));}
function collect(o:ReturnType<typeof linkedOrder>){updateOrderStatus(o.id,'ready');recordPayment({orderId:o.id,amountCents:o.totalCents,method:'card',reference:randomUUID()},'staff');updateOrderStatus(o.id,'completed');}
test('linked staff membership earns once only after matching receipt, payment and collection; reward can be redeemed',async()=>{
 const u=user();await enabled();const o=linkedOrder(u.code,10);assert.equal(o.userId,u.id);assert.equal(listCustomerOrders(u.id).length,1);assert.equal(customerRewards(u.id,'test').stamps,0);
 matchingSale(o);await verifyOrder(o);assert.ok(counterOrderSummary(o.id)?.saleId);assert.equal(customerRewards(u.id,'test').stamps,0);assert.equal(getDb().prepare('SELECT count(*) n FROM payment_records').get()?.n,0);
 updateOrderStatus(o.id,'ready');assert.throws(()=>updateOrderStatus(o.id,'completed'),/payment/);recordPayment({orderId:o.id,amountCents:o.totalCents,method:'card',reference:randomUUID()},'staff');assert.equal(customerRewards(u.id,'test').stamps,0);updateOrderStatus(o.id,'completed');reconcileOrderRewards(o.id);
 const r=customerRewards(u.id,'test').rewards;assert.equal(r.length,1);assert.equal(r[0].status,'available');await assert.rejects(quote(u.code),/FOND|recorded/);
 const free=createOrder({source:'staff',customerName:'Free',contactNumber:'0821234567',collectionTime:'ASAP',staffRewardCode:String(r[0].code),rewardEnvironment:'test',lines:[{id:'espresso-single',quantity:1}]});assert.equal(free.totalCents,0);recordPosEntry(free.id,'free-receipt','staff');updateOrderStatus(free.id,'ready');updateOrderStatus(free.id,'completed');assert.equal(customerRewards(u.id,'test').rewards[0].status,'redeemed');
});
test('receipt mismatch, missing FOND note, paused and stale verification cannot record POS or reserve stamps',async()=>{
 const u=user();await enabled();const o=linkedOrder(u.code);matchingSale(o);sales[0].note='FOND 999999';await assert.rejects(verifyOrder(o),/match/);sales[0].note='FOND '+o.staffNumber;sales[0].amounts.net_amount.amount++;await assert.rejects(verifyOrder(o));matchingSale(o);const verify=await prepareCounterOrderReceipt(o.id,'123',date(),'staff');pauseCounter('admin');assert.throws(()=>recordPosEntry(o.id,'123','staff',verify),/settings/);assert.equal(counterOrderSummary(o.id)?.saleId,null);assert.equal(getDb().prepare('SELECT pos_reference FROM orders WHERE id=?').get(o.id)?.pos_reference,null);
});
test('rollback reverses pending linked receipt and re-enabling never resurrects it',async()=>{
 const u=user();await enabled();const o=linkedOrder(u.code);matchingSale(o);await verifyOrder(o);assert.equal(rollbackCounter('Stop practice','admin').reversed,1);await enabled();collect(o);assert.equal(customerRewards(u.id,'test').stamps,0);assert.ok(counterOrderSummary(o.id)?.reversedAt);
});
test('linked order cancellation and later payment refund reverse credits',async()=>{
 const u=user();await enabled();const a=linkedOrder(u.code);matchingSale(a);await verifyOrder(a);updateOrderStatus(a.id,'cancelled');assert.ok(counterOrderSummary(a.id)?.reversedAt);
 const b=linkedOrder(u.code);matchingSale(b);sales[0].order_number='456';await verifyOrder(b);collect(b);assert.equal(customerRewards(u.id,'test').stamps,1);recordPayment({orderId:b.id,amountCents:b.totalCents,method:'refund',reference:randomUUID()},'admin');assert.equal(customerRewards(u.id,'test').stamps,0);
});
test('membership validation rejects customer route, wrong member and reward-code combination',()=>{
 const u=user();assert.throws(()=>linkedOrder('FOND-M-AAAAAAAAAAAA'));assert.throws(()=>createOrder({source:'customer',customerName:'No',contactNumber:'0821234567',collectionTime:'ASAP',membershipCode:u.code,rewardEnvironment:'test',lines:[{id:'espresso-single',quantity:1}]}),/staff/);assert.equal(getDb().prepare('SELECT count(*) n FROM orders').get()?.n,0);
});

test('staff can explicitly continue without stamps when counter rewards are paused',()=>{
 const u=user(),o=linkedOrder(u.code);recordPosEntry(o.id,'plain-receipt','staff',()=>skipCounterOrder(o.id,'staff'));collect(o);assert.equal(counterOrderSummary(o.id),undefined);assert.equal(customerRewards(u.id,'test').stamps,0);assert.equal(listCustomerOrders(u.id).length,1);
});
