import {test,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {getDb,resetDbForTests} from '../src/lib/db';
import {signUp} from '../src/lib/auth';
import {createOrder,recordPosEntry,updateOrderStatus} from '../src/lib/orders';
import {recordPayment} from '../src/lib/business-data';
import {issueGift,customerRewards,quoteReward,quoteCounterReward,saveRewardPreferences,reconcileOrderRewards,sendCustomerReward,revokeGift} from '../src/lib/loyalty';
import {getAvailableMenu} from '../src/lib/menu-store';
import {saveProviderSecret} from '../src/lib/provider-secrets';
import {saveDocument} from '../src/lib/management';
import {processRewardMessages} from '../src/lib/loyalty-messages';
process.env.FOND_DB_PATH=':memory:';
beforeEach(resetDbForTests);
function customer(email='coffee@example.com'){const u=signUp(email,'safe-test-password').user;getDb().prepare('UPDATE users SET email_verified_at=? WHERE id=?').run(new Date().toISOString(),u.id);return u;}
function order(userId:string,qty=10,extra:Record<string,unknown>={}){return createOrder({customerName:'Coffee test',contactNumber:'0821234567',collectionTime:'ASAP',source:'customer',userId,rewardEnvironment:'test',lines:[{id:'espresso-single',quantity:qty}],...extra});}
function complete(o:ReturnType<typeof order>){if(o.status==='received')updateOrderStatus(o.id,'accepted');recordPosEntry(o.id,randomUUID(),'test');updateOrderStatus(o.id,'ready');if(o.totalCents)recordPayment({orderId:o.id,amountCents:o.totalCents,method:'cash',reference:randomUUID()},'test');updateOrderStatus(o.id,'completed');}
function gift(email:string,extra:Record<string,unknown>={}){return issueGift({email,environment:'test',reason:'Test gift',requestKey:randomUUID(),emailEnabled:false,smsEnabled:false,phone:'',...extra},'admin:test');}
test('ten individual app coffees earn exactly one reward only after payment and completion',()=>{const u=customer();const a=order(u.id,6);complete(a);assert.equal(customerRewards(u.id,'test').stamps,6);const b=order(u.id,4);assert.equal(customerRewards(u.id,'test').rewards.length,0);complete(b);reconcileOrderRewards(b.id);assert.equal(customerRewards(u.id,'test').rewards.length,1);assert.equal(customerRewards(u.id,'test').stamps,0);assert.equal(getDb().prepare('SELECT count(*) n FROM loyalty_events WHERE action=?').get('issued')?.n,1);});
test('counter, guest, unverified and legacy orders do not earn app rewards; live and test stay separate',()=>{const u=customer();complete(order(u.id,10,{source:'staff'}));complete(order(u.id,10,{userId:undefined}));complete(order(u.id,10,{rewardEnvironment:undefined}));const unverified=signUp('unverified@example.com','safe-test-password').user;complete(order(unverified.id,10));assert.equal(customerRewards(u.id,'test').rewards.length,0);complete(order(u.id,10));assert.equal(customerRewards(u.id,'live').rewards.length,0);});
test('codes bind to a verified account and environment and require a Coffee item',()=>{const u=customer(),other=customer('other@example.com'),r=gift(u.email),menu=getAvailableMenu();assert.throws(()=>quoteReward(other.id,'test',r.code,[{id:'espresso-single',quantity:1}],menu));assert.throws(()=>quoteReward(u.id,'live',r.code,[{id:'espresso-single',quantity:1}],menu));assert.throws(()=>quoteReward(u.id,'test',r.code,[{id:'smashed-avo',quantity:1}],menu));getDb().prepare('UPDATE users SET email_verified_at=NULL WHERE id=?').run(u.id);assert.throws(()=>quoteReward(u.id,'test',r.code,[{id:'espresso-single',quantity:1}],menu),/verify/);});
test('gift issuance and order submission are idempotent; reservation prevents a second order',()=>{const u=customer(),requestKey=randomUUID(),r=gift(u.email,{requestKey});assert.equal(gift(u.email,{requestKey}).id,r.id);const submissionKey=randomUUID();const a=order(u.id,1,{rewardCode:r.code,submissionKey});assert.equal(a.totalCents,0);assert.equal(order(u.id,1,{rewardCode:r.code,submissionKey}).id,a.id);assert.throws(()=>order(u.id,1,{rewardCode:r.code}));assert.equal(getDb().prepare('SELECT count(*) n FROM payment_records').get()?.n,0);updateOrderStatus(a.id,'cancelled');const next=order(u.id,1,{rewardCode:r.code});complete(next);assert.equal(customerRewards(u.id,'test').rewards[0].status,'redeemed');assert.equal(customerRewards(u.id,'test').stamps,0);assert.throws(()=>order(u.id,1,{rewardCode:r.code}));});
test('highest priced Coffee base item is free and modifiers and other coffees remain payable',()=>{const u=customer(),r=gift(u.email),menu=getAvailableMenu();const items=menu.filter(m=>m.category==='Coffee').sort((a,b)=>b.price-a.price);const expensive=items[0],cheap=items[items.length-1];const lines=[{id:cheap.id,quantity:2},{id:expensive.id,quantity:1}];const q=quoteReward(u.id,'test',r.code,lines,menu);assert.equal(q.discountCents,expensive.price);const a=order(u.id,1,{rewardCode:r.code,lines});assert.equal(a.totalCents,cheap.price*2);assert.equal(a.lines[1].subtotalCents,0);complete(a);assert.equal(customerRewards(u.id,'test').stamps,2);});
test('refunds revoke unspent earned rewards and carry spent reward debt forward without duplicate issuance',()=>{const u=customer(),a=order(u.id,10);complete(a);recordPayment({orderId:a.id,amountCents:1,method:'refund',reference:randomUUID()},'finance');assert.equal(customerRewards(u.id,'test').rewards[0].status,'revoked');const b=order(u.id,10);complete(b);const reward=customerRewards(u.id,'test').rewards.find(r=>r.status==='available')!;const free=order(u.id,1,{rewardCode:String(reward.code)});complete(free);recordPayment({orderId:b.id,amountCents:1,method:'refund',reference:randomUUID()},'finance');assert.equal(customerRewards(u.id,'test').stampsToNext,20);complete(order(u.id,10));assert.equal(customerRewards(u.id,'test').rewards.filter(r=>r.status==='available').length,0);complete(order(u.id,10));assert.equal(customerRewards(u.id,'test').rewards.filter(r=>r.status==='available').length,1);});
test('earned code notifications are opt-in, deduplicated, and remain pending without providers',async()=>{const u=customer();saveRewardPreferences(u.id,{email:true,sms:true,phone:'0821234567'});const a=order(u.id,10);complete(a);reconcileOrderRewards(a.id);assert.equal(getDb().prepare('SELECT count(*) n FROM loyalty_messages').get()?.n,2);await processRewardMessages();assert.equal(getDb().prepare("SELECT count(*) n FROM loyalty_messages WHERE status='pending'").get()?.n,2);saveRewardPreferences(u.id,{email:false,sms:false,phone:''});await processRewardMessages();assert.equal(getDb().prepare("SELECT count(*) n FROM loyalty_messages WHERE status='cancelled'").get()?.n,2);saveRewardPreferences(u.id,{email:true,sms:true,phone:'0821234568'});sendCustomerReward(u.id,String(customerRewards(u.id,'test').rewards[0].id));assert.equal(getDb().prepare("SELECT count(*) n FROM loyalty_messages WHERE status='pending'").get()?.n,2);assert.equal(getDb().prepare("SELECT recipient FROM loyalty_messages WHERE channel='sms'").get()?.recipient,'+27821234568');});

test('paid extras stay payable and unspent gift revocation does not affect earned rewards',()=>{const u=customer(),r=gift(u.email);getAvailableMenu();getDb().prepare('UPDATE menu_items SET modifiers_json=? WHERE id=?').run(JSON.stringify([{id:'extra-shot',name:'Extra shot',price:1200}]),'espresso-single');const a=order(u.id,1,{rewardCode:r.code,lines:[{id:'espresso-single',quantity:1,modifierIds:['extra-shot']}]});assert.equal(a.totalCents,1200);assert.throws(()=>revokeGift(r.id,'admin'));updateOrderStatus(a.id,'cancelled');revokeGift(r.id,'admin');assert.throws(()=>order(u.id,1,{rewardCode:r.code}));});
test('code notifications call both providers once and preserve uncertain SMS results for review',async()=>{process.env.FOND_CREDENTIALS_KEY='ab'.repeat(32);const u=customer();saveProviderSecret('email-api','re_test-provider-secret-not-real','test');saveProviderSecret('twilio-auth-token','a'.repeat(32),'test');saveDocument('email-from','orders@fond.mid-point.co.za','test');saveDocument('twilio-sms-config',{accountSid:'AC'+'a'.repeat(32),sender:'+27600928520'},'test');const r=gift(u.email);saveRewardPreferences(u.id,{email:true,sms:true,phone:'0821234567'});sendCustomerReward(u.id,r.id);sendCustomerReward(u.id,r.id);const original=global.fetch;const calls:string[]=[];global.fetch=async(url,init)=>{calls.push(String(url));assert.match(String(init?.body),/COFFEE/);return new Response(JSON.stringify(String(url).includes('resend')?{id:'email-test'}:{sid:'sms-test',status:'queued'}),{status:200});};try{await Promise.all([processRewardMessages(),processRewardMessages()]);await processRewardMessages();assert.equal(calls.length,2);assert.equal(getDb().prepare("SELECT count(*) n FROM loyalty_messages WHERE status='provider-accepted'").get()?.n,2);const second=gift(u.email,{smsEnabled:true,phone:'0821234567'});global.fetch=async()=>{throw new Error('timeout');};await processRewardMessages();assert.equal(getDb().prepare('SELECT status FROM loyalty_messages WHERE reward_id=?').get(second.id)?.status,'unconfirmed');await processRewardMessages();}finally{global.fetch=original;}});

test('counter redemption reserves one verified code, links the account and never earns stamps',()=>{
 const u=customer(),r=gift(u.email),menu=getAvailableMenu();const lines=[{id:'espresso-single',quantity:3}];
 const quote=quoteCounterReward('test',r.code,lines,menu);assert.equal(quote.userId,u.id);
 const key=randomUUID();const input={source:'staff' as const,customerName:'Counter reward',contactNumber:'0821234567',collectionTime:'ASAP',lines,staffRewardCode:r.code,rewardEnvironment:'test' as const,submissionKey:key,actor:'team:operator'};
 const a=createOrder(input);assert.equal(a.userId,u.id);assert.equal(a.totalCents,quote.totalCents);assert.equal(a.status,'accepted');assert.equal(createOrder(input).id,a.id);
 assert.throws(()=>quoteCounterReward('test',r.code,lines,menu));assert.throws(()=>order(u.id,1,{rewardCode:r.code}));
 assert.equal(getDb().prepare("SELECT actor FROM loyalty_events WHERE action='reserved-at-counter'").get()?.actor,'team:operator');
 assert.throws(()=>updateOrderStatus(a.id,'ready'),/Yoco/);complete(a);assert.equal(customerRewards(u.id,'test').stamps,0);assert.equal(customerRewards(u.id,'test').rewards[0].status,'redeemed');
});
test('counter code cancellation releases once; invalid identity, mode and customer bypass are rejected',()=>{
 const u=customer(),r=gift(u.email),menu=getAvailableMenu(),lines=[{id:'espresso-single',quantity:1}];
 assert.throws(()=>quoteCounterReward('live',r.code,lines,menu));assert.throws(()=>order(u.id,1,{staffRewardCode:r.code}));
 getDb().prepare('UPDATE users SET email_verified_at=NULL WHERE id=?').run(u.id);assert.throws(()=>quoteCounterReward('test',r.code,lines,menu));getDb().prepare('UPDATE users SET email_verified_at=? WHERE id=?').run(new Date().toISOString(),u.id);
 const a=createOrder({source:'staff',customerName:'Counter',contactNumber:'0821234567',collectionTime:'ASAP',lines,staffRewardCode:r.code,rewardEnvironment:'test'});assert.equal(a.totalCents,0);assert.equal(getDb().prepare('SELECT count(*) n FROM payment_records').get()?.n,0);updateOrderStatus(a.id,'cancelled');assert.equal(quoteCounterReward('test',r.code,lines,menu).discountCents,menu.find(m=>m.id==='espresso-single')!.price);
 revokeGift(r.id,'admin');assert.throws(()=>createOrder({source:'staff',customerName:'Counter',contactNumber:'0821234567',collectionTime:'ASAP',lines,staffRewardCode:r.code,rewardEnvironment:'test'}));assert.equal(getDb().prepare('SELECT count(*) n FROM orders').get()?.n,1);
});

test('guest email earns coffee quantities without a session; claim is idempotent and refunds reverse',()=>{
 const u=customer();const a=order(u.id,4,{userId:undefined,customerEmail:'  COFFEE@EXAMPLE.COM  ',emailOptIn:false});
 assert.equal(a.userId,null);assert.equal(customerRewards(u.id,'test').stamps,0);
 complete(a);assert.equal(customerRewards(u.id,'test').stamps,4);assert.equal(customerRewards(u.id,'test').stamps,4);
 assert.equal(customerRewards(u.id,'live').stamps,0);
 recordPayment({orderId:a.id,amountCents:1,method:'refund',reference:randomUUID()},'finance');
 assert.equal(customerRewards(u.id,'test').stamps,0);
});
test('guest stamps survive until account creation and email verification, then issue one reward',()=>{
 const email='later@example.com';const a=order('',10,{userId:undefined,customerEmail:email});complete(a);
 assert.equal(getDb().prepare('SELECT count(*) n FROM loyalty_orders WHERE order_id=?').get(a.id)?.n,0);
 const u=customer(email);assert.equal(customerRewards(u.id,'test').rewards.length,1);
 assert.equal(customerRewards(u.id,'test').rewards.length,1);
});
