import {test,expect} from '@playwright/test';

test('sign-in and registration have inviting customer styling and a loaded coffee promotion',async({page},info)=>{
 await page.route('**/api/auth/session',r=>r.fulfill({json:{user:null}}));await page.goto('/account');
 const promo=page.getByRole('complementary',{name:'Coffee rewards promotion'});await expect(promo).toBeVisible();const image=promo.getByRole('img');await expect(image).toBeVisible();expect(await image.evaluate((el:HTMLImageElement)=>el.complete&&el.naturalWidth>0)).toBe(true);
 await expect(page.getByRole('heading',{name:'Sign in',exact:true})).toBeVisible();expect(await page.getByLabel('Email',{exact:true}).evaluate(el=>getComputedStyle(el).fontSize)).toBe('16px');expect(await page.getByRole('heading',{level:1}).evaluate(el=>getComputedStyle(el).color)).toBe('rgb(22, 54, 47)');
 await page.screenshot({path:info.outputPath('account-sign-in.png'),fullPage:true});await page.getByRole('button',{name:'Create an account',exact:true}).click();await expect(page.getByRole('heading',{name:'Create an account',exact:true})).toBeVisible();await expect(page.getByText('Choose at least 8 characters.',{exact:false})).toBeVisible();await page.screenshot({path:info.outputPath('account-register.png'),fullPage:true});
 await page.route('**/api/auth/signup',r=>r.abort());await page.getByLabel('Email',{exact:true}).fill('preview@example.test');await page.getByLabel('Password',{exact:true}).fill('preview-password');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page.getByRole('main').getByRole('alert')).toBeVisible();await expect(page.getByRole('button',{name:'Create account',exact:true})).toBeEnabled();
 await page.setViewportSize({width:320,height:740});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(promo).toBeVisible();
});

test('verification has separated steps, padded controls and a working transition to the account',async({page},info)=>{
 let verified=false;await page.route('**/api/auth/session',r=>r.fulfill({json:{user:{id:'layout',email:'customer@example.test',emailVerified:verified}}}));await page.route('**/api/account/orders',r=>r.fulfill({json:{orders:[]}}));
 await page.route('**/api/account/verification',r=>{if(r.request().method()==='PATCH'){verified=true;return r.fulfill({json:{ok:true}});}return r.fulfill({json:{ok:true}});});
 await page.goto('/account');const verify=page.getByRole('region',{name:'Verify your email',exact:true});await expect(verify).toBeVisible();expect(await verify.evaluate(el=>parseFloat(getComputedStyle(el).paddingLeft))).toBeGreaterThanOrEqual(22);await expect(verify.getByRole('button',{name:'Verify email',exact:true})).toBeDisabled();
 await verify.getByRole('button',{name:'Send verification code'}).click();await expect(verify.getByRole('status')).toContainText('Check your inbox');await verify.getByLabel('Six digit code').fill('123456');const input=await verify.getByLabel('Six digit code').boundingBox(),button=await verify.getByRole('button',{name:'Verify email',exact:true}).boundingBox();expect(button!.y-(input!.y+input!.height)).toBeGreaterThanOrEqual(19);
 await page.screenshot({path:info.outputPath('account-verify.png'),fullPage:true});await page.setViewportSize({width:320,height:740});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await verify.getByRole('button',{name:'Verify email',exact:true}).click();await expect(verify).not.toBeVisible();await expect(page.getByText('Email verified',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Explore the menu'})).toBeVisible();await page.screenshot({path:info.outputPath('account-empty-320.png'),fullPage:true});
});
