import {test,expect} from '@playwright/test';
test('service and profile screens share navigation, readable headings and responsive layout',async({page},info)=>{
 test.setTimeout(120000);
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:844});for(const route of ['/padel','/padel/prices','/padel/info','/padel/signup','/padel/events','/functions','/functions/enquire','/functions/spaces','/functions/packages','/functions/michelle','/functions/gallery','/profile','/profile/orders','/profile/rewards','/profile/details','/profile/bookings','/profile/memberships','/profile/notifications','/profile/help']){await page.goto(route);await expect(page.getByRole('heading',{level:1})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route+' at '+width).toBe(true);const nav=page.getByRole('navigation',{name:'App navigation'});const bounds=await nav.boundingBox();expect(bounds!.y+bounds!.height).toBeLessThanOrEqual(845);await expect(nav.getByRole('link',{name:'Home',exact:true})).toBeVisible();}}
 await page.goto('/functions');await expect(page.locator('a[href="/functions/enquire"]')).toHaveCount(1);await page.getByRole('link',{name:'Plan an event',exact:true}).click();await expect(page.getByRole('button',{name:'Request this date'})).toBeVisible();await page.goto('/profile');await page.getByRole('link',{name:/Coffee rewards/}).click();await expect(page).toHaveURL(/profile\/rewards/);await page.goto('/fond');await expect(page.getByRole('link',{name:'Your profile & rewards'})).toHaveAttribute('href','/profile');await expect(page.locator('a[href="/rewards"]')).toHaveCount(0);
 await page.goto('/functions/michelle');await expect(page.getByRole('heading',{name:'Meet Michelle Strydom.',exact:true})).toHaveCount(1);await page.screenshot({path:info.outputPath('michelle.png'),fullPage:true});
});
test('Profile shows only current account data and keeps real reward QR redemption',async({page})=>{
 let signed=true;await page.route('**/api/auth/session',r=>r.fulfill({json:{user:signed?{id:'fixture',email:'member@example.test',emailVerified:true}:null}}));await page.route('**/api/account/security',r=>r.fulfill({json:{enabled:false,channels:{},recoveryCodesRemaining:0}}));await page.route('**/api/account/rewards',r=>r.fulfill({json:{verified:true,environment:'test',stamps:7,stampsToNext:3,rewards:[{id:'reward-fixture',code:'FOND-TEST-FIXTURE',status:'available',kind:'earned'}],preferences:{email_enabled:false,sms_enabled:false}}}));await page.route('**/api/auth/logout',r=>{signed=false;return r.fulfill({json:{ok:true}});});
 await page.goto('/profile');await expect(page.getByText('member@example.test',{exact:true})).toBeVisible();await expect(page.getByText('Practice rewards · 1 reward available')).toBeVisible();await page.getByRole('link',{name:/Coffee rewards/}).click();await expect(page.locator('.coffee-ticket')).toContainText('7');await page.getByRole('button',{name:/Show.*code/i}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByAltText('Free coffee redemption QR code')).toBeVisible();await page.getByRole('button',{name:'Close reward code'}).click();await page.goto('/profile');await page.getByRole('button',{name:'Log out',exact:true}).click();await expect(page.getByRole('button',{name:'Sign in',exact:true})).toBeVisible();await expect(page.getByText('member@example.test',{exact:true})).toHaveCount(0);
});

