import {test,expect} from '@playwright/test';
test('gift codes require admin and can be issued without sending and revoked',async({page,request},info)=>{
 expect((await request.get('/api/admin/rewards')).status()).toBe(403);expect((await request.get('/api/account/rewards')).status()).toBe(401);
 await page.goto('/admin');await page.getByLabel('Admin access code').fill(process.env.FOND_ADMIN_CODE!);await page.getByRole('button',{name:'Unlock',exact:true}).click();await page.getByRole('button',{name:'Marketing & CMS',exact:true}).click();
 const panel=page.locator('.coffee-rewards');await expect(panel).toContainText('TEST codes');await panel.getByLabel('Gift recipient email').fill(`gift-${info.project.name}@example.test`);await panel.getByLabel('Gift reason').fill('Automated isolated gift test');await panel.getByLabel('Email this code').uncheck();await panel.getByRole('button',{name:'Issue free-coffee gift code'}).click();await expect(panel.getByRole('status')).toContainText('COFFEE-');
 const gift=panel.locator('p').filter({hasText:`gift-${info.project.name}@example.test`});await expect(gift).toContainText('available');await gift.getByRole('button',{name:'Revoke unused gift'}).click();await expect(gift).toContainText('revoked');
 const denied=await page.evaluate(async()=>{const r=await fetch('/api/admin/rewards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'gift',email:'bad'})});return r.status;});expect(denied).toBe(400);
});
test('customer account shows reward ownership, test mode and notification preferences',async({page},info)=>{
 await page.route('**/api/auth/session',r=>r.fulfill({json:{user:{id:'fixture',email:'customer@example.test',emailVerified:true}}}));await page.route('**/api/account/orders',r=>r.fulfill({json:{orders:[]}}));
 await page.route('**/api/account/rewards',async r=>{if(r.request().method()==='POST')return r.fulfill({json:{ok:true}});return r.fulfill({json:{verified:true,environment:'test',stamps:7,stampsToNext:3,rewards:[{id:'demo',code:'COFFEE-TESTDEMO1234',kind:'earned',status:'available'}],preferences:{email_enabled:1,sms_enabled:0,phone:''}}});});
 await page.goto('/rewards');await expect(page.getByText('7 / 10 stamps · 3 coffees to your next reward')).toBeVisible();await expect(page.getByText('COFFEE-TESTDEMO1234',{exact:true})).toBeVisible();await page.getByText('Email & SMS preferences',{exact:true}).click();await page.getByLabel('SMS me my earned coffee codes').check();await page.getByLabel('Mobile number for reward codes').fill('0821234567');await page.getByRole('button',{name:'Save reward preferences'}).click();await expect(page.getByRole('status')).toContainText('saved');await page.screenshot({path:info.outputPath('coffee-rewards-account.png'),fullPage:true});
});
test('basket applies a free coffee, invalidates it on edit and submits no payment for zero total',async({page},info)=>{
 await page.clock.setFixedTime(new Date('2026-09-28T10:00:00+02:00'));
 await page.route('**/api/account/rewards',r=>r.fulfill({json:{discountCents:3200,totalCents:0}}));let posted:any;
 await page.route('**/api/orders',async r=>{if(r.request().method()!=='POST')return r.continue();posted=r.request().postDataJSON();return r.fulfill({status:201,json:{reference:'fixture-ref',displayReference:'FOND-TEST-1234',totalCents:0,estimatedPrepMinutes:5,redirectUrl:null}});});
 let payments=0;await page.route('**/api/payments/checkout',r=>{payments++;return r.fulfill({status:500,json:{message:'Unexpected payment'}});});
 await page.goto('/');await page.getByRole('tab',{name:'Coffee',exact:true}).click();await page.getByRole('button',{name:'Add Espresso (Single)',exact:true}).click();await page.getByRole('button',{name:'Basket',exact:true}).click();await page.getByLabel('Free-coffee code').fill('COFFEE-TESTDEMO1234');await page.getByRole('button',{name:'Apply coffee code'}).click();await expect(page.getByRole('button',{name:'Redeem free coffee'})).toBeVisible();await page.getByRole('button',{name:'Add one Espresso (Single)',exact:true}).click();await expect(page.getByRole('button',{name:'Redeem free coffee'})).toHaveCount(0);await page.getByRole('button',{name:'Remove one Espresso (Single)',exact:true}).click();await page.getByRole('button',{name:'Apply coffee code'}).click();await page.getByLabel(/Your name/).fill('Reward test');await page.getByLabel('Contact number').fill('0821234567');await page.getByRole('button',{name:'Redeem free coffee'}).click();await expect(page.getByText('Your coffee reward covers this order. No payment is due.')).toBeVisible();expect(posted.rewardCode).toBe('COFFEE-TESTDEMO1234');expect(payments).toBe(0);await page.screenshot({path:info.outputPath('free-coffee-order.png')});
});
