import {test,expect} from '@playwright/test';
test('browse, adjust basket, place order and track it',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:/Good food/,level:1})).toBeVisible();
 await expect(page.locator('.meal-card').filter({has:page.getByRole('heading',{name:'Smashed Avo'})}).getByText(/Approx\. \d+ min/)).toBeVisible();
 await page.getByRole('button',{name:'Add Smashed Avo',exact:true}).click();
 await page.getByRole('button',{name:/^Basket/}).click();
 await expect(page.getByRole('tab',{name:'Delivery'})).toBeDisabled();
 await expect(page.getByText(/Online payment is currently unavailable/)).toBeVisible();
 await page.getByRole('button',{name:'Add one Smashed Avo',exact:true}).click();
 await page.getByLabel('Preferred collection').selectOption('Lunch collection');
 await page.getByLabel(/Your name/).fill('Playwright Test');
 await page.getByLabel('Contact number').fill('0821234567');
 await page.getByLabel('Email address').fill('guest@example.test');
 await expect(page.getByLabel('Email me when my order is received and ready')).toBeChecked();
 await expect(page.getByLabel('Email me when my order is received and ready')).toBeEnabled();
 await expect(page.getByLabel('WhatsApp notifications unavailable — setup pending')).toBeDisabled();
 await page.getByRole('button',{name:'Send order to FOND'}).click();
 await expect(page.getByText('Order sent to FOND.')).toBeVisible();
 await expect(page.getByRole('dialog')).toContainText(/240/);
 await page.getByRole('button',{name:'Back to the menu'}).click();
 await page.getByRole('button',{name:'Track order'}).click();
 await expect(page.getByRole('dialog')).toContainText('FOND-');
 await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test('available email and SMS notifications are preselected while WhatsApp stays unavailable',async({page})=>{
 await page.route('**/api/store',async route=>{const response=await route.fetch();const body=await response.json();body.settings.smsEnabled=true;body.settings.whatsappEnabled=false;await route.fulfill({response,json:body});});
 await page.route('**/api/auth/session',route=>route.fulfill({json:{user:{id:'unverified-customer',email:'customer@example.test',emailVerified:false}}}));
 await page.goto('/');
 await page.getByRole('button',{name:'Add Smashed Avo',exact:true}).click();
 await page.getByRole('button',{name:/^Basket/}).click();
 const sms=page.getByLabel('SMS me when my order is accepted and ready');
 const email=page.getByLabel('Email me when my order is received and ready');
 await expect(sms).toBeChecked();await expect(sms).toBeDisabled();
 await expect(page.getByLabel('Email address')).toHaveValue('customer@example.test');
 await expect(email).toBeChecked();await expect(email).toBeEnabled();
 await expect(page.getByLabel('WhatsApp notifications unavailable — setup pending')).toBeDisabled();
 await page.getByLabel('Contact number').fill('0821234567');
 await expect(sms).toBeChecked();await expect(sms).toBeEnabled();
 await expect(email).toBeChecked();
});
test('delivery tracking shows dispatch status and arrival time without a preparation estimate',async({page})=>{
 await page.route('**/api/orders?reference=*',route=>route.fulfill({json:{reference:'FOND-43E48401AA7044188B6DA071832E84AE',displayReference:'FOND-7K3P-9Q8R',status:'out_for_delivery',fulfillment:'delivery',totalCents:12000,collectionTime:'As soon as possible',estimatedPrepMinutes:13,updatedAt:'2026-09-22T09:00:00.000Z',estimatedArrivalAt:'2026-09-22T09:10:00.000Z',paymentMethod:'yoco_online',payment:{paidCents:12000,checkout:'paid'}}}));
 await page.goto('/');
 await page.getByRole('button',{name:'Track order'}).click();
 await page.getByLabel('Order number').fill('FOND-7K3P-9Q8R');
 await page.getByRole('button',{name:'Check status'}).click();
 await expect(page.getByRole('dialog')).toContainText('FOND-7K3P-9Q8R');
 await expect(page.getByRole('dialog')).toContainText('Out for delivery');
 await expect(page.getByRole('dialog')).toContainText(/Expected by/);
 await expect(page.getByRole('dialog')).not.toContainText('Ready for collection');
 await expect(page.getByRole('dialog')).not.toContainText('13 min preparation');
});
test('PWA manifest and order API validation',async({request})=>{
 const manifest=await request.get('/manifest.webmanifest');expect(manifest.ok()).toBeTruthy();expect((await manifest.json()).display).toBe('standalone');
 const staffManifest=await request.get('/staff/manifest.webmanifest');expect(staffManifest.ok()).toBeTruthy();expect(await staffManifest.json()).toMatchObject({name:'FOND Staff',start_url:'/staff',scope:'/staff'});
 const testStaffManifest=await request.get('/staff/manifest.webmanifest',{headers:{host:'fond-test.mid-point.co.za'}});expect(testStaffManifest.ok()).toBeTruthy();expect(await testStaffManifest.json()).toMatchObject({name:'FOND Staff TEST',short_name:'STAFF TEST',start_url:'/staff'});
 const result=await request.post('/api/orders',{data:{amount:1}});expect(result.status()).toBe(400);
 for(const path of ['/icons/icon-192.png','/icons/icon-512.png','/sw.js','/offline.html'])expect((await request.get(path)).ok()).toBeTruthy();
});
test('offline navigation shows fallback without queuing orders',async({page,context})=>{
 await page.goto('/');
 await page.evaluate(async()=>{await navigator.serviceWorker.ready; if(!navigator.serviceWorker.controller)await new Promise<void>(resolve=>navigator.serviceWorker.addEventListener('controllerchange',()=>resolve(),{once:true}));});
 await context.setOffline(true);await page.reload();await expect(page.getByRole('heading',{name:'Back in a moment.'})).toBeVisible();await expect(page.getByText('Orders are never sent while offline.')).toBeVisible();
 await context.setOffline(false);
});
test('staff tablet requires the access code and shows the queue',async({page})=>{
 await page.goto('/staff');
 await expect(page.getByRole('heading',{name:'Ready for service.'})).toBeVisible();
 await page.getByLabel('Sign in with a named account').check();
 await expect(page.getByLabel('Username')).toBeVisible();
 await expect(page.getByLabel('Password')).toBeVisible();
 await expect(page.getByLabel('Authenticator or recovery code')).toBeVisible();
 await page.getByLabel('Sign in with a named account').uncheck();
 await expect(page.getByLabel('Authenticator or recovery code')).toHaveCount(0);
 await page.getByLabel('Staff access code').fill(process.env.FOND_STAFF_CODE ?? '000000');
 await page.getByRole('button',{name:'Open order queue'}).click();
 await expect(page.getByRole('heading',{name:'Live order board'})).toBeVisible();
 await page.route(/\/api\/staff\/orders\?query=/,route=>route.fulfill({json:{search:true,orders:[{id:'search-fixture',reference:'FOND-43E48401AA7044188B6DA071832E84AE',displayReference:'FOND-7K3P-9Q8R',customerName:'Search Customer',note:null,lines:[{id:'espresso-single',quantity:1,name:'Espresso (Single)'}],collectionTime:'As soon as possible',totalCents:3200,status:'completed',source:'customer',createdAt:'2026-09-22T09:00:00.000Z',updatedAt:'2026-09-22T09:20:00.000Z',fulfillment:'collection',contactNumber:'0821234567',company:null,building:null,posRequired:true,posRecordedAt:'2026-09-22T09:02:00.000Z',posReference:'Y-123',estimatedPrepMinutes:4,paymentMethod:'pay_at_collection',paymentRequired:false,payment:{paidCents:3200,paymentMethod:'cash',checkout:null}}]}}));
 await page.getByPlaceholder('Order number, name, mobile, company or building').fill('FOND-7K3P-9Q8R');
 await page.getByRole('button',{name:'Search',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Search results'})).toBeVisible();
 await expect(page.getByText('FOND-7K3P-9Q8R')).toBeVisible();
 await expect(page.getByText('Search Customer')).toBeVisible();
});

test('menu add-ons update the basket and collection needs a contact number',async({page,request})=>{
 await page.goto('/');
 await page.getByRole('tab',{name:'Smoothies'}).click();
 const smoothie=page.locator('.meal-card').filter({has:page.getByRole('heading',{name:'Tropical Gold'})});
 await smoothie.getByLabel('Add protein powder').check();
 await smoothie.getByRole('button',{name:'Add Tropical Gold'}).click();
 await page.getByRole('button',{name:/^Basket/}).click();
 await expect(page.getByText('Add protein powder').last()).toBeVisible();
 await page.getByLabel(/Your name/).fill('Modifier browser test');
 await page.getByRole('button',{name:'Send order to FOND'}).click();
 await expect(page.getByText('Enter a contact number so FOND can reach you about your order.')).toBeVisible();
 const rejected=await request.post('/api/orders',{headers:{'Idempotency-Key':crypto.randomUUID()},data:{customerName:'Missing phone',collectionTime:'ASAP',lines:[{id:'tropical-gold',quantity:1}]}});
 expect(rejected.status()).toBe(400);
});
