import {test,expect} from '@playwright/test';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jvWQAAAAASUVORK5CYII=','base64');
test('promotion upload requires admin and accepts raster images only',async({request})=>{
 expect((await request.post('/api/admin/promotion-images')).status()).toBe(401);
 const login=await request.post('/api/admin/login',{data:{code:process.env.FOND_ADMIN_CODE}});expect(login.ok()).toBe(true);const headers={Cookie:login.headers()['set-cookie'].split(';')[0]};
 expect((await request.post('/api/admin/promotion-images',{headers,multipart:{image:{name:'bad.png',mimeType:'image/png',buffer:Buffer.from('<svg onload="alert(1)"></svg>')}}})).status()).toBe(400);
 const uploaded=await request.post('/api/admin/promotion-images',{headers,multipart:{image:{name:'test.png',mimeType:'image/png',buffer:png}}});expect(uploaded.status()).toBe(200);
 const image=await request.get((await uploaded.json()).url);expect(image.status()).toBe(200);expect(image.headers()['content-type']).toBe('image/png');expect(image.headers()['x-content-type-options']).toBe('nosniff');expect(await image.body()).toEqual(png);
});
test('customer promotions display cards and dismiss popup once per session',async({page},testInfo)=>{
 await page.route('**/api/store',async route=>{const response=await route.fetch(),data=await response.json();const base={body:'Fresh food for your working day.',active:true,startsAt:new Date(Date.now()-60000).toISOString(),endsAt:new Date(Date.now()+3600000).toISOString()};data.content.promotions=[{...base,id:'banner',title:'Breakfast sorted',display:'banner',category:'Smoothies'},{...base,id:'card',title:'Lunch at FOND',display:'card',imageUrl:'/test-offer.png'},{...base,id:'popup',title:'Your afternoon pick-me-up',display:'popup',imageUrl:'/images/fond-hero.jpg',buttonLabel:'Explore the menu'}];await route.fulfill({json:data});});
 await page.route('**/test-offer.png',route=>route.fulfill({body:png,contentType:'image/png'}));
 await page.goto('/');await page.getByRole('button',{name:'Basket',exact:true}).click();await page.waitForTimeout(1600);await expect(page.getByRole('dialog',{name:'Your afternoon pick-me-up'})).toHaveCount(0);await page.getByRole('button',{name:'Explore the menu',exact:true}).click();await expect(page.getByRole('dialog',{name:'Your afternoon pick-me-up'})).toBeVisible();await page.screenshot({path:testInfo.outputPath('promotion-popup.png'),fullPage:false});
 await page.getByRole('button',{name:'Close promotion'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Breakfast sorted'})).toBeVisible();await expect(page.locator('.promo-visual img')).toBeVisible();
 await page.locator('.promo-banner').getByRole('button',{name:'View menu'}).click();await expect(page.getByRole('tab',{name:'Smoothies',exact:true})).toHaveAttribute('aria-selected','true');
 await page.reload();await expect(page.getByRole('heading',{name:'Lunch at FOND'})).toBeVisible();await page.waitForTimeout(1600);await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('admin offers format controls and a working popup preview',async({page},testInfo)=>{
 await page.goto('/admin');await page.getByLabel('Admin access code').fill(process.env.FOND_ADMIN_CODE!);await page.getByRole('button',{name:'Unlock',exact:true}).click();await page.getByRole('button',{name:'Marketing & CMS',exact:true}).click();await page.getByRole('button',{name:'Add promotion',exact:true}).click();await page.getByLabel('Promotion title',{exact:true}).fill('Lunch made easy');await page.getByLabel('Display format').selectOption('popup');await page.getByLabel('Message',{exact:true}).fill('Order ahead and collect at Midpoint.');await page.getByRole('button',{name:'Preview popup'}).click();await expect(page.getByRole('dialog',{name:'Lunch made easy'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByLabel('Display format').selectOption('card');await page.getByLabel('Promotion image',{exact:true}).setInputFiles({name:'test.png',mimeType:'image/png',buffer:png});await expect(page.locator('.promotion-preview img')).toBeVisible();await page.screenshot({path:testInfo.outputPath('promotion-editor.png'),fullPage:true});
 // Draft preview only: do not publish into the shared test database.
});
