import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const previewArtwork=process.env.FOND_PROMOTION_PREVIEW_IMAGE?readFileSync(process.env.FOND_PROMOTION_PREVIEW_IMAGE):null;
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jvWQAAAAASUVORK5CYII=','base64');
test('promotion upload requires admin and accepts raster images only',async({request})=>{
 expect((await request.post('/api/admin/promotion-images')).status()).toBe(401);
 const login=await request.post('/api/admin/login',{data:{code:process.env.FOND_ADMIN_CODE}});expect(login.ok()).toBe(true);const headers={Cookie:login.headers()['set-cookie'].split(';')[0]};
 expect((await request.post('/api/admin/promotion-images',{headers,multipart:{image:{name:'bad.png',mimeType:'image/png',buffer:Buffer.from('<svg onload="alert(1)"></svg>')}}})).status()).toBe(400);
 const uploaded=await request.post('/api/admin/promotion-images',{headers,multipart:{image:{name:'test.png',mimeType:'image/png',buffer:png}}});expect(uploaded.status()).toBe(200);
 const image=await request.get((await uploaded.json()).url);expect(image.status()).toBe(200);expect(image.headers()['content-type']).toBe('image/png');expect(image.headers()['x-content-type-options']).toBe('nosniff');expect(await image.body()).toEqual(png);
});
test('customer promotions preserve cards and open popup only on request',async({page},testInfo)=>{
 await page.route('**/api/store',async route=>{const response=await route.fetch(),data=await response.json();const base={body:'Fresh food for your working day.',active:true,startsAt:new Date(Date.now()-60000).toISOString(),endsAt:new Date(Date.now()+3600000).toISOString()};data.content.promotions=[{...base,id:'banner',title:'Breakfast sorted',display:'banner',category:'Smoothies'},{...base,id:'card',title:'Lunch at FOND',display:'card',imageUrl:'/test-offer.png'},{...base,id:'popup',title:'Your afternoon pick-me-up',display:'popup',imageUrl:'/images/fond-hero.jpg',buttonLabel:'Explore the menu'}];await route.fulfill({json:data});});
 await page.route('**/test-offer.png',route=>route.fulfill({body:png,contentType:'image/png'}));
 await page.goto('/');await page.getByRole('button',{name:'Basket',exact:true}).click();await page.waitForTimeout(1600);await expect(page.getByRole('dialog',{name:'Your afternoon pick-me-up'})).toHaveCount(0);await page.getByRole('button',{name:'Explore the menu',exact:true}).click();await expect(page.getByRole('dialog',{name:'Your afternoon pick-me-up'})).toHaveCount(0);await page.getByRole('button',{name:'View offer: Your afternoon pick-me-up',exact:true}).click();await expect(page.getByRole('dialog',{name:'Your afternoon pick-me-up'})).toBeVisible();await page.screenshot({path:testInfo.outputPath('promotion-popup.png'),fullPage:false});
 await page.getByRole('button',{name:'Close promotion'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Breakfast sorted'})).toBeVisible();await expect(page.locator('.promo-visual img')).toBeVisible();
 await page.locator('.promo-banner').getByRole('button',{name:'View menu'}).click();await expect(page.getByRole('tab',{name:'Smoothies',exact:true})).toHaveAttribute('aria-selected','true');
 await page.reload();await expect(page.getByRole('heading',{name:'Lunch at FOND'})).toBeVisible();await page.waitForTimeout(1600);await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('admin offers format controls and a working popup preview',async({page},testInfo)=>{
 await page.goto('/admin');await page.getByLabel('Admin access code').fill(process.env.FOND_ADMIN_CODE!);await page.getByRole('button',{name:'Unlock',exact:true}).click();await page.getByRole('button',{name:'Marketing & CMS',exact:true}).click();await page.getByRole('button',{name:'Add promotion',exact:true}).click();await page.getByLabel('Promotion title',{exact:true}).fill('Lunch made easy');await page.getByLabel('Display format').selectOption('popup');await page.getByLabel('Message',{exact:true}).fill('Order ahead and collect at Midpoint.');await page.getByRole('button',{name:'Preview popup'}).click();await expect(page.getByRole('dialog',{name:'Lunch made easy'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByLabel('Display format').selectOption('card');await page.getByLabel('Promotion image',{exact:true}).setInputFiles({name:'test.png',mimeType:'image/png',buffer:png});await expect(page.locator('.promotion-preview img')).toBeVisible();await page.screenshot({path:testInfo.outputPath('promotion-editor.png'),fullPage:true});
 // Draft preview only: do not publish into the shared test database.
});

test('finished artwork fits the screen, keeps its content and opens the chosen category',async({page},testInfo)=>{
 const svg='<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1536"><rect width="1024" height="1536" fill="#f4e6d6"/><text x="80" y="220" font-size="70">COFFEE REWARDS</text><text x="80" y="1350" font-size="50">SEE THE FULL OFFER</text></svg>';
 await page.route('**/artwork-test',route=>route.fulfill({body:previewArtwork||svg,contentType:previewArtwork?'image/png':'image/svg+xml'}));
 await page.route('**/api/store',async route=>{const response=await route.fetch(),data=await response.json();data.content.promotions=[{id:'artwork',title:'Coffee artwork',body:'Buy ten coffees and receive one free on your next order.',display:'image-popup',imageUrl:'/artwork-test',buttonLabel:'Browse smoothies',category:'Smoothies',active:true,startsAt:new Date(Date.now()-60000).toISOString(),endsAt:new Date(Date.now()+3600000).toISOString()}];await route.fulfill({json:data});});
 await page.goto('/');const dialog=page.getByRole('dialog',{name:'Coffee artwork'});await expect(dialog).toHaveCount(0);await page.getByRole('button',{name:'View offer: Coffee artwork',exact:true}).click();await expect(dialog).toBeVisible();
 const img=dialog.getByRole('img');await expect(img).toHaveJSProperty('naturalWidth',1024);
 const bounds=await img.boundingBox();expect(bounds).not.toBeNull();expect(bounds!.width/bounds!.height).toBeCloseTo(2/3,2);expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.y).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width);expect(bounds!.y+bounds!.height).toBeLessThanOrEqual(page.viewportSize()!.height);
 await expect(dialog.locator('.promo-copy')).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Close promotion'})).toBeFocused();await page.screenshot({path:testInfo.outputPath('image-only-popup.png')});
 await dialog.getByRole('button',{name:/Buy ten coffees.*Browse smoothies/}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('tab',{name:'Smoothies',exact:true})).toHaveAttribute('aria-selected','true');await page.reload();await page.waitForTimeout(1500);await expect(dialog).toHaveCount(0);
});
test('admin previews full image artwork and upload accepts artwork above the old limit',async({page},testInfo)=>{
 await page.goto('/admin');await page.getByLabel('Admin access code').fill(process.env.FOND_ADMIN_CODE!);await page.getByRole('button',{name:'Unlock',exact:true}).click();await page.getByRole('button',{name:'Marketing & CMS',exact:true}).click();await page.getByRole('button',{name:'Add promotion',exact:true}).click();await page.getByLabel('Promotion title',{exact:true}).fill('Coffee rewards artwork');await page.getByLabel('Display format').selectOption('image-popup');await page.getByLabel('Image description (for screen readers)',{exact:true}).fill('Buy 10 coffees, get 1 free on your next order.');
 await page.getByLabel('Promotion image',{exact:true}).setInputFiles({name:'artwork.png',mimeType:'image/png',buffer:previewArtwork||Buffer.concat([png,Buffer.alloc(2100000)])});await expect(page.locator('.promotion-preview img')).toBeVisible();await page.getByRole('button',{name:'Preview popup'}).click();await expect(page.getByRole('dialog',{name:'Coffee rewards artwork'})).toBeVisible();await expect(page.getByRole('dialog').locator('.promo-copy')).toHaveCount(0);await page.getByRole('button',{name:'Close promotion'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 const rejected=page.waitForResponse(r=>r.url().includes('/api/admin/promotion-images')&&r.request().method()==='POST');await page.getByLabel('Promotion image',{exact:true}).setInputFiles({name:'too-large.png',mimeType:'image/png',buffer:Buffer.concat([png,Buffer.alloc(5000001)])});expect((await rejected).ok()).toBe(false);await expect(page.locator('.manage-promotion').getByRole('alert')).toContainText('5 MB');
});
