import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';

test('super admin owns provider settings while named admin can manage operations', async ({ request }) => {
  const bootstrap = await request.post('/api/admin/login', { data: { code: process.env.FOND_ADMIN_CODE } });
  expect(bootstrap.ok()).toBe(true);
  const superHeaders = { Cookie: bootstrap.headers()['set-cookie'].split(';')[0] };
  const providerResponse=await request.get('/api/admin/provider-credentials', { headers: superHeaders });
  expect(providerResponse.status()).toBe(200);
  const providers=await providerResponse.json();
  expect(providers.sms).toEqual({accountSid:'',sender:''});
  expect(providers.smsWebhookUrl).toMatch(/\/api\/webhooks\/twilio\/sms$/);
  const username = `manager.${randomUUID().slice(0, 8)}`;
  const created = await request.post('/api/admin/manage/team', { headers: superHeaders, data: { name: 'Test admin', username, role: 'manager', active: true, password: 'manager-password-123' } });
  expect(created.ok()).toBe(true);
  const login = await request.post('/api/admin/login', { data: { username, password: 'manager-password-123' } });
  expect(login.ok()).toBe(true);
  const adminHeaders = { Cookie: login.headers()['set-cookie'].split(';')[0] };
  const settings = await (await request.get('/api/admin/manage/settings', { headers: adminHeaders })).json();
  expect(settings.role).toBe('manager'); expect(settings.team).toEqual([]);
  expect((await request.get('/api/admin/provider-credentials', { headers: adminHeaders })).status()).toBe(403);
  expect((await request.post('/api/admin/provider-credentials', { headers: adminHeaders, data: { name: 'yoco-secret', value: 'sk_test_fake' } })).status()).toBe(403);
  expect((await request.post('/api/admin/manage/team', { headers: adminHeaders, data: { name: 'Another', username: `${username}.2`, role: 'staff', active: true, password: 'long-password-123' } })).status()).toBe(403);
  const operational = await request.post('/api/admin/manage/settings', { headers: adminHeaders, data: settings.settings });
  expect(operational.ok()).toBe(true);
  const forbidden = await request.post('/api/admin/manage/settings', { headers: adminHeaders, data: { ...settings.settings, onlinePaymentsEnabled: !settings.settings.onlinePaymentsEnabled } });
  expect(forbidden.status()).toBe(403);
});

test('owner has oversight and can manage operational accounts without provider or privilege access', async ({ request,page }) => {
  const bootstrap = await request.post('/api/admin/login', { data: { code: process.env.FOND_ADMIN_CODE } });
  expect(bootstrap.ok()).toBe(true);
  const superHeaders = { Cookie: bootstrap.headers()['set-cookie'].split(';')[0] };
  const suffix=randomUUID().slice(0,8),username=`owner.${suffix}`;
  const created=await request.post('/api/admin/manage/team',{headers:superHeaders,data:{name:'Test owner',username,role:'owner',active:true,password:'owner-password-123'}});
  expect(created.ok()).toBe(true);
  const login=await request.post('/api/admin/login',{data:{username,password:'owner-password-123'}});
  expect(login.ok()).toBe(true);
  const ownerHeaders={Cookie:login.headers()['set-cookie'].split(';')[0]};
  const response=await request.get('/api/admin/manage/settings',{headers:ownerHeaders});
  expect(response.ok()).toBe(true);
  const data=await response.json();
  expect(data.role).toBe('owner');
  expect(Array.isArray(data.changes)).toBe(true);
  expect(data.team.every((member:{role:string})=>['manager','staff'].includes(member.role))).toBe(true);
  expect((await request.get('/api/admin/provider-credentials',{headers:ownerHeaders})).status()).toBe(403);
  expect((await request.post('/api/admin/provider-credentials',{headers:ownerHeaders,data:{name:'yoco-secret',value:'sk_test_fake'}})).status()).toBe(403);
  const manager=await request.post('/api/admin/manage/team',{headers:ownerHeaders,data:{name:'Owner-managed manager',username:`managed.${suffix}`,role:'manager',active:true,password:'manager-password-123'}});
  expect(manager.ok()).toBe(true);
  const forbiddenOwner=await request.post('/api/admin/manage/team',{headers:ownerHeaders,data:{name:'Another owner',username:`owner.two.${suffix}`,role:'owner',active:true,password:'second-owner-password'}});
  expect(forbiddenOwner.status()).toBe(403);
  const forbiddenSuper=await request.post('/api/admin/manage/team',{headers:ownerHeaders,data:{name:'Another super',username:`super.two.${suffix}`,role:'super-admin',active:true,password:'second-super-password'}});
  expect(forbiddenSuper.status()).toBe(403);
  await page.goto('/admin');
  await page.getByLabel('Sign in with a named account').check();
  await page.getByLabel('Username').fill(username);
  await page.getByLabel('Password').fill('owner-password-123');
  await page.getByRole('button',{name:'Unlock'}).click();
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Team & permissions · owner'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Change history & rollback'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Provider credentials'})).toHaveCount(0);
  await expect(page.getByLabel('Role')).not.toContainText('Owner — oversight & rollback');
});
