import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';

test('staff accepts, records Yoco entry, then marks the order ready', async ({ page, request }) => {
  const created = await request.post('/api/orders', { headers: { 'Idempotency-Key': randomUUID() }, data: { customerName: 'POS browser test', contactNumber: '0821234567', collectionTime: 'ASAP', lines: [{ id: 'espresso-single', quantity: 1 }] } });
  expect(created.status()).toBe(201);
  const { reference } = await created.json();
  await page.goto('/staff');
  await page.getByLabel('Staff access code').fill(process.env.FOND_STAFF_CODE!);
  await page.getByRole('button', { name: 'Open order queue' }).click();
  for (const title of ['New','Awaiting Yoco payment confirmation','Added to Yoco system','Preparing','Ready for delivery','Ready for collection']) await expect(page.getByRole('region',{name:title})).toBeVisible();
  await expect(page.getByRole('button',{name:'Enable sound'})).toBeVisible();
  const card = page.locator('.staff-card').filter({ hasText: reference });
  await expect(card).toBeVisible();
  await expect(card.getByRole('status').filter({ hasText: 'PAY IN PERSON ON COLLECTION' })).toBeVisible();
  await expect(card.getByText(/Collecting: POS browser test · 0821234567/)).toBeVisible();
  await card.getByRole('button',{name:'View audit trail'}).click();
  await expect(card.getByText('Permanent order record')).toBeVisible();
  await expect(card.getByText(/Created → received/)).toBeVisible();
  await card.getByRole('button', { name: 'Accept' }).click();
  await expect(card.getByRole('button', { name: 'Start preparing' })).toHaveCount(0);
  await card.getByRole('button', { name: 'Record Yoco entry' }).click();
  await card.getByLabel('Yoco order reference').fill('YOCO-BROWSER-1');
  await card.getByRole('button', { name: 'Confirm Yoco entry' }).click();
  await expect(page.getByRole('region',{name:'Added to Yoco system'}).locator('.staff-card').filter({hasText:reference})).toBeVisible();
  await expect(card.getByText('Entered in Yoco · YOCO-BROWSER-1')).toBeVisible();
  await card.getByRole('button', { name: 'Start preparing' }).click();
  await expect(page.getByRole('region',{name:'Preparing'}).locator('.staff-card').filter({hasText:reference})).toBeVisible();
  await card.getByRole('button', { name: 'Ready for collection' }).click();
  await expect(page.getByRole('region',{name:'Ready for collection'}).locator('.staff-card').filter({hasText:reference})).toBeVisible();
});
