import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test('Functions date requests, access isolation and booking confirmation',async({page,request,playwright,baseURL},info)=>{
 const suffix=Date.now()+'-'+info.project.name,date=new Date(Date.now()+(info.project.name==='mobile'?45:44)*86400000).toISOString().slice(0,10);
 const login=await request.post('/api/admin/login',{data:{code:'isolated-hub-admin'}}),cookie=login.headers()['set-cookie'].split(';')[0];
 for(const role of ['functions','gym']){const r=await request.post('/api/admin/manage/team',{headers:{Cookie:cookie},data:{name:'Fixture '+role,username:role+suffix,role,active:true,password:'isolated-test-password'}});expect(r.ok(),await r.text()).toBe(true);}
 async function client(role:string){const r=await request.post('/api/hub/session',{data:{username:role+suffix,password:'isolated-test-password'}});expect(r.ok()).toBe(true);return playwright.request.newContext({baseURL,extraHTTPHeaders:{Cookie:r.headers()['set-cookie'].split(';')[0]}});}
 const functions=await client('functions'),gym=await client('gym'),anonymous=await playwright.request.newContext({baseURL});
 try{expect((await anonymous.get('/api/functions/manage?month='+date.slice(0,7))).status()).toBe(403);expect((await gym.get('/api/functions/manage?month='+date.slice(0,7))).status()).toBe(403);expect((await functions.get('/api/hub/manage?service=gym')).status()).toBe(401);expect((await functions.get('/api/admin/menu')).status()).toBe(401);
 await page.goto('/functions');const current=new Date(Date.now()+2*3600000),target=new Date(date+'T12:00:00Z'),steps=(target.getUTCFullYear()-current.getUTCFullYear())*12+target.getUTCMonth()-current.getUTCMonth();for(let i=0;i<steps;i++){await page.getByRole('button',{name:'Next month',exact:true}).click();await expect(page.locator('.function-month strong')).toHaveText(new Date(Date.UTC(current.getUTCFullYear(),current.getUTCMonth()+i+1,1)).toLocaleDateString('en-ZA',{month:'long',year:'numeric',timeZone:'Africa/Johannesburg'}));}await page.getByRole('button',{name:date,exact:true}).click();await page.getByLabel('Pax').fill('25');await page.getByLabel('Function style',{exact:true}).selectOption('Buffet');await page.getByLabel('Contact person').fill('Fixture '+suffix);await page.getByLabel('Email',{exact:true}).fill(suffix+'@example.com');await page.getByLabel('Contact number').fill('0820000000');await page.getByLabel('Company').fill('Fixture Co');await page.getByLabel('Theme or occasion').fill('Fixture team day');await page.getByLabel('Budget (R)',{exact:true}).fill('350');await page.getByLabel('Budget basis',{exact:true}).selectOption('per-person');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Request this date'}).click();await expect(page.getByRole('heading',{name:'Your request is in.'})).toBeVisible();
 const data=await(await functions.get('/api/functions/manage?month='+date.slice(0,7))).json(),saved=data.bookings.find((b:any)=>b.details.contactPerson==='Fixture '+suffix);expect(saved.status).toBe('pending');expect(saved.details.pax).toBe('25');expect(saved.details.budget).toBe('350.00');expect(saved.details.budgetBasis).toBe('per-person');expect((await gym.post('/api/functions/manage',{data:{action:'status',id:saved.id,status:'confirmed'}})).status()).toBe(403);expect((await functions.post('/api/functions/manage',{headers:{Origin:'https://foreign.example'},data:{action:'status',id:saved.id,status:'confirmed'}})).status()).toBe(403);
 const second=await anonymous.post('/api/functions',{headers:{'Idempotency-Key':randomUUID()},data:{date,pax:12,cuisine:'Braai',contactPerson:'Second fixture',email:'second-'+suffix+'@example.com',phone:'0820000000',consent:true}});expect(second.ok()).toBe(true);const secondId=(await second.json()).id;
 expect((await functions.post('/api/functions/manage',{data:{action:'status',id:saved.id,status:'confirmed'}})).ok()).toBe(true);expect((await functions.post('/api/functions/manage',{data:{action:'status',id:secondId,status:'confirmed'}})).status()).toBe(400);const publicData=await(await anonymous.get('/api/functions')).json();expect(publicData.bookedDates).toContain(date);expect(JSON.stringify(publicData)).not.toContain('Fixture');
 await page.goto('/hub/functions');await page.getByLabel('Team username').fill('functions'+suffix);await page.getByLabel('Password',{exact:true}).fill('isolated-test-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByLabel('Month',{exact:true}).fill(date.slice(0,7));await expect(page.getByText(date+' · Fixture '+suffix+' · confirmed',{exact:true})).toBeVisible();
 for(const width of [320,390,768]){await page.setViewportSize({width,height:850});for(const path of ['/functions','/hub/functions']){await page.goto(path);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),path+' '+width).toBe(true);}}
 }finally{await functions.dispose();await gym.dispose();await anonymous.dispose();}
});
