import {test,expect} from '@playwright/test';
test('practice: membership to paid collection, tenth stamp and one-use free coffee',async({page},info)=>{
 await page.goto('/rewards');await page.getByLabel('Email',{exact:true}).fill('coffee@example.test');await page.getByLabel('Password',{exact:true}).fill('CoffeePractice29!');await page.getByRole('button',{name:'Sign in',exact:true}).click();
 const membership=page.locator('.membership-card');await expect(membership).toBeVisible();const code=await membership.locator('code').innerText();await expect(page.locator('.ticket-progress')).toContainText('9 / 10');await page.screenshot({path:info.outputPath('practice-membership.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('practice-membership-mobile.png'),fullPage:true});await page.setViewportSize({width:1280,height:900});
 const staff=await page.context().newPage();await staff.goto('/staff');await staff.getByLabel('Staff access code').fill('practice-staff');await staff.getByRole('button',{name:'Open order queue'}).click();
 await staff.getByRole('button',{name:'Add order',exact:true}).click();let drawer=staff.getByRole('dialog',{name:'Add order manually'});await drawer.getByLabel('Jump to category').selectOption('Coffee');await drawer.getByRole('button',{name:'Add Espresso (Single)',exact:true}).click();await drawer.getByLabel('Customer membership number').fill(code);await drawer.getByRole('button',{name:'Check membership'}).click();await expect(drawer.getByRole('status')).toContainText('Membership confirmed');
 await drawer.getByLabel('Name / table / desk').fill('Practice paid coffee');await drawer.getByLabel('Contact number').fill('0821234567');await drawer.getByRole('button',{name:'Add to queue'}).click();
 let card=staff.locator('.staff-card').filter({hasText:'Practice paid coffee'});await expect(card).toContainText('Coffee membership attached');
 async function pos(c:typeof card){const number=(await c.locator('.staff-short-number').first().innerText()).replace('FOND ','');await c.getByRole('button',{name:'Record Yoco entry'}).click();const d=staff.getByRole('dialog',{name:'Confirm Yoco POS entry'});await d.getByLabel('Yoco POS receipt / order number').fill('PRACTICE-'+number);await d.getByRole('button',{name:'Confirm POS entry'}).click();await expect(d).not.toBeVisible();return 'PRACTICE-'+number;}
 const receipt=await pos(card);await expect(card).toContainText('Yoco receipt verified');await page.reload();await expect(page.locator('.ticket-progress')).toContainText('9 / 10');
 await card.getByRole('button',{name:'Start preparing'}).click();await card.getByRole('button',{name:'Ready for collection'}).click();await card.getByRole('button',{name:'Record Yoco payment'}).click();const payment=staff.getByRole('dialog',{name:'Record payment received'});await payment.getByLabel('Card receipt reference').fill(receipt);await payment.getByRole('button',{name:'Confirm payment received'}).click();await card.getByRole('button',{name:'Mark collected'}).click();await expect(card).toHaveCount(0);
 await page.reload();const reward=page.locator('.reward-card');await expect(reward).toContainText('Ready to use');const rewardCode=await reward.locator('code').innerText();await page.screenshot({path:info.outputPath('practice-free-coffee.png'),fullPage:true});
 await staff.getByRole('button',{name:'Redeem coffee',exact:true}).click();drawer=staff.getByRole('dialog',{name:'Add order manually'});await drawer.getByRole('button',{name:'Add Espresso (Single)',exact:true}).click();await drawer.getByLabel('Coffee reward code').fill(rewardCode);await drawer.getByRole('button',{name:'Validate coffee code'}).click();await expect(drawer.getByRole('status')).toContainText('Nothing to collect');await drawer.getByLabel('Name / table / desk').fill('Practice free coffee');await drawer.getByLabel('Contact number').fill('0821234567');await drawer.getByRole('button',{name:'Add to queue'}).click();
 await staff.getByRole('tab',{name:/^New:/}).click();card=staff.locator('.staff-card').filter({hasText:'Practice free coffee'});await pos(card);await card.getByRole('button',{name:'Start preparing'}).click();await card.getByRole('button',{name:'Ready for collection'}).click();await expect(card.getByRole('button',{name:'Take payment',exact:true})).toHaveCount(0);await card.getByRole('button',{name:'Mark collected'}).click();await page.reload();await expect(page.locator('.reward-card')).toContainText('redeemed');
 await staff.getByRole('button',{name:'Redeem coffee',exact:true}).click();drawer=staff.getByRole('dialog',{name:'Add order manually'});await drawer.getByRole('button',{name:'Add Espresso (Single)',exact:true}).click();await drawer.getByLabel('Coffee reward code').fill(rewardCode);await drawer.getByRole('button',{name:'Validate coffee code'}).click();await expect(drawer.getByRole('alert')).toContainText('unavailable');
});
