'use client';
import {useEffect,useState} from 'react';
type Reward={id:string;code:string;status:string;kind:string};
export function CoffeeRewards(){
 const [data,setData]=useState<{verified:boolean;environment:string;stamps:number;stampsToNext:number;rewards:Reward[]}|null>(null),[email,setEmail]=useState(false),[sms,setSms]=useState(false),[phone,setPhone]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/account/rewards',{cache:'no-store'});if(!r.ok)throw new Error('Could not load coffee rewards.');const d=await r.json();setData(d);setEmail(!!d.preferences?.email_enabled);setSms(!!d.preferences?.sms_enabled);setPhone(d.preferences?.phone??'');}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function send(rewardId:string){setBusy(true);try{const r=await fetch('/api/account/rewards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'send',rewardId})});const d=await r.json();setMessage(r.ok?'Code delivery requested using your saved preferences. Previously submitted codes are not sent twice.':d.message);}catch{setMessage('Could not request code delivery.');}finally{setBusy(false);}}
 async function save(){setBusy(true);try{const r=await fetch('/api/account/rewards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'preferences',email,sms,phone})});const d=await r.json();if(!r.ok)throw new Error(d.message);setMessage('Reward notification preferences saved.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="coffee-rewards"><p className="eyebrow">THROUGH THE FOND APP ONLY</p><h2>Coffee rewards</h2><p>Buy 10 coffees through the FOND app and get one free on your next order. Sign in with a verified email before ordering. Each paid coffee earns one stamp when collected or delivered. Counter orders do not count.</p>{data?.verified?<>{data.environment==='test'&&<p className="notice">Test rewards only — these stamps and codes cannot be used for live payments.</p>}<strong>{data.stamps} / 10 stamps · {data.stampsToNext} coffees to your next reward</strong><p>Redeem against any one Coffee item. Extras are charged separately. One code per order; the highest-priced eligible coffee is discounted. Codes belong to your account.</p>{data.rewards.map(r=><div className="reward-card" key={r.id}><strong>{r.kind==='gift'?'Gift coffee':'Earned coffee'}</strong><span>{r.status}</span>{r.status==='available'&&<><code>{r.code}</code><button className="outline" onClick={()=>navigator.clipboard.writeText(r.code).then(()=>setMessage('Code copied. Paste it into your basket.')).catch(()=>setMessage('Select and copy the code above.'))}>Copy coffee code</button><button className="quiet" disabled={busy} onClick={()=>send(r.id)}>Email / SMS this code</button><a href="/">Choose your coffee</a></>}{r.status==='reserved'&&<small>Reserved on an order. Staff can cancel the order to release it.</small>}</div>)}<h3>Send my new reward codes</h3><label className="field-check"><input type="checkbox" checked={email} onChange={e=>setEmail(e.target.checked)}/> Email me my earned coffee codes</label><label className="field-check"><input type="checkbox" checked={sms} onChange={e=>setSms(e.target.checked)}/> SMS me my earned coffee codes</label>{sms&&<label className="field">Mobile number for reward codes<input value={phone} onChange={e=>setPhone(e.target.value)} type="tel" placeholder="+27…"/></label>}<button className="outline" disabled={busy} onClick={save}>Save reward preferences</button></>:<p>Verify your account email above to start earning and redeeming rewards.</p>}{message&&<p role="status">{message}</p>}</section>;
}
export function AdminCoffeeRewards(){
 const [data,setData]=useState<any>(null),[email,setEmail]=useState(''),[phone,setPhone]=useState(''),[reason,setReason]=useState(''),[emailEnabled,setEmailEnabled]=useState(true),[smsEnabled,setSmsEnabled]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[key,setKey]=useState('');
 async function load(){const r=await fetch('/api/admin/rewards',{cache:'no-store'});if(r.ok)setData(await r.json());}useEffect(()=>{void load();setKey(crypto.randomUUID());},[]);
 async function gift(){setBusy(true);try{const r=await fetch('/api/admin/rewards',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify({action:'gift',email,phone,reason,emailEnabled,smsEnabled})}),d=await r.json();if(!r.ok)throw new Error(d.message);setMessage(`Gift code: ${d.code}. Delivery is queued where selected; check status below.`);setKey(crypto.randomUUID());setReason('');await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function revoke(id:string){setBusy(true);try{const r=await fetch('/api/admin/rewards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'revoke',id})}),d=await r.json();setMessage(r.ok?'Unused gift revoked.':d.message);await load();}catch{setMessage('Could not revoke gift.');}finally{setBusy(false);}}
 if(!data)return null;
 return <section className="manage-card coffee-rewards"><h2>Coffee rewards · app only</h2><p>Every 10 paid coffees completed through a verified customer account earns one free Coffee item. Extras remain payable. Gift codes are issued only by super admins and redeemable through the recipient’s verified account.</p><strong>{data.environment==='test'?'TEST codes — not valid for live payment':'LIVE coffee rewards'}</strong><label className="field">Gift recipient email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field">Gift reason<input maxLength={200} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="field-check"><input type="checkbox" checked={emailEnabled} onChange={e=>setEmailEnabled(e.target.checked)}/> Email this code</label><label className="field-check"><input type="checkbox" checked={smsEnabled} onChange={e=>setSmsEnabled(e.target.checked)}/> SMS this code</label>{smsEnabled&&<label className="field">Gift recipient mobile<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label>}<button className="primary" disabled={busy||!email.trim()||!reason.trim()} onClick={gift}>Issue free-coffee gift code</button>{message&&<p role="status">{message}</p>}<button className="quiet" onClick={load}>Refresh reward log</button><h3>Recent rewards</h3>{data.rewards.map((r:any)=><p key={r.id}>{r.recipient_email} · {r.environment} · {r.kind} · {r.status} {r.kind==='gift'&&r.status==='available'&&<button className="quiet" disabled={busy} onClick={()=>revoke(r.id)}>Revoke unused gift</button>}</p>)}<h3>Code delivery</h3><p>Provider accepted means submitted to the provider, not confirmed at the recipient. Unconfirmed responses need provider review before any resend.</p>{data.messages.map((m:any,i:number)=><p key={i}>{m.channel} · {m.status} {m.error&&`· ${m.error}`}</p>)}<details><summary>Reward audit trail</summary>{data.events.map((e:any,i:number)=><p key={i}>{e.created_at} · {e.action} · {e.actor} · {e.detail}</p>)}</details></section>;
}
