import Link from 'next/link';
import {ArrowLeft,ArrowRight,Coffee,Clock3,ShoppingBag,Truck,Search,UserRound,Utensils} from 'lucide-react';
import {HubAppNav} from './hub-app-nav';
import {settings,orderingAvailable} from '@/lib/management';
import {orderingHoursMessage,weeklyTradingHours} from '@/lib/trading-hours';
import './fond-experience.css';
export function FondShell({children}:{children:React.ReactNode}){return <main className="fond-experience"><header className="fond-page-header"><Link href="/hub" aria-label="Midpoint Home"><ArrowLeft size={22}/></Link><Link href="/hub"><img src="/hub-assets/hub-logo.png" alt="Midpoint Hub" width="106" height="38"/></Link><Link href="/account" aria-label="Your account"><UserRound size={20}/></Link></header><div className="fond-page-content">{children}<footer className="fond-page-legal"><Link href="/hub/privacy">Privacy policy</Link><Link href="/hub/terms">Terms and conditions</Link></footer></div><HubAppNav/></main>}
function Row({href,title,copy,icon}:{href:string;title:string;copy:string;icon:React.ReactNode}){return <Link className="fond-page-row" href={href}>{icon}<div><strong>{title}</strong><small>{copy}</small></div><ArrowRight size={16}/></Link>}
export function FondLanding(){const trading=settings();return <FondShell><p className="fond-kicker">FOND / MIDPOINT</p><h1>Good food.<br/><em>Good days.</em></h1><p className="fond-intro">Quality coffee, fresh food and all-day favourites. A little pause in the middle of everything.</p><Link className="fond-page-primary" href="/fond/menu">Order now <ArrowRight size={20}/></Link><p className="fond-page-status">{orderingAvailable(trading)?'Taking orders':'Currently closed'} · {orderingHoursMessage(trading)}</p><section className="fond-page-actions" aria-label="Explore FOND"><Row href="/fond/menu" title="Explore the menu" copy="Find your next favourite." icon={<Utensils/>}/><Row href="/fond/reorder" title="Order again" copy="Your past favourites, ready for another day." icon={<ShoppingBag/>}/><Row href="/fond/fulfilment" title="Delivery or collection" copy="Choose what suits your day." icon={<Truck/>}/><Row href="/fond/hours" title="Opening hours" copy={orderingHoursMessage(trading)} icon={<Clock3/>}/><Row href="/fond/track" title="Track your order" copy="See the latest from FOND." icon={<Search/>}/></section><Link href="/rewards" className="fond-rewards-link"><Coffee/><div><strong>Your coffee moments</strong><p>See your stamps, rewards and next little lift.</p></div><ArrowRight size={18}/></Link></FondShell>}
export function FondHours(){const trading=settings();return <FondShell><p className="fond-kicker">FOND / VISIT US</p><h1>Make time<br/><em>for FOND.</em></h1><p className="fond-intro">{orderingHoursMessage(trading)}</p><section className="fond-info-card"><h2>FOND Café & Eatery</h2><p>{weeklyTradingHours(trading)}</p><h2>Food Truck</h2><p>{weeklyTradingHours(trading,true)}</p><small>All times are South African time. Ordering availability follows the current trading settings.</small></section><Row href="/fond/menu" title="Explore the menu" copy="Your next favourite is waiting." icon={<Utensils/>}/><Row href="/fond" title="Back to FOND" copy="Good food. Good days." icon={<Coffee/>}/></FondShell>}
export function FondFulfilment(){const trading=settings();return <FondShell><p className="fond-kicker">FOND / YOUR ORDER</p><h1>Your food.<br/><em>Your way.</em></h1><p className="fond-intro">Choose collection or delivery when you order. The basket shows the available times and payment options.</p><section className="fond-info-card"><h2>Collection</h2><p>{trading.collectionEnabled===false?'Collection is currently unavailable.':'Collect from FOND at Midpoint Hub. Choose your collection time in the basket.'}</p><h2>Delivery</h2><p>{trading.deliveryEnabled?trading.deliveryArea||'Delivery to supported Midpoint businesses.':'Delivery is currently unavailable.'}</p><p>Delivery needs an eligible business and building, contact number and online payment. Add floor or desk details to the order note. You can optionally confirm a location pin.</p><small>Only options supported by current trading and payment settings can be selected in the menu.</small></section><Link className="fond-page-primary" href="/fond/menu">Start your order <ArrowRight size={20}/></Link></FondShell>}
