'use client';
import { useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Check } from 'lucide-react';
import { HUB_CONTACTS, type HubService } from '@/lib/hub-config';
export function HubSignup({service,eventId,eventTitle,eventImage,eventImageAlt}:{service:HubService;eventId?:string;eventTitle?:string;eventImage?:string;eventImageAlt?:string}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
  const key=useRef(''),gym=service==='gym',contact=HUB_CONTACTS[service];
  async function submit(e:React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); if(busy)return;setBusy(true);setError(''); const form=e.currentTarget, data=Object.fromEntries(new FormData(form));
    key.current ||= crypto.randomUUID();
    try { const response=await fetch('/api/hub/requests',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key.current},body:JSON.stringify({...data,service,kind:eventId?'interest':'signup',eventId,consent:data.consent==='on',playtomicAccount:data.playtomicAccount==='yes'})});const result=await response.json();if(!response.ok)throw new Error(result.message);form.reset();setSaved(true); }
    catch(e){setError(e instanceof Error?e.message:'Could not save your request. Please try again.');}finally{setBusy(false);}
  }
  if(saved)return <section className="hub-success" role="status"><div className="hub-tick"><Check/></div><span className="hub-eyebrow">REQUEST RECEIVED</span><h1>{eventId?'Thanks for your interest.':gym?<>See you<br/>at the gym.</>:<>Next stop:<br/>the court.</>}</h1><p>Your request has been saved for {contact.name}. {eventId?'The team will confirm availability and the next steps. Your place is not yet reserved.':gym?'Visit reception with your ID or passport to complete your membership.':'The team will confirm your tenant details and help with Playtomic setup.'}</p>{!eventId&&<ol className="hub-steps">{(gym?['Visit the gym reception with your ID or passport.','Choose your membership and complete Itensity registration with our staff.','Finalise payment; the team then activates your gym access.']:['We check your company and tenant details.','We help with your existing Playtomic profile or getting started.','The team contacts you with the next steps. Court bookings follow separately.']).map(s=><li key={s}>{s}</li>)}</ol>}<Link className="hub-primary" href={`/${service}/${gym?'classes':'events'}`}>Explore the calendar <ArrowRight/></Link><Link className="hub-secondary" href="/hub">Back to Midpoint Hub</Link></section>;
  return <><section className="hub-intro"><span className="hub-eyebrow">{eventId?'JOIN IN':gym?'YOUR NEXT CHAPTER':'FOR MIDPOINT TENANTS'}</span><h1>{eventId?eventTitle:gym?<>Let’s get<br/>you moving.</>:<>Let’s get<br/>you on court.</>}</h1><p>{eventId?'Send your interest to the team. Availability and participation are confirmed separately.':gym?'Leave your details and we’ll help sign you up to Itensity. Or pop into the gym and we’ll do it together.':'Tell us where you work at Midpoint. We’ll verify your tenant details and help set you up on Playtomic.'}</p></section>{eventImage&&<img className="hub-event-image hub-event-hero" src={eventImage} alt={eventImageAlt||eventTitle||'Event image'}/>}<form className="hub-form" onSubmit={submit}><div className="hub-field-row"><label>First name<input name="firstName" autoComplete="given-name" maxLength={80} required/></label><label>Surname<input name="surname" autoComplete="family-name" maxLength={80} required/></label></div><label>Email address<input name="email" type="email" autoComplete="email" maxLength={254} required/></label><label>Mobile number<input name="phone" type="tel" autoComplete="tel" maxLength={30} required/></label>{!eventId&&<label>ID or passport number<input name="identity" autoComplete="off" maxLength={40} required/><small>Stored securely for the {gym?'Gym':'Padel'} team to review your signup. Bring your document when the team asks to verify it.</small></label>}<label>Company / tenant name {gym&&<small>· if applicable</small>}<input name="company" maxLength={160} required={!gym}/></label>{!gym&&<><label>Building / unit<input name="building" maxLength={100} required/></label>{!eventId&&<label>Do you already use Playtomic?<select name="playtomicAccount"><option value="no">No, I need help getting started</option><option value="yes">Yes, I already have an account</option></select><small>If you have an account, use its email address above.</small></label>}</>}<div className="hub-trap" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="hub-check"><input name="consent" type="checkbox" required/><span>I agree that Midpoint may use these details to process this request and contact me about it. <Link href="/hub/privacy">Privacy policy</Link> · <Link href="/hub/terms">Terms and conditions</Link></span></label>{error&&<p className="hub-error" role="alert">{error}</p>}<button className="hub-primary" disabled={busy}>{busy?'Saving your request…':eventId?'Send my interest':gym?'Send signup request':'Request tenant setup'}<ArrowRight/></button><p className="hub-helper">{eventId?'This does not reserve a place.':'This request does not take payment or activate membership or access.'}</p></form><a className="hub-contact" href={`mailto:${contact.email}`}>Need help? Contact {contact.name}</a></>;
}
