import Link from 'next/link';
import { ArrowLeft, ArrowRight, CalendarDays, Coffee, Dumbbell, Home, MapPin, ShieldCheck, Volleyball, UserRoundPlus } from 'lucide-react';
import { HUB_CONTACTS, type HubService } from '@/lib/hub-config';
import { bookingUrl } from '@/lib/hub-store';
import './hub.css';
export function HubShell({children,service}:{children:React.ReactNode;service?:HubService}) {
  return <main className={`hub-shell ${service==='padel'?'hub-padel':''}`}><header className="hub-top"><Link href="/hub" aria-label="Midpoint Hub home"><img src="/hub-assets/hub-logo.png" alt="Midpoint Hub"/></Link><Link href="/hub" className="hub-home" aria-label="Choose a destination"><Home/></Link></header><div className="hub-content">{children}</div><footer className="hub-footer"><strong>All at Midpoint.</strong><p>162 Tonetti Street, Halfway House, Midrand</p><nav><Link href="/fond">FOND</Link><Link href="/gym">Gym</Link><Link href="/padel">Padel</Link><Link href="/functions">Functions</Link></nav><div><Link href="/hub/privacy">Your details</Link><Link href="/hub/manage">Team sign in</Link></div></footer></main>;
}
export function HubBack({href,children}:{href:string;children:React.ReactNode}) {return <Link href={href} className="hub-back"><ArrowLeft size={16}/>{children}</Link>;}
export function HubNote({title,children}:{title:string;children:React.ReactNode}) {return <aside className="hub-note"><ShieldCheck/><div><h3>{title}</h3><p>{children}</p></div></aside>;}
export function HubHome() {
  return <HubShell><section className="hub-hero"><span className="hub-eyebrow">WELCOME TO YOUR MIDPOINT</span><h1>Your day.<br/>All at Midpoint.</h1><p>Your coffee, your next class, your time on court. All in one place.</p></section><p className="hub-section-label">WHERE WOULD YOU LIKE TO GO?</p><nav className="hub-destinations" aria-label="Choose a destination">{[
    {href:'/fond',title:'fond.',copy:'Coffee, good food & rewards',icon:Coffee,color:'#d86432'},
    {href:'/gym',title:'Gym',copy:'Find your everyday energy',icon:Dumbbell,color:'#003c35'},
    {href:'/padel',title:'Padel',copy:'Meet you on the court',icon:Volleyball,color:'#2458cb'},
  ].map(item=><Link href={item.href} key={item.href} style={{'--service':item.color} as React.CSSProperties}><span className="hub-round-icon"><item.icon/></span><div>{item.title!=='fond.'&&<small>MIDPOINT</small>}<h2>{item.title}</h2><p>{item.copy}</p></div><ArrowRight/></Link>)}</nav><div className="hub-place"><span><MapPin size={15}/> Midpoint · Midrand</span><Link href="/functions">Planning a function? <ArrowRight size={15}/></Link></div></HubShell>;
}
export function HubLanding({service}:{service:HubService}) {
  const gym=service==='gym', contact=HUB_CONTACTS[service], venue=gym?null:bookingUrl('padel');
  const actions=gym?[{href:'/gym/signup',label:'Sign up',icon:UserRoundPlus},{href:'/gym/events',label:'Join an event',icon:CalendarDays},{href:'/gym/classes',label:'Join a class',icon:Dumbbell}]:[{href:'/padel/signup',label:'Tenant signup',icon:UserRoundPlus},{href:venue??`mailto:${contact.email}?subject=Midpoint%20Padel%20court%20enquiry`,label:venue?'Book a court':'Court enquiries',icon:Volleyball},{href:'/padel/events',label:'Join an event',icon:CalendarDays}];
  return <HubShell service={service}><HubBack href="/hub">Midpoint Hub</HubBack><div className="hub-photo"><img src={`/hub-assets/${service}.jpg.png`} alt={gym?'Midpoint Gym training floor':'Midpoint rooftop padel courts'}/><span>{gym?'MOVE & RECHARGE':'PLAY & UNWIND'}</span></div><section className="hub-landing"><span className="hub-eyebrow">MIDPOINT {service.toUpperCase()}</span><h1>{gym?<>Make time<br/>for your strength.</>:<>A better way<br/>to end your day.</>}</h1><p>{gym?'A great workout, a fresh start. Right here on the estate.':'Good rallies. Great company. Your next game starts here.'}</p></section><nav className="hub-actions" aria-label={`${service} actions`}>{actions.map(a=><a href={a.href} key={a.label} {...(a.href.startsWith('https:')?{target:'_blank',rel:'noopener noreferrer'}:{})}><span><small>Midpoint {gym?'Gym':'Padel'}</small><a.icon/></span><b>{a.label}</b></a>)}</nav><HubNote title={gym?'Your membership starts here':'A Midpoint tenant? Let’s get you playing.'}>{gym?'Send us your details, then visit the gym. Our team will complete your Itensity registration, finalise payment and set up your gym access.':'Request your tenant setup. Our team will verify your details and help get your Playtomic profile ready. Court bookings are confirmed separately.'}</HubNote><p className="hub-provider">{gym?'Membership & gym access':'Court bookings'} <strong>{gym?'Itensity':'Playtomic'}</strong></p><a className="hub-contact" href={`mailto:${contact.email}`}>Contact {contact.name} · {contact.email}</a></HubShell>;
}
export function HubFunctions() {return <HubShell><HubBack href="/hub">Midpoint Hub</HubBack><section className="hub-hero"><span className="hub-eyebrow">GET TOGETHER AT MIDPOINT</span><h1>Make it<br/>an occasion.</h1><p>Planning a meeting, team gathering or function? Speak to Michelle about your date, group size and what you have in mind.</p></section><a className="hub-primary" href="mailto:michelle@midpointhub.com?subject=Midpoint%20function%20enquiry">Enquire with Michelle <ArrowRight/></a><p className="hub-helper">Availability, catering and pricing are confirmed by the team.</p></HubShell>;}
