'use client';
import {useEffect,useRef,useState} from 'react';
import {Download,Smartphone,Monitor,Check,X} from 'lucide-react';
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export function InstallApp({onHelpChange}:{onHelpChange:(open:boolean)=>void}){
 const [prompt,setPrompt]=useState<InstallEvent|null>(null),[installed,setInstalled]=useState(false),[help,setHelp]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const media=matchMedia('(display-mode: standalone)');const check=()=>setInstalled(media.matches||!!(navigator as Navigator&{standalone?:boolean}).standalone);const capture=(e:Event)=>{e.preventDefault();setPrompt(e as InstallEvent);};const done=()=>{setInstalled(true);setPrompt(null);setHelp(false);};check();media.addEventListener('change',check);window.addEventListener('beforeinstallprompt',capture);window.addEventListener('appinstalled',done);return()=>{media.removeEventListener('change',check);window.removeEventListener('beforeinstallprompt',capture);window.removeEventListener('appinstalled',done);};},[]);
 useEffect(()=>{onHelpChange(help);if(help)dialog.current?.showModal();else dialog.current?.close();},[help,onHelpChange]);
 async function install(){if(!prompt){setHelp(true);return;}setBusy(true);setError('');try{await prompt.prompt();await prompt.userChoice;setPrompt(null);}catch{setError('Your browser could not open installation. Use the steps below.');setHelp(true);}finally{setBusy(false);}}
 return <><section className="install install-feature"><div className="install-device-icons" aria-hidden="true"><Smartphone size={30}/><Monitor size={34}/></div><div className="install-copy"><span className="eyebrow">FOND, ONE TAP AWAY</span><h3>Good food. On your phone or desktop.</h3><p>Install FOND for quick access whenever you’re hungry.</p></div><button className="primary install-primary" disabled={installed||busy} onClick={()=>void install()}>{installed?<Check size={21}/>:<Download size={21}/>} {installed?'FOND is installed':busy?'Opening…':'Install FOND'}</button></section><dialog ref={dialog} className="install-dialog" aria-label="Install FOND" onCancel={()=>setHelp(false)} onClick={e=>{if(e.target===e.currentTarget)setHelp(false);}}><button autoFocus className="install-close" aria-label="Close install instructions" onClick={()=>setHelp(false)}><X/></button><h2>Keep FOND close.</h2><p>Choose the steps for your device.</p>{error&&<p role="alert">{error}</p>}<div className="install-guide"><Smartphone/><div><h3>iPhone or iPad</h3><p>Open FOND in Safari, tap Share, then Add to Home Screen.</p></div></div><div className="install-guide"><Smartphone/><div><h3>Android</h3><p>Open FOND in Chrome. In the browser menu, choose Install app or Add to Home screen.</p></div></div><div className="install-guide"><Monitor/><div><h3>Desktop or laptop</h3><p>In Chrome or Edge, look for the install icon in the address bar or Install FOND in the browser menu. On supported Safari versions, use File → Add to Dock.</p></div></div><p className="small">Options depend on your browser. If installation is unavailable, you can still order here in the browser.</p></dialog></>;
}
