'use client';
import { useState,useEffect,useCallback } from 'react';
import {PromotionEditor,PromotionPreview} from './promotion-editor';
import {ProviderSettings} from './provider-settings';
import {TwoFactorSettings} from './two-factor-settings';
import { money } from '@/lib/menu';
import type { Customer } from '@/lib/business-data';
import type { TradingSettings,SiteContent } from '@/lib/management';

async function api(section:string,body?:unknown){
  const r=await fetch('/api/admin/manage/'+section,{cache:'no-store',...(body!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});
  const d=await r.json();if(!r.ok)throw new Error(d.message??'Request failed.');return d;
}
function useData(section:string){
  const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const refresh=useCallback(async()=>{try{setData(await api(section));setError('');}catch(e){setError((e as Error).message);}},[section]);
  useEffect(()=>{void refresh();},[refresh]);
  async function save(target:string,body:unknown){setBusy(true);setError('');setMessage('');try{await api(target,body);await refresh();setMessage('Saved successfully.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
  return {data,error,busy,message,refresh,save};
}
function Feedback({state}:{state:{error:string;message:string}}){return <>{state.error&&<p className="manage-error" role="alert">{state.error}</p>}{state.message&&<p className="manage-success" role="status">{state.message}</p>}</>;}
function Empty(){return <p className="small">No records yet.</p>;}
const blankCustomer={name:'',phone:'',email:'',company:'',notes:'',marketing_consent:0,consent_note:'',archived:0};
export function CustomersPanel(){
  const [q,setQ]=useState(''),[edit,setEdit]=useState<Partial<Customer>|null>(null),[history,setHistory]=useState<any[]>([]);
  const state=useData('customers?q='+encodeURIComponent(q));
  async function select(c:Customer){setEdit(c);try{setHistory((await api('customers?id='+c.id)).history);}catch{setHistory([]);}}
  return <div className="manage-page"><Feedback state={state}/><div className="manage-toolbar"><p>Customer profiles, consent and linked order history.</p><button className="primary" onClick={()=>{setEdit({...blankCustomer});setHistory([]);}}>Add customer</button></div>
    <label className="field">Search customers<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Name, phone, email or company"/></label>
    <div className="manage-split"><section className="manage-card"><h2>Customer directory</h2>{!state.data?.customers.length?<Empty/>:state.data.customers.map((c:Customer)=><button className="manage-record" key={c.id} onClick={()=>select(c)}><strong>{c.name}{c.archived?' · Archived':''}</strong><span>{c.phone||c.email||'No contact details'} · {c.company||'Individual'}</span><small>{c.marketing_consent?'Marketing consent recorded':'No marketing consent'}</small></button>)}
    <a className="outline" href="/api/admin/manage/customers?export=consented">Export consented contacts</a></section>
    {edit&&<section className="manage-card"><h2>{edit.id?'Edit customer':'New customer'}</h2><form onSubmit={async e=>{e.preventDefault();if(await state.save('customers',edit))setEdit(null);}}>
      {(['name','phone','email','company'] as const).map(k=><label className="field" key={k}>{k[0].toUpperCase()+k.slice(1)}<input required={k==='name'} type={k==='email'?'email':'text'} value={edit[k]??''} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></label>)}
      <label className="field">Internal notes<textarea value={edit.notes??''} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label>
      <label className="field-check"><input type="checkbox" checked={!!edit.marketing_consent} onChange={e=>setEdit({...edit,marketing_consent:e.target.checked?1:0})}/> Marketing consent</label>
      <label className="field">Consent evidence<input value={edit.consent_note??''} onChange={e=>setEdit({...edit,consent_note:e.target.value})} placeholder="Date and how permission was given"/></label>
      <label className="field-check"><input type="checkbox" checked={!!edit.archived} onChange={e=>setEdit({...edit,archived:e.target.checked?1:0})}/> Archive profile</label>
      <button className="primary" disabled={state.busy}>Save customer</button><button type="button" className="quiet" onClick={()=>setEdit(null)}>Close</button></form>
      <h3>Orders linked by phone</h3><p className="small">Phone matches are a convenience, not verified customer identity.</p>{history.length?history.map(o=><p key={o.id}>{o.reference.slice(0,13)} · {o.status} · {money(o.total_cents)}</p>):<Empty/>}</section>}
    </div><section className="manage-card"><h2>Create profiles from recent orders</h2><p className="small">This does not grant marketing consent.</p>{state.data?.recentOrders?.slice(0,20).map((o:any)=><div className="manage-inline" key={o.id}><span>{o.customer_name} · {o.contact_number||'No phone'} · {o.reference.slice(0,13)}</span><button className="quiet" disabled={state.busy} onClick={()=>state.save('customers',{orderId:o.id})}>Create / find profile</button></div>)}</section></div>;
}

export function MarketingPanel(){
  const [uploads,setUploads]=useState(0);const uploading=uploads>0;
  const state=useData('marketing'),[draft,setDraft]=useState<SiteContent|null>(null);
  useEffect(()=>{if(state.data)setDraft(state.data.draft);},[state.data]);
  if(!draft)return <div className="manage-page"><Feedback state={state}/><p>Loading content…</p></div>;
  return <div className="manage-page"><Feedback state={state}/><div className="manage-split"><section className="manage-card"><h2>Website content</h2><p>Save a draft, review the preview, then publish it to the customer website.</p>
    <label className="field">Hero headline<input maxLength={120} value={draft.headline} onChange={e=>setDraft({...draft,headline:e.target.value})}/></label>
    <label className="field">Introduction<textarea maxLength={600} value={draft.intro} onChange={e=>setDraft({...draft,intro:e.target.value})}/></label>
    <label className="field">Announcement<input maxLength={250} value={draft.announcement} onChange={e=>setDraft({...draft,announcement:e.target.value})}/></label>
    <h3>App promotions</h3><p className="small">Choose a text banner, image overlay or popup. Popups appear once per browser session, outside checkout. Dates use your device timezone. Change prices in Menu &amp; specials.</p>
    {draft.promotions.map((p,i)=><PromotionEditor key={p.id} promotion={p} onUploading={busy=>setUploads(n=>Math.max(0,n+(busy?1:-1)))} onChange={value=>setDraft(current=>current?{...current,promotions:current.promotions.map(x=>x.id===p.id?value:x)}:current)} onRemove={()=>setDraft({...draft,promotions:draft.promotions.filter(x=>x.id!==p.id)})}/>)}
    <button className="outline" onClick={()=>setDraft({...draft,promotions:[...draft.promotions,{id:crypto.randomUUID(),title:'',body:'',display:'banner',buttonLabel:'View menu',active:true,startsAt:new Date().toISOString(),endsAt:new Date(Date.now()+86400000*7).toISOString()}]})}>Add promotion</button>
    <div className="manage-actions"><button className="outline" disabled={state.busy||uploading} onClick={()=>state.save('marketing',{content:draft})}>Save draft</button><button className="primary" disabled={state.busy||uploading} onClick={()=>state.save('marketing',{content:draft,publish:true})}>Publish to website</button><button className="quiet" disabled={state.busy||uploading} onClick={()=>state.save('restore-content',{})}>Restore previous publication</button></div>
    </section><section className="manage-card"><p className="eyebrow">DRAFT PREVIEW</p><h2>{draft.headline}</h2><p>{draft.intro}</p>{draft.announcement&&<p className="notice">{draft.announcement}</p>}{draft.promotions.map(p=><PromotionPreview key={p.id} promotion={p}/>)}<h3>Marketing contacts</h3><p>Use the consented-contact export in Customers with your approved messaging provider. Publishing here changes the website; it does not send messages.</p></section></div>
    <section className="manage-card"><h2>Order notification log</h2><button className="quiet" onClick={state.refresh}>Refresh log</button><p>WhatsApp attempts are processed while the staff tablet is open. Provider acceptance does not prove delivery to the phone.</p>{state.data?.jobs.length?state.data.jobs.map((j:any)=><div className="manage-inline" key={j.id}><span>{j.template} · {j.status} · {j.attempts} attempt(s) {j.last_error&&`· ${j.last_error}`}</span>{['failed','not-configured'].includes(j.status)&&<button className="quiet" onClick={()=>state.save('notification-retry',{id:j.id})}>Retry</button>}</div>):<Empty/>}</section>
    <section className="manage-card"><h2>Customer SMS log</h2><p>Twilio delivery callbacks update each accepted and ready message. Queued or sent means Twilio is still processing it; delivered is handset confirmation from the network.</p>{state.data?.smsJobs?.length?state.data.smsJobs.map((j:any)=><div className="manage-inline" key={j.id}><span>{j.template} · {j.status} · {j.attempts} attempt(s) {j.provider_id&&`· ${j.provider_id}`} {j.last_error&&`· ${j.last_error}`}</span>{['failed','undelivered','not-configured'].includes(j.status)&&<button className="quiet" onClick={()=>state.save('sms-retry',{id:j.id})}>Retry SMS</button>}</div>):<Empty/>}</section>
    <section className="manage-card"><h2>Customer email log</h2><p>Verification codes and order emails require a Resend key and verified FOND domain. A provider response records acceptance, not inbox delivery.</p>{state.data?.emailJobs?.length?state.data.emailJobs.map((j:any)=><div className="manage-inline" key={j.id}><span>{j.event} · {j.recipient} · {j.status} {j.error&&`· ${j.error}`}</span>{['failed','pending'].includes(j.status)&&<button className="quiet" onClick={()=>state.save('email-retry',{id:j.id})}>Retry email</button>}</div>):<Empty/>}</section></div>;
}

export function FinancePanel(){
  const [from,setFrom]=useState(new Date(Date.now()-30*86400000).toISOString().slice(0,10)),[to,setTo]=useState(new Date().toISOString().slice(0,10)),[payment,setPayment]=useState({orderId:'',amount:'',method:'cash',reference:''});
  const state=useData(`finance?from=${from}&to=${to}`),summary=state.data?.summary;
  return <div className="manage-page"><Feedback state={state}/><div className="manage-toolbar"><label className="field">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field">To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><a className="outline" href={`/api/admin/manage/finance?from=${from}&to=${to}&export=1`}>Export ledger CSV</a></div>
    <p className="small">South Africa dates. Receipts use payment date; order totals and balances use order date. These are operational records, not bank settlement or tax invoices.</p>
    {summary&&<div className="manage-metrics">{[['Order value',summary.orderValue],['Net receipts',summary.netReceipts],['Outstanding',summary.outstanding],['Cancelled / refund due',summary.refundDue]].map(([label,value])=><div className="manage-card" key={label}><span>{label}</span><strong>{money(Number(value))}</strong></div>)}</div>}
    <section className="manage-card"><h2>Record payment or refund</h2><p>Record money already received or refunded outside this app. This form does not move money.</p><form className="manage-form-grid" onSubmit={async e=>{e.preventDefault();if(await state.save('finance',{orderId:payment.orderId,amountCents:Math.round(Number(payment.amount)*100),method:payment.method,reference:payment.reference}))setPayment({...payment,amount:'',reference:''});}}>
      <label className="field">Order<select required value={payment.orderId} onChange={e=>setPayment({...payment,orderId:e.target.value})}><option value="">Choose order</option>{state.data?.orders.map((o:any)=><option key={o.id} value={o.id}>{o.customer_name} · {o.reference.slice(0,13)} · {money(o.total_cents)}</option>)}</select></label>
      <label className="field">Amount (R)<input required type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label>
      <label className="field">Method<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option value="cash">Cash</option><option value="card">Card at restaurant</option><option value="eft">EFT</option><option value="refund">Refund already issued</option></select></label>
      <label className="field">Unique receipt / reference<input required value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label><button className="primary" disabled={state.busy}>Record transaction</button></form></section>
    <section className="manage-card"><h2>Order reconciliation</h2><div className="manage-table"><table><thead><tr><th>Customer / order</th><th>Status</th><th>Value</th><th>Paid</th><th>Balance</th></tr></thead><tbody>{state.data?.orders.map((o:any)=><tr key={o.id}><td>{o.customer_name}<small>{o.reference}</small></td><td>{o.status}</td><td>{money(o.total_cents)}</td><td>{money(o.paid_cents)}</td><td>{money(o.total_cents-o.paid_cents)}</td></tr>)}</tbody></table></div></section>
    <section className="manage-card"><h2>Online checkout reconciliation</h2><p>Pending checkouts must be checked in Yoco before taking another payment. A return to this site is not payment confirmation. Ask Yoco to redeliver a missing payment webhook; do not take a second payment while the result is uncertain.</p>{state.data?.checkouts?.length?state.data.checkouts.map((c:any)=><p key={c.order_id}>{c.reference.slice(0,13)} · {c.checkout_id||"Creation awaiting confirmation"} · {c.status}</p>):<Empty/>}<button className="quiet" onClick={state.refresh}>Refresh reconciliation</button></section><section className="manage-card"><h2>Payment ledger</h2>{state.data?.payments.length?state.data.payments.map((p:any)=><div className="manage-inline" key={p.id}><span>{new Date(p.created_at).toLocaleString()} · {p.method} · {p.reference}</span><strong>{money(p.amount_cents)}</strong></div>):<Empty/>}</section></div>;
}

export function SettingsPanel(){
  const state=useData('settings'),[form,setForm]=useState<TradingSettings|null>(null),[member,setMember]=useState({id:undefined as string|undefined,name:'',username:'',role:'staff',password:'',active:true});
  useEffect(()=>{if(state.data)setForm(state.data.settings);},[state.data]);
  if(!form)return <div className="manage-page"><Feedback state={state}/><p>Loading settings…</p></div>;
  return <div className="manage-page"><Feedback state={state}/><div className="manage-split"><section className="manage-card"><h2>Trading & fulfilment</h2><form onSubmit={e=>{e.preventDefault();void state.save('settings',form);}}>
    {([['orderingEnabled','Accept orders'],['collectionEnabled','Allow collection'],['deliveryEnabled','Allow delivery'],['enforceHours','Enforce trading hours']] as const).map(([k,label])=><label className="field-check" key={k}><input type="checkbox" checked={form[k]} onChange={e=>setForm({...form,[k]:e.target.checked})}/>{label}</label>)}
    <p className="small">Trading hours use Africa/Johannesburg. Closing prevents new orders; existing orders can still be completed.</p>
    <div className="manage-days">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=><label key={d}><input type="checkbox" checked={form.openDays.includes(i)} onChange={e=>setForm({...form,openDays:e.target.checked?[...form.openDays,i]:form.openDays.filter(n=>n!==i)})}/>{d}</label>)}</div>
    {(['openingTime','closingTime'] as const).map(k=><label className="field" key={k}>{k==='openingTime'?'Opens':'Closes'}<input type="time" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}
    <label className="field">Maximum active orders<input type="number" min="1" value={form.maxActiveOrders} onChange={e=>setForm({...form,maxActiveOrders:Number(e.target.value)})}/></label>
    <h3>Order queue timing targets</h3><p className="small">An order is marked Delayed after it exceeds the target for its current stage.</p>
    <div className="manage-form-grid">{([['newOrderMinutes','New order'],['paymentConfirmationMinutes','Yoco payment confirmation'],['yocoEntryMinutes','Yoco system entry'],['preparationMinutes','Preparing'],['readyDeliveryMinutes','Ready for delivery'],['readyCollectionMinutes','Ready for collection']] as const).map(([k,label])=><label className="field" key={k}>{label} (minutes)<input type="number" min="1" max="240" value={form[k]} onChange={e=>setForm({...form,[k]:Number(e.target.value)})}/></label>)}</div>
    <label className="field">Menu preparation uncertainty buffer (%)<input type="number" min="5" max="8" value={form.preparationWeightPercent} onChange={e=>setForm({...form,preparationWeightPercent:Number(e.target.value)})}/></label>
    {([['deliveryArea','Delivery area / instructions'],['contactPhone','Contact phone'],['closedMessage','Closed message']] as const).map(([k,label])=><label className="field" key={k}>{label}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}
    <label className="field">Collection options (one per line)<textarea value={form.collectionSlots.join('\n')} onChange={e=>setForm({...form,collectionSlots:e.target.value.split('\n')})}/></label>
    {state.data.role==='super-admin'&&<><h3>Payment & notifications · super admin</h3><label className="field-check"><input type="checkbox" checked={form.onlinePaymentsEnabled} onChange={e=>setForm({...form,onlinePaymentsEnabled:e.target.checked})}/> Offer online Yoco checkout when configured</label><label className="field-check"><input type="checkbox" checked={form.allowTestPayments} onChange={e=>setForm({...form,allowTestPayments:e.target.checked})}/> Allow Yoco sandbox webhook processing</label><p>Yoco credentials: <strong>{state.data.providers.yoco?'Configured':'Not configured'}</strong></p>
    <label className="field-check"><input type="checkbox" checked={form.smsEnabled} onChange={e=>setForm({...form,smsEnabled:e.target.checked})}/> Enable transactional SMS</label><p>SMS credentials: <strong>{state.data.providers.sms?'Configured':'Not configured'}</strong></p><label className="field-check"><input type="checkbox" checked={form.whatsappEnabled} onChange={e=>setForm({...form,whatsappEnabled:e.target.checked})}/> Enable transactional WhatsApp</label><p>WhatsApp credentials: <strong>{state.data.providers.whatsapp?'Configured':'Not configured'}</strong></p></>}
    <p className="small">Super admins enter provider keys and the shared tablet code below. Online payment confirmation requires a signed Yoco webhook. SMS uses the Twilio number configured below. WhatsApp requires an approved sender and templates.</p><button className="primary" disabled={state.busy}>Save settings</button></form></section>
    {state.data.role==='super-admin'&&<section className="manage-card"><h2>Team & permissions · super admin</h2><p>Staff manage orders. Admins manage operations, but cannot change provider credentials or team access. Super admins manage all settings. Named sessions expire after 12 hours; editing a member revokes their sessions.</p><div className="manage-team">{state.data.team.map((m:any)=><button className="manage-record" key={m.id} onClick={()=>setMember({...m,password:'',active:!!m.active})}><strong>{m.name}</strong><span>{m.username} · {m.role} · {m.active?'Active':'Disabled'}</span></button>)}</div>
    <h3>{member.id?'Edit team member':'Add team member'}</h3><form onSubmit={async e=>{e.preventDefault();if(await state.save('team',member))setMember({id:undefined,name:'',username:'',role:'staff',password:'',active:true});}}>
      <label className="field">Member name<input required value={member.name} onChange={e=>setMember({...member,name:e.target.value})}/></label><label className="field">Username<input required value={member.username} onChange={e=>setMember({...member,username:e.target.value})}/></label><label className="field">Role<select value={member.role} onChange={e=>setMember({...member,role:e.target.value})}><option value="staff">Staff — orders only</option><option value="manager">Admin — operations</option><option value="super-admin">Super admin — providers & access</option></select></label>
      <label className="field">{member.id?'New password (leave blank to keep)':'Password (12+ characters)'}<input type="password" autoComplete="new-password" minLength={12} required={!member.id} value={member.password} onChange={e=>setMember({...member,password:e.target.value})}/></label><label className="field-check"><input type="checkbox" checked={member.active} onChange={e=>setMember({...member,active:e.target.checked})}/> Active account</label><button className="primary" disabled={state.busy}>Save team member</button><button type="button" className="quiet" onClick={()=>setMember({id:undefined,name:'',username:'',role:'staff',password:'',active:true})}>New member</button></form>
    <p className="small">The shared staff code remains available for the tablet. The shared admin code stops working after a named super admin enables 2FA.</p></section>}</div>
    <TwoFactorSettings/>{state.data.role==='super-admin'&&<ProviderSettings/>}{state.data.role==='super-admin'&&<section className="manage-card"><h2>Administration activity</h2>{state.data.audit.length?state.data.audit.map((e:any)=><div className="manage-inline" key={e.id}><span>{e.action} · {e.target}</span><small>{e.actor} · {new Date(e.created_at).toLocaleString()}</small></div>):<Empty/>}</section>}</div>;
}
