'use client';
import {useEffect,useRef,useState} from 'react';
export function MembershipScanner({value,onChange}:{value:string;onChange:(value:string)=>void}){
 const [camera,setCamera]=useState(false),[message,setMessage]=useState(''),[checking,setChecking]=useState(false),[verified,setVerified]=useState('');
 const video=useRef<HTMLVideoElement>(null),version=useRef(0);
 useEffect(()=>{version.current++;setVerified('');setMessage('');},[value]);
 useEffect(()=>{if(!camera)return;let stopped=false,stream:MediaStream|undefined,timer:ReturnType<typeof setTimeout>;
  (async()=>{try{const Detector=(window as any).BarcodeDetector;if(!Detector)throw new Error('Camera scanning is not supported in this browser. Type the membership number below or use a USB QR scanner.');
   stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});if(stopped){stream.getTracks().forEach(t=>t.stop());return;}video.current!.srcObject=stream;await video.current!.play();const detector=new Detector({formats:['qr_code']});
   const scan=async()=>{if(stopped)return;try{const found=await detector.detect(video.current!);if(stopped)return;const code=found.find((v:any)=>/^FOND-M-[A-F0-9]{12}$/.test(v.rawValue))?.rawValue;if(code){onChange(code);setCamera(false);return;}}catch{}timer=setTimeout(scan,300);};await scan();
  }catch(e){if(!stopped){setMessage((e as Error).message);setCamera(false);}}})();return()=>{stopped=true;clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop());};
 },[camera,onChange]);
 async function check(){const v=++version.current;setChecking(true);setMessage('');try{const r=await fetch('/api/staff/membership',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:value})}),d=await r.json();if(v!==version.current)return;if(!r.ok)throw new Error(d.message);setVerified(`Membership confirmed: ${d.email}. ${d.enabled?'Stamps follow verified payment and collection.':'Counter earning is paused. Membership can be saved, but the Yoco connection must be ready before confirming this rewards order.'}`);}catch(e){if(v===version.current)setMessage((e as Error).message);}finally{setChecking(false);}}
 return <section className="basket-rewards membership-scanner"><h3>Earn coffee stamps</h3><p>Before adding the order, ask the customer to open Account → Coffee rewards and show their membership QR.</p><button type="button" className="outline" onClick={()=>setCamera(!camera)}>{camera?'Stop camera':'Scan customer rewards'}</button>{camera&&<video ref={video} muted playsInline aria-label="Membership QR camera"/>}<label className="field">Customer membership number<input value={value} onChange={e=>onChange(e.target.value.toUpperCase())} placeholder="FOND-M-…" maxLength={40} autoComplete="off"/></label><button type="button" className="outline" disabled={!value||checking} onClick={check}>{checking?'Checking…':'Check membership'}</button>{value&&<button type="button" className="quiet" onClick={()=>onChange('')}>Remove membership</button>}{verified&&<p role="status">{verified}</p>}{message&&<p role="alert">{message}</p>}<small>Optional. A membership identifies the customer; it is separate from a free-coffee redemption code.</small></section>;
}
