'use client';
import {useEffect,useMemo,useState} from 'react';
import {ACTIVE_EMAIL_MESSAGE_KEYS,SAMPLE_MESSAGE_VALUES,SMS_MESSAGE_KEYS,renderMessageText,type EmailMessageKey,type MessageTemplateConfig,type SmsMessageKey} from '@/lib/message-template-config';

const emailLabels:Record<(typeof ACTIVE_EMAIL_MESSAGE_KEYS)[number],string>={received:'Order received',readyCollection:'Ready · collection',readyDelivery:'Ready · delivery'};
const smsLabels:Record<SmsMessageKey,string>={accepted:'Order accepted',readyCollection:'Ready · collection',readyDelivery:'Ready · delivery'};
const clone=(value:MessageTemplateConfig)=>JSON.parse(JSON.stringify(value)) as MessageTemplateConfig;

export function MessagingStudio({initialDraft,published,busy,onSave}:{initialDraft:MessageTemplateConfig;published:MessageTemplateConfig;busy:boolean;onSave:(body:unknown)=>Promise<boolean>}){
  const [draft,setDraft]=useState(()=>clone(initialDraft)),[channel,setChannel]=useState<'email'|'sms'>('email'),[emailKey,setEmailKey]=useState<EmailMessageKey>('received'),[smsKey,setSmsKey]=useState<SmsMessageKey>('accepted'),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState('');
  useEffect(()=>setDraft(clone(initialDraft)),[initialDraft]);
  const changed=useMemo(()=>JSON.stringify(draft)!==JSON.stringify(published),[draft,published]);
  const email=draft.email.templates[emailKey],sms=draft.sms[smsKey],sampleEmail={subject:renderMessageText(email.subject,SAMPLE_MESSAGE_VALUES),title:renderMessageText(email.title,SAMPLE_MESSAGE_VALUES),status:renderMessageText(email.status,SAMPLE_MESSAGE_VALUES),intro:renderMessageText(email.intro,SAMPLE_MESSAGE_VALUES)},sampleSms=renderMessageText(sms,SAMPLE_MESSAGE_VALUES);
  const updateEmail=(field:keyof typeof email,value:string)=>setDraft(current=>({...current,email:{...current.email,templates:{...current.email.templates,[emailKey]:{...current.email.templates[emailKey],[field]:value}}}}));
  async function upload(file?:File){if(!file)return;setUploading(true);setUploadError('');try{const form=new FormData();form.set('image',file);const response=await fetch('/api/admin/promotion-images',{method:'POST',body:form}),data=await response.json();if(!response.ok)throw new Error(data.message??'Upload failed.');setDraft(current=>({...current,email:{...current.email,banner:{...current.email.banner,imageUrl:data.url}}}));}catch(error){setUploadError((error as Error).message);}finally{setUploading(false);}}
  return <section className="manage-card messaging-studio"><div className="manage-toolbar"><div><p className="eyebrow">MESSAGING STUDIO</p><h2>Email and SMS templates</h2><p>Build transactional messages here, review the preview, then publish. Published changes apply to future messages only.</p></div><span className={changed?'studio-status draft':'studio-status live'}>{changed?'Draft differs from live':'Live version shown'}</span></div>
    <div className="tabs" role="tablist" aria-label="Message channel"><button type="button" aria-selected={channel==='email'} onClick={()=>setChannel('email')}>Email</button><button type="button" aria-selected={channel==='sms'} onClick={()=>setChannel('sms')}>SMS</button><button type="button" aria-selected={false} disabled title="WhatsApp templates require provider approval">WhatsApp · provider managed</button></div>
    {channel==='email'?<div className="studio-grid"><div className="studio-editor"><div className="provider-note"><strong>Customer email journey:</strong> FOND sends an order receipt first, then one ready email matched to collection or delivery. Accepted and completed remain staff workflow stages without extra customer email.</div><label className="field">Order stage<select value={emailKey} onChange={event=>setEmailKey(event.target.value as EmailMessageKey)}>{ACTIVE_EMAIL_MESSAGE_KEYS.map(key=><option key={key} value={key}>{emailLabels[key]}</option>)}</select></label>
      <p className="small">Available placeholders: {'{customerName}'} · {'{reference}'} · {'{prepMinutes}'} · {'{collectionTime}'} · {'{destination}'} · {'{total}'}. Every subject must retain {'{reference}'}.</p>
      <label className="field">Email subject<input maxLength={150} value={email.subject} onChange={event=>updateEmail('subject',event.target.value)}/></label>
      <label className="field">Status-banner heading<input maxLength={120} value={email.title} onChange={event=>updateEmail('title',event.target.value)}/></label>
      <label className="field">Status-banner detail<input maxLength={180} value={email.status} onChange={event=>updateEmail('status',event.target.value)}/></label>
      <label className="field">Customer message<textarea maxLength={600} value={email.intro} onChange={event=>updateEmail('intro',event.target.value)}/></label>
      <h3>Ready-email upsell banner</h3><p className="small">This optional banner appears only after the customer’s order is ready, when the next-order prompt is useful. It is not added to the order receipt.</p><label className="field-check"><input type="checkbox" checked={draft.email.banner.enabled} onChange={event=>setDraft(current=>({...current,email:{...current.email,banner:{...current.email.banner,enabled:event.target.checked}}}))}/> Include this banner in ready emails</label>
      <label className="field">Banner image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>void upload(event.target.files?.[0])}/></label><p className="small">JPG, PNG or WebP, up to 2 MB. Use a wide image. Some email apps hide images until the recipient allows them, so the text remains complete without it.</p>{uploading&&<p role="status">Uploading banner…</p>}{uploadError&&<p role="alert" className="manage-error">{uploadError}</p>}{draft.email.banner.imageUrl&&<button type="button" className="quiet" onClick={()=>setDraft(current=>({...current,email:{...current.email,banner:{...current.email.banner,imageUrl:''}}}))}>Remove banner image</button>}
      <label className="field">Image description<input maxLength={120} value={draft.email.banner.imageAlt} onChange={event=>setDraft(current=>({...current,email:{...current.email,banner:{...current.email.banner,imageAlt:event.target.value}}}))}/></label>
      {(['eyebrow','title','body','buttonLabel','buttonUrl'] as const).map(field=><label className="field" key={field}>{field==='eyebrow'?'Small banner label':field==='title'?'Banner heading':field==='body'?'Banner message':field==='buttonLabel'?'Button text':'Button link'}{field==='body'?<textarea maxLength={400} value={draft.email.banner[field]} onChange={event=>setDraft(current=>({...current,email:{...current.email,banner:{...current.email.banner,[field]:event.target.value}}}))}/>:<input maxLength={field==='buttonUrl'?500:field==='title'?100:field==='eyebrow'?60:40} value={draft.email.banner[field]} placeholder={field==='buttonUrl'?'/ or https://…':''} onChange={event=>setDraft(current=>({...current,email:{...current.email,banner:{...current.email.banner,[field]:event.target.value}}}))}/>}</label>)}
      <label className="field">Email footer<textarea maxLength={300} value={draft.email.footer} onChange={event=>setDraft(current=>({...current,email:{...current.email,footer:event.target.value}}))}/></label></div>
      <div className="studio-preview"><p className="eyebrow">LIVE PREVIEW · SAMPLE ORDER</p><p className="studio-subject"><strong>Subject:</strong> {sampleEmail.subject}</p><div className="email-mini"><div className="email-mini-logo">fond<span>.</span></div><div className={`email-mini-status ${emailKey.startsWith('ready')?'is-ready':''}`}>{emailKey.startsWith('ready')&&<em>ORDER READY</em>}<strong>{sampleEmail.title}</strong><small>{sampleEmail.status}</small></div><div className="email-mini-body"><h4>Your order details</h4><dl><dt>Order:</dt><dd>{SAMPLE_MESSAGE_VALUES.reference}</dd><dt>Name:</dt><dd>{SAMPLE_MESSAGE_VALUES.customerName}</dd><dt>Fulfilment:</dt><dd>{emailKey==='readyDelivery'?'Delivery':'Collection'}</dd><dt>Total:</dt><dd>{SAMPLE_MESSAGE_VALUES.total}</dd></dl><p>{sampleEmail.intro}</p>{emailKey.startsWith('ready')&&draft.email.banner.enabled&&<div className="email-mini-banner">{draft.email.banner.imageUrl&&<img src={draft.email.banner.imageUrl} alt={draft.email.banner.imageAlt}/>}<small>{draft.email.banner.eyebrow}</small><h4>{draft.email.banner.title}</h4><p>{draft.email.banner.body}</p>{draft.email.banner.buttonLabel&&<span>{draft.email.banner.buttonLabel}</span>}</div>}</div><div className="email-mini-footer">{draft.email.footer}</div></div></div></div>:<div className="studio-grid"><div className="studio-editor"><label className="field">Order stage<select value={smsKey} onChange={event=>setSmsKey(event.target.value as SmsMessageKey)}>{SMS_MESSAGE_KEYS.map(key=><option key={key} value={key}>{smsLabels[key]}</option>)}</select></label><p className="small">Available placeholders: {'{reference}'} and {'{customerName}'}. The order reference is required so staff and customers can identify the same order.</p><label className="field">SMS message<textarea maxLength={320} value={sms} onChange={event=>setDraft(current=>({...current,sms:{...current.sms,[smsKey]:event.target.value}}))}/></label><p className="small">{sampleSms.length}/320 characters after sample placeholders. Longer SMS messages may be billed and delivered as multiple segments.</p><div className="provider-note"><strong>Transactional use only.</strong> These messages go only to customers who opted in during their order. Promotional campaigns must use recorded marketing consent and an unsubscribe process.</div></div><div className="studio-preview"><p className="eyebrow">PHONE PREVIEW</p><div className="sms-phone"><small>FOND · now</small><p>{sampleSms}</p></div><p className="small">WhatsApp wording remains in Meta or Twilio because each business-initiated template must be provider approved.</p></div></div>}
    <div className="manage-actions"><button type="button" className="outline" disabled={busy||uploading} onClick={()=>void onSave({content:draft})}>Save message draft</button><button type="button" className="primary" disabled={busy||uploading} onClick={()=>void onSave({content:draft,publish:true})}>Publish to future messages</button><button type="button" className="quiet" disabled={busy||uploading} onClick={()=>void onSave({restore:true})}>Restore previous publication</button></div>
  </section>;
}
