'use client';
import { useEffect, useState } from 'react';
import { ArrowRight, Check, Clock3, Coffee, Leaf, MapPin, Minus, Plus, ShoppingBag, Utensils, X, Download, History } from 'lucide-react';
import { menu, money, quoteCart, type CartLine, type Category } from '@/lib/menu';
type DemoOrder = {reference:string; total:number; lines:CartLine[]; collection:string};
type InstallEvent = Event & {prompt:()=>Promise<void>; userChoice:Promise<{outcome:string}>};
export function OrderingApp() {
 const [category,setCategory]=useState<Category>('Breakfast');
 const [cart,setCart]=useState<CartLine[]>([]);
 const [panel,setPanel]=useState<'basket'|'history'|null>(null);
 const [collection,setCollection]=useState('As soon as possible');
 const [orders,setOrders]=useState<DemoOrder[]>([]);
 const [confirmation,setConfirmation]=useState<DemoOrder|null>(null);
 const [error,setError]=useState('');
 const [install,setInstall]=useState<InstallEvent|null>(null);
 const [offline,setOffline]=useState(false);
 useEffect(()=>{
   if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{});
   const capture=(event:Event)=>{event.preventDefault();setInstall(event as InstallEvent)};
   const connectivity=()=>setOffline(!navigator.onLine);
   window.addEventListener('beforeinstallprompt',capture);window.addEventListener('online',connectivity);window.addEventListener('offline',connectivity);connectivity();
   return ()=>{window.removeEventListener('beforeinstallprompt',capture);window.removeEventListener('online',connectivity);window.removeEventListener('offline',connectivity)};
 },[]);
 useEffect(()=>{if(!panel)return;const previousFocus=document.activeElement as HTMLElement|null;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setPanel(null);if(e.key==='Tab'){const elements=Array.from(document.querySelectorAll<HTMLElement>('[role="dialog"] button:not(:disabled), [role="dialog"] select, [role="dialog"] a[href]'));const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',close);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',close);document.body.style.overflow=previous;previousFocus?.focus()}},[panel]);
 const count=cart.reduce((n,l)=>n+l.quantity,0);
 const total=cart.reduce((n,l)=>n+(menu.find(m=>m.id===l.id)?.price??0)*l.quantity,0);
 function change(id:string,delta:number){setConfirmation(null);setError('');setCart(current=>{const qty=current.find(l=>l.id===id)?.quantity??0;const next=Math.max(0,Math.min(20,qty+delta));return [...current.filter(l=>l.id!==id),...(next?[{id,quantity:next}]:[])]})}
 function preview(){try{if(offline)throw new Error('Reconnect before continuing.');const priced=quoteCart(cart);const order={reference:`DEMO-${crypto.randomUUID().slice(0,8).toUpperCase()}`,total:priced.reduce((n,l)=>n+l.subtotal,0),lines:[...cart],collection};setConfirmation(order);setOrders(current=>[order,...current]);setCart([])}catch(e){setError(e instanceof Error?e.message:'Please check your basket.')}}
 return <>
 <div className="preview-ribbon">A taste of what’s coming <span>•</span> Preview only — no real orders or payments</div>
 <header className="header"><a href="/" className="wordmark" aria-label="FOND home">fond<span>.</span></a><div className="location"><MapPin size={16}/><div><strong>Midpoint</strong><small>Collect from FOND</small></div></div><nav><button className="quiet history" onClick={()=>{setPanel('history');setConfirmation(null)}}><History size={18}/> My previews</button><button className="basket-button" aria-label="Basket" onClick={()=>setPanel('basket')}><ShoppingBag size={18}/><span>Basket</span><b>{count}</b></button></nav></header>
 <main id="main">
 <section className="hero"><div className="hero-copy"><p className="eyebrow"><span/> YOUR EVERYDAY FOOD STOP</p><h1>Good food.<br/>One less thing<br/><em>to think about.</em></h1><p className="intro">From your first meeting to your last set.<br/>Fresh breakfast, proper lunch and a little lift.<br/>Made for your day at Midpoint.</p><a className="primary hero-cta" href="#menu">Find your favourite <ArrowRight size={18}/></a><div className="hero-foot"><Leaf size={16}/> Freshly made <span>·</span><ShoppingBag size={16}/> Easy collection</div></div>
 <div className="hero-art" aria-label="Illustration of a fresh breakfast bowl"><div className="art-label">a little<br/><i>everyday good.</i></div><div className="plate"><div className="greens g1"/><div className="greens g2"/><div className="greens g3"/><div className="toast"><span/><span/><span/></div><div className="egg"><div/></div><div className="tomato t1"/><div className="tomato t2"/><div className="seed s1"/><div className="seed s2"/></div><div className="floating-note"><span>Made for your</span><strong>midday moment.</strong><div>✦</div></div><span className="art-caption">A FOND MENU CONCEPT · MIDPOINT</span></div></section>
 <section className="promise"><span><Coffee size={20}/> Before work.</span><span><Utensils size={20}/> Between meetings.</span><span><Leaf size={20}/> After your workout.</span><strong>We’ve got your day.</strong></section>
 <section id="menu" className="menu-section"><div className="section-top"><div><p className="eyebrow">SOMETHING GOOD, WHEN YOU NEED IT</p><h2>What are you in the mood for?</h2></div><div className="collection-badge"><Clock3 size={18}/><span>Order ahead.<br/><strong>Collect at Midpoint.</strong></span></div></div><div className="menu-toolbar"><div className="tabs" role="tablist" aria-label="Meal category">{(['Breakfast','Lunch','Smoothies'] as Category[]).map(c=><button role="tab" aria-selected={category===c} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><p>Proposed menu · illustrative prices</p></div>
 <div className="meal-grid" role="tabpanel" aria-label={category}>{menu.filter(m=>m.category===category).map(m=><article className="meal-card" key={m.id}><div className={`meal-art ${m.tone}`}><span className="meal-tag">{m.tag}</span><div className="food-symbol" aria-hidden="true">{m.symbol}</div><span className="art-mark">fond.</span></div><div className="meal-content"><h3>{m.name}</h3><p>{m.description}</p><div className="meal-bottom"><strong>{money(m.price)}</strong><button className="add" aria-label={`Add ${m.name}`} onClick={()=>change(m.id,1)}><Plus size={18}/> Add{cart.find(l=>l.id===m.id)?` (${cart.find(l=>l.id===m.id)!.quantity})`:''}</button></div></div></article>)}</div><p className="allergen-note">Meal concepts are for review. Final ingredients, allergens, availability and prices will be confirmed before ordering opens.</p></section>
 <section className="daily"><div><p className="eyebrow">LESS PLANNING. MORE ENJOYING.</p><h2>Your lunch break.<br/><em>Made a little better.</em></h2></div><p>Something fresh around the corner.<br/>Something good to look forward to.<br/>Something you didn’t have to pack.</p></section>
 <section className="install"><div><h3>A little FOND on your phone.</h3><p>Add this preview to your home screen for easy access.</p></div>{install?<button className="outline" onClick={async()=>{await install.prompt();await install.userChoice;setInstall(null)}}><Download size={17}/> Install FOND</button>:<p className="install-help">In your browser menu, choose “Add to Home Screen”<br/>or “Install app”, if available.</p>}</section>
 </main><footer><a className="wordmark" href="/">fond.</a><span>Good food. Everyday.</span><span>Midpoint · Collection concept</span></footer>
 {offline&&<div className="offline" role="status">You’re offline. Reconnect to continue.</div>}
 <button className="mobile-basket" onClick={()=>setPanel('basket')}><ShoppingBag size={18}/> View basket ({count}) <strong>{money(total)}</strong></button>
 {panel&&<div className="overlay" onClick={()=>setPanel(null)}><section className="drawer" role="dialog" aria-modal="true" aria-label={panel==='basket'?'Your basket':'My previews'} onClick={e=>e.stopPropagation()}><header><div><p className="eyebrow">FOND · MIDPOINT</p><h2>{panel==='basket'?'Your basket':'My previews'}</h2></div><button autoFocus className="icon-button" aria-label="Close basket" onClick={()=>setPanel(null)}><X/></button></header><div className="drawer-scroll">
 {panel==='history'?<><p className="notice">Demo history for this visit only. Account sign-in and saved orders will be enabled in a later stage.</p>{orders.length?orders.map(o=><article className="history-card" key={o.reference}><strong>{o.reference}</strong><p>{o.collection} · {money(o.total)}</p><button className="outline" onClick={()=>{setCart(o.lines);setConfirmation(null);setPanel('basket')}}>Try this basket again</button></article>):<div className="empty"><History/><h3>Your everyday favourites, remembered.</h3><p>Complete a demo basket to try reordering here.</p></div>}</>:confirmation?<div className="confirmation"><span className="check"><Check/></span><h3>Your preview is ready.</h3><p className="reference">{confirmation.reference}</p><p>{confirmation.collection}</p><strong>{money(confirmation.total)}</strong><p className="notice">This is a demonstration. Nothing has been sent to FOND or Yoco, no payment has been taken, and no collection time has been reserved.</p><p>The planned next step is staff acceptance in Yoco, followed by kitchen printing. This connection is awaiting confirmation.</p><button className="primary" onClick={()=>{setPanel(null);setConfirmation(null)}}>Back to the menu <ArrowRight size={18}/></button></div>:cart.length?<><p className="notice">Preview basket · illustrative pricing</p>{cart.map(l=>{const m=menu.find(m=>m.id===l.id)!;return <div className="cart-line" key={l.id}><span className={`cart-art ${m.tone}`} aria-hidden="true">{m.symbol}</span><div><h3>{m.name}</h3><p>{money(m.price)}</p><div className="quantity"><button aria-label={`Remove one ${m.name}`} onClick={()=>change(m.id,-1)}><Minus size={14}/></button><span>{l.quantity}</span><button disabled={l.quantity>=20} aria-label={`Add one ${m.name}`} onClick={()=>change(m.id,1)}><Plus size={14}/></button></div></div><strong>{money(m.price*l.quantity)}</strong></div>})}<label className="field">Preferred collection<select value={collection} onChange={e=>setCollection(e.target.value)}><option>As soon as possible</option><option>Breakfast collection</option><option>Lunch collection</option><option>After-work collection</option></select></label><p className="small">Collection windows are illustrative. Actual hours and capacity will be confirmed with FOND.</p><div className="total"><span>Total</span><strong>{money(total)}</strong></div>{error&&<p role="alert">{error}</p>}<button className="primary full" disabled={offline} onClick={preview}>Preview order <ArrowRight size={18}/></button><p className="small center">No payment required. This will not place a real order.</p></>:<div className="empty"><ShoppingBag/><h3>A little something good?</h3><p>Your basket is waiting for its first favourite.</p><button className="primary" onClick={()=>setPanel(null)}>Explore the menu <ArrowRight size={18}/></button></div>}
 </div></section></div>}
 </>;
}
