import Link from 'next/link';
import {ArrowLeft,ArrowRight,CalendarDays,Info,Tag,UsersRound} from 'lucide-react';
import {ServiceLanding} from './service-landing';
import {HubAppNav} from './hub-app-nav';
import {HUB_CONTACTS} from '@/lib/hub-config';
import './gym-pages.css';

export const PADEL_BOOKING_URL='https://playtomic.com/clubs/midpoint-padel';
const actions=[{href:'/padel/prices',label:'Court prices',icon:Tag},{href:'/padel/events',label:'Events & leagues',icon:CalendarDays},{href:'/padel/signup',label:'Join Midpoint Padel',icon:UsersRound},{href:'/padel/info',label:'How it works',icon:Info}];
export function PadelLanding(){return <ServiceLanding service="Padel" image="/hub-assets/tile-padel-2.webp" alt="Padel courts at Midpoint" title={<>Play.<br/>Connect.<br/>Repeat.</>} description="Rooftop padel at Midpoint. Book a court, join an event or play with your team." href={PADEL_BOOKING_URL} action="Book a court"><nav className="gym-landing-actions" aria-label="Padel actions">{actions.map(({href,label,icon:Icon})=><Link href={href} key={href}><Icon size={20} strokeWidth={1.7}/><span>{label}</span><ArrowRight size={16}/></Link>)}</nav></ServiceLanding>}
export function PadelShell({children}:{children:React.ReactNode}){return <main className="gym-experience padel-experience"><header className="gym-page-header"><Link href="/padel" aria-label="Back to Padel"><ArrowLeft size={21}/></Link><Link href="/padel" className="gym-wordmark" aria-label="Midpoint Padel">MIDPOINT<span>PADEL</span></Link><span aria-hidden="true" style={{width:44}}/></header>{children}<footer className="gym-page-footer"><Link href="/hub/privacy">Privacy policy</Link><Link href="/hub/terms">Terms and conditions</Link></footer><HubAppNav/></main>}
export function PadelInformation({section}:{section:'prices'|'info'}){const contact=HUB_CONTACTS.padel;return <PadelShell><section className="gym-information"><p className="gym-kicker">MIDPOINT / PADEL</p><h1>{section==='prices'?'Make time for a game.':'See you on court.'}</h1>{section==='prices'?<><p>Choose your court time and bring your team.</p><section className="gym-prices" aria-label="Padel court prices"><div className="gym-membership-plans"><article className="gym-price-card"><p className="gym-kicker">TENANT</p><h2>Book at the Proshop.</h2><dl><div><dt>60 minutes</dt><dd>R280</dd></div><div><dt>90 minutes</dt><dd>R350</dd></div></dl></article><article className="gym-price-card"><p className="gym-kicker">PUBLIC</p><h2>Book on Playtomic.</h2><dl><div><dt>60 minutes</dt><dd>R350</dd></div><div><dt>90 minutes</dt><dd>R550</dd></div></dl></article></div><p className="gym-price-note">Terms and conditions apply. Prices are subject to change. Confirm the applicable rate when booking.</p></section></>:<><p>Rooftop padel at Midpoint Hub. Bring your friends, colleagues or your next doubles partner.</p><div className="gym-information-card"><h2>Book your court</h2><p>Public court bookings are handled on Playtomic. Choose a time and follow its booking and payment steps. Midpoint tenants can book at the Proshop.</p><h2>For Midpoint tenants</h2><p><Link href="/padel/signup">Leave your details</Link> and Ali’s team will verify your tenant profile and help you get set up. Sending a request does not reserve a court.</p><h2>Events &amp; leagues</h2><p><Link href="/padel/events">Explore the published events</Link> and send your interest to the team. They will confirm places and participation.</p><h2>Find us</h2><p>Midpoint Hub<br/>162 Tonetti Street, Halfway House, Midrand</p></div></>}<a className="gym-primary" href={PADEL_BOOKING_URL} target="_blank" rel="noopener noreferrer">Book a court <ArrowRight size={18}/></a><a className="gym-contact" href={`mailto:${contact.email}`}>Contact {contact.name}<span>{contact.email}</span><ArrowRight size={18}/></a><Link className="gym-back" href="/padel"><ArrowLeft size={16}/> Back to Padel</Link></section></PadelShell>}
