 'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,CalendarDays,ShoppingBag,CreditCard,Award,UserRound,Bell,Info,LogOut} from 'lucide-react';
import {EcosystemShell} from './ecosystem-shell';
import {AccountAccess} from './account-access';
type User={id:string;email:string;emailVerified:boolean};
export function ProfileLanding(){const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[stamps,setStamps]=useState<number|null>(null),[available,setAvailable]=useState(0),[testRewards,setTestRewards]=useState(false);
async function refresh(){const r=await fetch('/api/auth/session',{cache:'no-store'});if(!r.ok)throw new Error('Could not load your profile. Please try again.');const {user:u}=await r.json();setUser(u??null);setStamps(null);setAvailable(0);if(u?.emailVerified){try{const rr=await fetch('/api/account/rewards',{cache:'no-store'});if(rr.ok){const d=await rr.json();if(d.verified){setStamps(d.stamps??0);setAvailable((d.rewards??[]).filter((x:{status:string})=>x.status==='available').length);setTestRewards(d.environment==='test');}}}catch{/* The reward page offers retry without hiding profile. */}}setError('');setLoading(false);}
useEffect(()=>{refresh().catch(e=>{setError(e.message);setLoading(false);});},[]);
async function logout(){setBusy(true);try{const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw new Error('Could not sign out. Please try again.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not sign out.');}finally{setBusy(false);}}
const rows=[{href:'/profile/bookings',label:'My bookings',icon:CalendarDays},{href:'/profile/orders',label:'My orders',icon:ShoppingBag},{href:'/profile/memberships',label:'My memberships',icon:CreditCard},{href:'/profile/rewards',label:'Coffee rewards',icon:Award},{href:'/profile/details',label:'My details & security',icon:UserRound},{href:'/profile/notifications',label:'Notifications',icon:Bell},{href:'/profile/help',label:'Help & contact',icon:Info}];
return <EcosystemShell service="Profile" back="/hub"><section className="profile-identity"><div className="profile-avatar" aria-hidden="true">{user?user.email.slice(0,2).toUpperCase():<UserRound size={28}/>}</div><h1>{user?'Your Midpoint profile.':'Make yourself at home.'}</h1><p>{user?user.email:'Your orders, coffee rewards and next visit. Together.'}</p>{user&&<small>{user.emailVerified?'Email verified':'Verify your email to collect rewards'}</small>}</section>{error&&<p className="hub-error" role="alert">{error}</p>}{loading?<p className="profile-status" role="status">Loading your profile…</p>:<><nav className="profile-actions" aria-label="Profile actions">{rows.map(({href,label,icon:Icon})=><Link href={href} key={href}><Icon size={20} strokeWidth={1.7}/><span>{label}{href.endsWith('/rewards')&&<small>{stamps!==null?`${testRewards?'Practice rewards · ':''}${available?`${available} reward${available===1?'':'s'} available`:`${stamps%10} of 10 coffees`}`:'Coffee card & free-coffee redemption'}{stamps!==null&&<progress aria-label="Coffee reward progress" value={stamps%10} max={10}/>}</small>}</span><ArrowRight size={16}/></Link>)}{user&&<button disabled={busy} onClick={logout}><LogOut size={20}/><span>{busy?'Signing out…':'Log out'}</span></button>}</nav>{!user&&<div className="profile-access"><AccountAccess onSignedIn={refresh}/></div>}</>}</EcosystemShell>}
export function ProfileInformation({section}:{section:'bookings'|'memberships'|'notifications'|'help'}){return <EcosystemShell service="Profile"><section className="gym-information"><p className="gym-kicker">MIDPOINT / PROFILE</p><h1>{({bookings:'Your next visit.',memberships:'Your memberships.',notifications:'Stay in the loop.',help:'A little help, close by.'})[section]}</h1>{section==='bookings'?<><p>Court and class bookings are managed by their booking services. Your confirmed bookings are not yet synced into this profile.</p><nav className="profile-actions"><a href="https://playtomic.com/clubs/midpoint-padel" target="_blank" rel="noopener noreferrer"><span>Padel on Playtomic</span><ArrowRight/></a><Link href="/gym/classes"><span>Gym classes on Itensity</span><ArrowRight/></Link><Link href="/functions/enquire"><span>Plan a function</span><ArrowRight/></Link></nav></>:section==='memberships'?<><p>Your Gym membership and tenant Padel setup are confirmed with the team. Live membership status is not yet synced here.</p><nav className="profile-actions"><Link href="/gym/membership"><span>Gym membership options</span><ArrowRight/></Link><Link href="/padel/signup"><span>Midpoint tenant Padel setup</span><ArrowRight/></Link><Link href="/profile/rewards"><span>Your coffee membership & rewards</span><ArrowRight/></Link></nav></>:section==='notifications'?<><p>Choose whether to receive earned coffee reward codes by email or SMS.</p><Link className="gym-primary" href="/profile/rewards#reward-preferences">Manage reward notifications <ArrowRight size={18}/></Link><p className="hub-helper">These preferences apply to coffee rewards. Order and account messages follow their existing settings.</p></>:<nav className="profile-actions">{[{label:'FOND · Ray',email:'ray@midpointhub.com'},{label:'Gym · Christine',email:'christine@midpointhub.com'},{label:'Padel · Ali',email:'ali@midpointhub.com'},{label:'Functions · Michelle',email:'michelle@midpointhub.com'}].map(c=><a key={c.email} href={'mailto:'+c.email}><span>{c.label}<small>{c.email}</small></span><ArrowRight size={16}/></a>)}</nav>}</section></EcosystemShell>}

