'use client';
import {useEffect,useState} from 'react';
type Credential='yoco-secret'|'yoco-webhook'|'email-api'|'staff-shared-code'|'twilio-auth-token'|'meta-access-token'|'meta-app-secret'|'meta-webhook-verify';
type Twilio = {mode:'production'|'sandbox';accountSid:string;sender:string;acceptedContentSid:string;readyContentSid:string};
type Meta = {phoneNumberId:string;wabaId:string;acceptedTemplate:string;readyTemplate:string;languageCode:string};
type Sms = {accountSid:string;sender:string};
const EMPTY_TWILIO:Twilio={mode:'production',accountSid:'',sender:'',acceptedContentSid:'',readyContentSid:''};
const EMPTY_META:Meta={phoneNumberId:'',wabaId:'',acceptedTemplate:'fond_order_accepted',readyTemplate:'fond_order_ready',languageCode:'en'};
const EMPTY_SMS:Sms={accountSid:'',sender:''};
const labels:Record<Credential,string>={'yoco-secret':'Yoco secret key','yoco-webhook':'Yoco webhook signing secret','email-api':'Resend API key','staff-shared-code':'Shared staff tablet code','twilio-auth-token':'Twilio auth token','meta-access-token':'Meta permanent access token','meta-app-secret':'Meta app secret','meta-webhook-verify':'Meta webhook verify token'};
export function ProviderSettings(){
 const [status,setStatus]=useState<{configured:Record<Credential,boolean>;yocoMode:'test'|'live'|'none';webhookUrl:string;whatsappWebhookUrl:string;smsWebhookUrl:string;vaultReady:boolean;emailFrom:string;twilio:Twilio;sms:Sms;meta:Meta}|null>(null),[fields,setFields]=useState<Record<Credential,string>>({'yoco-secret':'','yoco-webhook':'','email-api':'','staff-shared-code':'','twilio-auth-token':'','meta-access-token':'','meta-app-secret':'','meta-webhook-verify':''}),[busy,setBusy]=useState<Credential|'register-yoco'|'test-whatsapp'|'test-sms'|null>(null),[message,setMessage]=useState(''),[emailFrom,setEmailFrom]=useState(''),[twilio,setTwilio]=useState<Twilio>(EMPTY_TWILIO),[sms,setSms]=useState<Sms>(EMPTY_SMS),[meta,setMeta]=useState<Meta>(EMPTY_META),[testLink,setTestLink]=useState<{url:string;reference:string;amount:number}|null>(null),[whatsappTestNumber,setWhatsappTestNumber]=useState(''),[whatsappTestTemplate,setWhatsappTestTemplate]=useState<'order_accepted'|'order_ready'>('order_accepted'),[smsTestNumber,setSmsTestNumber]=useState(''),[smsTestTemplate,setSmsTestTemplate]=useState<'order_accepted'|'order_ready'>('order_accepted');
 async function refresh(){const r=await fetch('/api/admin/provider-credentials',{cache:'no-store'});if(r.ok){const data=await r.json();setStatus(data);setEmailFrom(data.emailFrom??'');setTwilio(data.twilio??EMPTY_TWILIO);setSms(data.sms??EMPTY_SMS);setMeta(data.meta??EMPTY_META);}}
 useEffect(()=>{void refresh();},[]);
 async function save(name:Credential){setBusy(name);setMessage('');try{const r=await fetch('/api/admin/provider-credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,value:fields[name]})});const d=await r.json();if(!r.ok)throw new Error(d.message);setFields(current=>({...current,[name]:''}));setMessage(labels[name]+' saved.');await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(null);}}
 async function saveSender(){setMessage('');const r=await fetch('/api/admin/provider-credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'email-from',value:emailFrom})});const d=await r.json();setMessage(r.ok?'FOND email sender saved.':d.message??'Could not save sender.');if(r.ok)await refresh();}
 async function saveTwilio(){setMessage('');const r=await fetch('/api/admin/provider-credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'twilio-config',value:twilio})});const d=await r.json();setMessage(r.ok?'Twilio configuration saved.':d.message??'Could not save Twilio configuration.');if(r.ok)await refresh();}
 async function saveSms(){setMessage('');const r=await fetch('/api/admin/provider-credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'twilio-sms-config',value:sms})});const d=await r.json();setMessage(r.ok?'Twilio SMS configuration saved.':d.message??'Could not save SMS configuration.');if(r.ok)await refresh();}
 async function saveMeta(){setMessage('');const r=await fetch('/api/admin/provider-credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'meta-whatsapp-config',value:meta})});const d=await r.json();setMessage(r.ok?'Meta WhatsApp configuration saved.':d.message??'Could not save Meta configuration.');if(r.ok)await refresh();}
 async function createYocoTest(){setMessage('Creating sandbox checkout…');setTestLink(null);const r=await fetch('/api/admin/yoco/test-checkout',{method:'POST'});const d=await r.json();if(!r.ok){setMessage(d.message??'Could not create test checkout.');return;}setMessage('Sandbox checkout created. Complete it with Yoco test card details, then check Finance reconciliation.');setTestLink({url:d.redirectUrl,reference:d.reference,amount:d.amountCents});}
 async function registerWebhook(){setBusy('register-yoco');setMessage('Registering the secure webhook with Yoco…');try{const r=await fetch('/api/admin/yoco/register-webhook',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.message);setMessage(`Yoco ${d.mode} webhook registered and its signing secret saved securely.`);await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(null);}}
 async function sendWhatsAppTest(){setBusy('test-whatsapp');setMessage('Sending WhatsApp test…');try{const r=await fetch('/api/admin/twilio/test-message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to:whatsappTestNumber,template:whatsappTestTemplate})});const d=await r.json();if(!r.ok)throw new Error(d.message);setMessage(d.message);}catch(e){setMessage((e as Error).message);}finally{setBusy(null);}}
 async function sendSmsTest(){setBusy('test-sms');setMessage('Sending SMS test…');try{const r=await fetch('/api/admin/twilio/test-sms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to:smsTestNumber,template:smsTestTemplate})});const d=await r.json();if(!r.ok)throw new Error(d.message);setMessage(d.message);}catch(e){setMessage((e as Error).message);}finally{setBusy(null);}}
 return <section className="manage-card"><h2>Provider credentials · super admin</h2><p>Paste credentials here over HTTPS. Saved values are encrypted in the FOND database and never displayed again. The server needs a one-time encryption key before this vault can be used.</p>{status&&!status.vaultReady&&<p className="manage-error" role="alert">Credential vault is not initialized on this server.</p>}
 {(['yoco-secret','yoco-webhook','email-api','staff-shared-code'] as Credential[]).map(name=><div className="provider-entry" key={name}><label className="field">{labels[name]} · {status?.configured[name]?'Stored':'Not stored'}<input type="password" autoComplete="off" value={fields[name]} onChange={e=>setFields({...fields,[name]:e.target.value})} placeholder={name==='yoco-secret'?'sk_test_… or sk_live_…':name==='yoco-webhook'?'whsec_…':name==='email-api'?'re_…':'6–64 letters, digits or . _ -'}/></label><button className="outline" disabled={!status?.vaultReady||!fields[name]||!!busy} onClick={()=>void save(name)}>Save {labels[name]}</button></div>)}
 <div className="provider-test"><h3>Yoco sandbox test</h3><p>Credential mode: <strong>{status?.yocoMode??'none'}</strong></p><p>Secure payment notification URL: <code>{status?.webhookUrl||'Public URL not configured'}</code></p><ol><li>Save the test secret key above.</li><li>Register the webhook below. FOND sends the key to Yoco from the server and stores the returned signing secret in the encrypted vault.</li><li>Enable sandbox webhook processing in Trading &amp; fulfilment, then save. Keep public online checkout off during testing.</li><li>Create and complete a fresh sandbox checkout, then confirm signed payment reconciliation in Finance.</li></ol><p><button className="outline" disabled={status?.yocoMode==='none'||status?.configured['yoco-webhook']||!!busy} onClick={()=>void registerWebhook()}>{status?.configured['yoco-webhook']?'Yoco webhook registered':'Register Yoco webhook securely'}</button></p><button className="primary" disabled={status?.yocoMode!=='test'||!status?.configured['yoco-webhook']||!!busy} onClick={()=>void createYocoTest()}>Create Yoco sandbox checkout</button>{testLink&&<p><a className="outline" href={testLink.url} target="_blank" rel="noreferrer">Open sandbox payment for {testLink.reference} · R {(testLink.amount/100).toFixed(2)}</a></p>}</div>
 <div className="provider-entry"><label className="field">Verified FOND sending address<input type="email" value={emailFrom} onChange={e=>setEmailFrom(e.target.value)} placeholder="orders@fond.mid-point.co.za"/></label><button className="outline" disabled={!emailFrom||emailFrom===status?.emailFrom} onClick={()=>void saveSender()}>Save email sender</button></div>
 <h3>Twilio SMS</h3><p>Transactional order updates from the FOND number. Delivery callback: <code>{status?.smsWebhookUrl||'Public URL not configured'}</code></p><p className="small">SMS uses the same encrypted Twilio auth token saved in the Twilio section below.</p><label className="field">Twilio Account SID<input value={sms.accountSid} onChange={e=>setSms({...sms,accountSid:e.target.value})} placeholder="AC…"/></label><label className="field">SMS sender (+E.164)<input value={sms.sender} onChange={e=>setSms({...sms,sender:e.target.value})} placeholder="+27600928520"/></label><button className="outline" onClick={()=>void saveSms()}>Save SMS configuration</button>
 <div className="provider-test"><h3>Send a controlled SMS test</h3><p>This sends one FOND order-status SMS without creating an order. Twilio acceptance is shown immediately; handset delivery is confirmed in the Twilio message log.</p><label className="field">Test recipient mobile number<input inputMode="tel" autoComplete="tel" value={smsTestNumber} onChange={e=>setSmsTestNumber(e.target.value)} placeholder="+27 82 123 4567"/></label><label className="field">Test message<select value={smsTestTemplate} onChange={e=>setSmsTestTemplate(e.target.value as 'order_accepted'|'order_ready')}><option value="order_accepted">Order accepted</option><option value="order_ready">Order ready</option></select></label><button className="primary" disabled={!status?.configured['twilio-auth-token']||!sms.accountSid||!sms.sender||!smsTestNumber||!!busy} onClick={()=>void sendSmsTest()}>Send SMS test from FOND</button></div>
 <h3>Meta WhatsApp Cloud API</h3><p>Direct FOND connection. Callback URL: <code>{status?.whatsappWebhookUrl||'Public URL not configured'}</code></p>
 {(['meta-access-token','meta-app-secret','meta-webhook-verify'] as Credential[]).map(name=><div className="provider-entry" key={name}><label className="field">{labels[name]} · {status?.configured[name]?'Stored':'Not stored'}<input type="password" autoComplete="off" value={fields[name]} onChange={e=>setFields({...fields,[name]:e.target.value})}/></label><button className="outline" disabled={!status?.vaultReady||!fields[name]||!!busy} onClick={()=>void save(name)}>Save {labels[name]}</button></div>)}
 {(['phoneNumberId','wabaId','acceptedTemplate','readyTemplate','languageCode'] as (keyof Meta)[]).map(key=><label className="field" key={key}>{key==='phoneNumberId'?'Phone number ID':key==='wabaId'?'WhatsApp Business Account ID':key==='acceptedTemplate'?'Accepted-order template name':key==='readyTemplate'?'Ready-order template name':'Template language'}<input value={meta[key]} onChange={e=>setMeta({...meta,[key]:e.target.value})}/></label>)}<button className="outline" onClick={()=>void saveMeta()}>Save Meta configuration</button>
 <h3>Twilio WhatsApp</h3><label className="field">Connection mode<select value={twilio.mode} onChange={e=>setTwilio({...twilio,mode:e.target.value as Twilio['mode']})}><option value="sandbox">FOND staging test · Twilio Sandbox</option><option value="production">Live registered WhatsApp sender</option></select></label>{twilio.mode==='sandbox'?<p className="provider-note"><strong>Testing only.</strong> FOND will send real order accepted and ready messages through Twilio Sandbox. Each test phone must first join the sandbox in Twilio. This mode is blocked outside fond-test.mid-point.co.za.</p>:<p>Use the registered FOND WhatsApp number and approved accepted/ready templates. Each template must have customer name and order reference as its two variables.</p>}
 <div className="provider-entry"><label className="field">Twilio auth token · {status?.configured['twilio-auth-token']?'Stored':'Not stored'}<input type="password" autoComplete="off" value={fields['twilio-auth-token']} onChange={e=>setFields({...fields,'twilio-auth-token':e.target.value})}/></label><button className="outline" disabled={!status?.vaultReady||!fields['twilio-auth-token']||!!busy} onClick={()=>void save('twilio-auth-token')}>Save Twilio auth token</button></div>
 <label className="field">Twilio Account SID<input value={twilio.accountSid} onChange={e=>setTwilio({...twilio,accountSid:e.target.value})}/></label>{twilio.mode==='sandbox'?<label className="field">Sandbox WhatsApp sender<input value="+1 415 523 8886" disabled/></label>:<>{(['sender','acceptedContentSid','readyContentSid'] as (keyof Twilio)[]).map(key=><label className="field" key={key}>{key==='sender'?'Registered WhatsApp sender (+E.164)':key==='acceptedContentSid'?'Approved accepted template Content SID':'Approved ready template Content SID'}<input value={twilio[key]} onChange={e=>setTwilio({...twilio,[key]:e.target.value})}/></label>)}</>}<button className="outline" onClick={()=>void saveTwilio()}>Save Twilio configuration</button>
 <div className="provider-test"><h3>Send a controlled WhatsApp test</h3><p>This sends one approved FOND order-status template without creating an order. Meta Cloud API is used when configured; Twilio remains a fallback.</p><label className="field">Test recipient mobile number<input inputMode="tel" autoComplete="tel" value={whatsappTestNumber} onChange={e=>setWhatsappTestNumber(e.target.value)} placeholder="+27 82 123 4567"/></label><label className="field">Test message<select value={whatsappTestTemplate} onChange={e=>setWhatsappTestTemplate(e.target.value as 'order_accepted'|'order_ready')}><option value="order_accepted">Order accepted</option><option value="order_ready">Order ready</option></select></label><button className="primary" disabled={(!status?.configured['meta-access-token']||!meta.phoneNumberId)||!whatsappTestNumber||!!busy} onClick={()=>void sendWhatsAppTest()}>Send WhatsApp test from FOND</button></div>
 {message&&<p role="status">{message}</p>}<p className="small">The Yoco public key is not needed by FOND’s server-side checkout. Keep online checkout disabled until a signed test payment has been reconciled. Email also needs a verified sending domain and address.</p></section>;
}
