'use client';
import {useEffect,useState} from 'react';
type Credential='yoco-secret'|'yoco-webhook'|'email-api'|'staff-shared-code'|'twilio-auth-token';
type Twilio = {accountSid:string;sender:string;acceptedContentSid:string;readyContentSid:string};
const EMPTY_TWILIO:Twilio={accountSid:'',sender:'',acceptedContentSid:'',readyContentSid:''};
const labels:Record<Credential,string>={'yoco-secret':'Yoco secret key','yoco-webhook':'Yoco webhook signing secret','email-api':'Resend API key','staff-shared-code':'Shared staff tablet code','twilio-auth-token':'Twilio auth token'};
export function ProviderSettings(){
 const [status,setStatus]=useState<{configured:Record<Credential,boolean>;yocoMode:'test'|'live'|'none';webhookUrl:string;vaultReady:boolean;emailFrom:string;twilio:Twilio}|null>(null),[fields,setFields]=useState<Record<Credential,string>>({'yoco-secret':'','yoco-webhook':'','email-api':'','staff-shared-code':'','twilio-auth-token':''}),[busy,setBusy]=useState<Credential|null>(null),[message,setMessage]=useState(''),[emailFrom,setEmailFrom]=useState(''),[twilio,setTwilio]=useState<Twilio>(EMPTY_TWILIO),[testLink,setTestLink]=useState<{url:string;reference:string;amount:number}|null>(null);
 async function refresh(){const r=await fetch('/api/admin/provider-credentials',{cache:'no-store'});if(r.ok){const data=await r.json();setStatus(data);setEmailFrom(data.emailFrom??'');setTwilio(data.twilio??EMPTY_TWILIO);}}
 useEffect(()=>{void refresh();},[]);
 async function save(name:Credential){setBusy(name);setMessage('');try{const r=await fetch('/api/admin/provider-credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,value:fields[name]})});const d=await r.json();if(!r.ok)throw new Error(d.message);setFields(current=>({...current,[name]:''}));setMessage(labels[name]+' saved.');await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(null);}}
 async function saveSender(){setMessage('');const r=await fetch('/api/admin/provider-credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'email-from',value:emailFrom})});const d=await r.json();setMessage(r.ok?'FOND email sender saved.':d.message??'Could not save sender.');if(r.ok)await refresh();}
 async function saveTwilio(){setMessage('');const r=await fetch('/api/admin/provider-credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'twilio-config',value:twilio})});const d=await r.json();setMessage(r.ok?'Twilio configuration saved.':d.message??'Could not save Twilio configuration.');if(r.ok)await refresh();}
 async function createYocoTest(){setMessage('Creating sandbox checkout…');setTestLink(null);const r=await fetch('/api/admin/yoco/test-checkout',{method:'POST'});const d=await r.json();if(!r.ok){setMessage(d.message??'Could not create test checkout.');return;}setMessage('Sandbox checkout created. Complete it with Yoco test card details, then check Finance reconciliation.');setTestLink({url:d.redirectUrl,reference:d.reference,amount:d.amountCents});}
 return <section className="manage-card"><h2>Provider credentials · super admin</h2><p>Paste credentials here over HTTPS. Saved values are encrypted in the FOND database and never displayed again. The server needs a one-time encryption key before this vault can be used.</p>{status&&!status.vaultReady&&<p className="manage-error" role="alert">Credential vault is not initialized on this server.</p>}
 {(['yoco-secret','yoco-webhook','email-api','staff-shared-code','twilio-auth-token'] as Credential[]).map(name=><div className="provider-entry" key={name}><label className="field">{labels[name]} · {status?.configured[name]?'Stored':'Not stored'}<input type="password" autoComplete="off" value={fields[name]} onChange={e=>setFields({...fields,[name]:e.target.value})} placeholder={name==='yoco-secret'?'sk_test_… or sk_live_…':name==='yoco-webhook'?'whsec_…':name==='email-api'?'re_…':name==='staff-shared-code'?'6–64 letters, digits or . _ -':'32 hexadecimal characters'}/></label><button className="outline" disabled={!status?.vaultReady||!fields[name]||!!busy} onClick={()=>void save(name)}>Save {labels[name]}</button></div>)}
 <div className="provider-test"><h3>Yoco sandbox test</h3><p>Credential mode: <strong>{status?.yocoMode??'none'}</strong></p><p>Register this exact webhook URL in Yoco: <code>{status?.webhookUrl||'Public URL not configured'}</code></p><ol><li>Save the test secret key above.</li><li>Enable sandbox webhook processing in Trading &amp; fulfilment, then save. Keep public online checkout off during testing.</li><li>Create and complete a sandbox checkout to verify the test key.</li><li>Create the Yoco webhook subscription, save its one-time <code>whsec_…</code> secret, then confirm signed payment reconciliation in Finance.</li></ol><button className="primary" disabled={status?.yocoMode!=='test'} onClick={()=>void createYocoTest()}>Create Yoco sandbox checkout</button>{testLink&&<p><a className="outline" href={testLink.url} target="_blank" rel="noreferrer">Open sandbox payment for {testLink.reference} · R {(testLink.amount/100).toFixed(2)}</a></p>}</div>
 <div className="provider-entry"><label className="field">Verified FOND sending address<input type="email" value={emailFrom} onChange={e=>setEmailFrom(e.target.value)} placeholder="orders@fond.co.za"/></label><button className="outline" disabled={!emailFrom||emailFrom===status?.emailFrom} onClick={()=>void saveSender()}>Save email sender</button></div>
 <h3>Twilio WhatsApp sender</h3><p>Enter the Twilio number only after it is registered as a WhatsApp sender. The accepted and ready Content SIDs must refer to approved WhatsApp templates with two variables: customer name and order reference.</p>
 {(['accountSid','sender','acceptedContentSid','readyContentSid'] as (keyof Twilio)[]).map(key=><label className="field" key={key}>{key==='accountSid'?'Twilio Account SID':key==='sender'?'Registered WhatsApp sender (+E.164)':key==='acceptedContentSid'?'Approved accepted template Content SID':'Approved ready template Content SID'}<input value={twilio[key]} onChange={e=>setTwilio({...twilio,[key]:e.target.value})}/></label>)}<button className="outline" onClick={()=>void saveTwilio()}>Save Twilio configuration</button>
 {message&&<p role="status">{message}</p>}<p className="small">The Yoco public key is not needed by FOND’s server-side checkout. Keep online checkout disabled until a signed test payment has been reconciled. Email also needs a verified sending domain and address.</p></section>;
}
