'use client';
import { useEffect,useState } from 'react';
import { ArrowDownRight,ArrowUpRight,BarChart3,CalendarDays,Download,RefreshCw,ShoppingBag,TrendingUp,UtensilsCrossed } from 'lucide-react';
import { money } from '@/lib/menu';
import type { Analytics } from '@/lib/analytics';
const colours=['#097e75','#42b4a8','#8099d7','#d6a453','#9e83bc','#7c9290'];
const today=()=>new Date(Date.now()+7200000).toISOString().slice(0,10);
const back=(date:string,days:number)=>new Date(Date.parse(date+'T00:00:00Z')-days*86400000).toISOString().slice(0,10);
const shortDate=(s:string)=>new Date(s+'T00:00:00Z').toLocaleDateString('en-ZA',{day:'numeric',month:'short',timeZone:'UTC'});
const compact=(c:number)=>'R '+Intl.NumberFormat('en-ZA',{notation:'compact',maximumFractionDigits:1}).format(c/100);
function Delta({value,prior}:{value:number;prior:number}){if(!prior)return <small className="bi-neutral">{value?'No prior-period baseline':'No comparison data'}</small>;const delta=(value-prior)/prior*100;return <small className={delta>=0?'bi-up':'bi-down'}>{delta>=0?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>} {Math.abs(delta).toFixed(1)}% <span>vs previous period</span></small>;}
function Empty({text='Completed orders will appear here.'}:{text?:string}){return <div className="bi-empty"><BarChart3 size={28}/><strong>No data for this period</strong><p>{text}</p></div>;}
function Trend({data}:{data:Analytics}){
 const [hover,setHover]=useState<number|null>(null),max=Math.max(100,...data.daily.flatMap(d=>[d.value,d.previousValue]));
 const point=(i:number,value:number)=>`${56+i/Math.max(1,data.daily.length-1)*650},${210-value/max*175}`;
 const path=(key:'value'|'previousValue')=>data.daily.map((d,i)=>(i?'L':'M')+point(i,d[key])).join(' ');
 return <><div className="bi-legend"><span><i style={{background:colours[0]}}/>Selected period</span><span><i style={{background:'#b6c8c5'}}/>Previous period</span></div>
 {data.summary.orders||data.previous.orders?<><svg className="bi-trend" viewBox="0 0 740 255" role="img" aria-label="Completed order value by order date, compared with preceding equal period">
 <defs><linearGradient id="fondTrendFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0a9c8b" stopOpacity=".22"/><stop offset="100%" stopColor="#0a9c8b" stopOpacity=".01"/></linearGradient></defs>
 {[0,.25,.5,.75,1].map(n=><g key={n}><line x1="56" x2="706" y1={210-n*175} y2={210-n*175} stroke="#e9efef"/><text x="46" y={214-n*175} textAnchor="end">{compact(max*n)}</text></g>)}
 <path d={path('value')+' L706,210 L56,210 Z'} fill="url(#fondTrendFill)"/><path d={path('previousValue')} fill="none" stroke="#b6c8c5" strokeWidth="2" strokeDasharray="5 5"/><path d={path('value')} fill="none" stroke={colours[0]} strokeWidth="3"/>
 {data.daily.map((d,i)=><g key={d.date}><circle cx={56+i/Math.max(1,data.daily.length-1)*650} cy={210-d.value/max*175} r={hover===i?5:3} fill={colours[0]}/><rect x={45+i/Math.max(1,data.daily.length-1)*650} y="20" width={Math.max(14,650/data.daily.length)} height="200" fill="transparent" onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)}><title>{d.date}: {money(d.value)} · {d.orders} orders</title></rect>{(i===0||i===data.daily.length-1||i===Math.floor(data.daily.length/2))&&<text x={56+i/Math.max(1,data.daily.length-1)*650} y="244" textAnchor="middle">{shortDate(d.date)}</text>}</g>)}
 </svg><p className="bi-chart-note">{hover!==null?`${shortDate(data.daily[hover].date)} · ${money(data.daily[hover].value)} · ${data.daily[hover].orders} completed orders`:'Hover over the chart for daily values. Previous period is aligned by day.'}</p></>:<Empty text="Your first completed order will start this trend. No sample sales are shown."/>}</>;
}
export function ReportsDashboard(){
 const [from,setFrom]=useState(back(today(),29)),[to,setTo]=useState(today()),[fulfillment,setFulfillment]=useState('all'),[preset,setPreset]=useState('30'),[data,setData]=useState<Analytics|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[category,setCategory]=useState(''),[search,setSearch]=useState(''),[rank,setRank]=useState('top');
 const query=new URLSearchParams({from,to,fulfillment}).toString();
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');setData(null);fetch('/api/admin/reports/overview?'+query,{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message);setData(d);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return ()=>c.abort();},[query,refresh]);
 const products=(data?.products??[]).filter(p=>(!category||p.category===category)&&p.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>rank==='top'?b.units-a.units:a.units-b.units);
 const totalMix=data?.mix.reduce((n,m)=>n+m.orders,0)??0,collection=data?.mix[0].orders??0;
 return <div className="bi-dashboard" aria-busy={loading}>
 <div className="bi-heading"><div><p className="bi-kicker">FOND INTELLIGENCE</p><h2>Business overview</h2><p>A clear view of what sells, when it sells and how orders move.</p></div><div className="bi-heading-actions"><span className="bi-source"><i/>FOND order data</span><button className="bi-button" onClick={()=>setRefresh(n=>n+1)} disabled={loading} aria-label="Refresh analytics"><RefreshCw size={16}/></button><a className="bi-button" href={'/api/admin/reports/overview?'+query+'&export=items'}><Download size={15}/> Export items</a></div></div>
 <div className="bi-filters"><CalendarDays size={19}/><div className="bi-presets">{[['7','7 days'],['30','30 days'],['90','90 days']].map(([n,label])=><button key={n} className={preset===n?'active':''} onClick={()=>{setPreset(n);setTo(today());setFrom(back(today(),Number(n)-1));}}>{label}</button>)}</div><label>From<input aria-label="Report from" type="date" value={from} onChange={e=>{setPreset('custom');setFrom(e.target.value);}}/></label><label>To<input aria-label="Report to" type="date" value={to} onChange={e=>{setPreset('custom');setTo(e.target.value);}}/></label><label>Fulfilment<select aria-label="Report fulfilment" value={fulfillment} onChange={e=>setFulfillment(e.target.value)}><option value="all">All orders</option><option value="collection">Collection</option><option value="delivery">Delivery</option></select></label></div>
 {error?<p className="manage-error" role="alert">{error}</p>:loading?<div className="bi-loading" role="status">Loading your business performance…</div>:data&&<>
 <div className="bi-period"><span>{shortDate(from)} – {shortDate(to)} · South Africa time</span><span>Compared with {shortDate(data.previousFrom)} – {shortDate(data.previousTo)}</span></div>
 <div className="bi-kpis">{[{name:'Completed order value',key:'value' as const,icon:TrendingUp,currency:true},{name:'Completed orders',key:'orders' as const,icon:ShoppingBag},{name:'Average order value',key:'average' as const,icon:BarChart3,currency:true},{name:'Items sold',key:'units' as const,icon:UtensilsCrossed}].map(({name,key,icon:Icon,currency})=><article className="bi-kpi" key={key}><div><span>{name}</span><Icon size={18}/></div><strong>{currency?money(data.summary[key]):data.summary[key].toLocaleString('en-ZA')}</strong><Delta value={data.summary[key]} prior={data.previous[key]}/></article>)}</div>
 {!data.summary.orders&&<div className="bi-notice"><BarChart3 size={20}/><div><strong>Your reporting dashboard is ready.</strong><span>No completed orders in this period. Charts will populate from real FOND orders; unsold menu items are not labelled slow movers.</span></div></div>}
 <div className="bi-main-grid"><section className="bi-card"><div className="bi-card-head"><div><h3>Sales performance</h3><p>Completed order value · by order date</p></div><span className="bi-pill">ZAR</span></div><Trend data={data}/></section>
 <section className="bi-card"><div className="bi-card-head"><div><h3>Order mix</h3><p>Completed orders by fulfilment</p></div></div>{totalMix?<><div className="bi-donut" style={{background:`conic-gradient(${colours[0]} 0 ${collection/totalMix*100}%, ${colours[2]} ${collection/totalMix*100}% 100%)`}}><div><strong>{totalMix}</strong><span>completed</span></div></div><div className="bi-mix">{data.mix.map((m,i)=><div key={m.name}><span><i style={{background:i?colours[2]:colours[0]}}/>{m.name}</span><strong>{m.orders} <small>{Math.round(m.orders/totalMix*100)}%</small></strong></div>)}</div></>:<Empty/>}</section></div>
 <div className="bi-three-grid"><section className="bi-card"><div className="bi-card-head"><div><h3>Category performance</h3><p>Units sold · click to filter item detail</p></div></div>{data.categories.length?<div className="bi-bars">{data.categories.map((c,i)=><button key={c.name} className={category===c.name?'selected':''} onClick={()=>setCategory(category===c.name?'':c.name)} aria-pressed={category===c.name}><span>{c.name}<strong>{c.units}</strong></span><div><i style={{width:`${c.units/Math.max(1,data.summary.units)*100}%`,background:colours[i%colours.length]}}/></div></button>)}</div>:<Empty/>}</section>
 <section className="bi-card"><div className="bi-card-head"><div><h3>Order status</h3><p>All orders placed in this period</p></div><span className="bi-pill">{data.status.reduce((n,s)=>n+s.orders,0)} total</span></div><div className="bi-status">{data.status.map((s,i)=><div key={s.name}><span><i style={{background:colours[i]}}/>{s.name}</span><div><i style={{width:`${s.orders/Math.max(1,...data.status.map(x=>x.orders))*100}%`,background:colours[i]}}/></div><strong>{s.orders}</strong></div>)}</div><p className="bi-chart-note">Current status of each order, including cancellations.</p></section>
 <section className="bi-card"><div className="bi-card-head"><div><h3>When customers order</h3><p>Completed orders · Johannesburg hour</p></div></div>{data.summary.orders?<><div className="bi-hours">{data.hours.map(h=><div key={h.hour} title={`${String(h.hour).padStart(2,'0')}:00 · ${h.orders} orders`}><i style={{height:`${h.orders/Math.max(1,...data.hours.map(x=>x.orders))*100}%`}}/></div>)}</div><div className="bi-hour-labels"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:00</span></div><p className="bi-chart-note">Based on placement time, not collection time.</p></>:<Empty/>}</section></div>
 <section className="bi-card"><div className="bi-card-head"><div><h3>Item performance</h3><p>Ranked by units in completed orders · {data.products.length} items ordered</p></div><span className="bi-pill">{data.noSalesCount} available items with no sales in period</span></div><div className="bi-table-filters"><input aria-label="Search report items" placeholder="Search item name…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Item category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{data.categories.map(c=><option key={c.name}>{c.name}</option>)}</select><select aria-label="Item ranking" value={rank} onChange={e=>setRank(e.target.value)}><option value="top">Highest units first</option><option value="low">Lowest units first · sold items only</option></select>{category&&<button className="bi-button" onClick={()=>setCategory('')}>Clear category</button>}</div>
 {products.length?<div className="bi-table"><table><thead><tr><th>Rank</th><th>Item</th><th>Category</th><th>Units</th><th>Share of all units</th><th>Recorded item value</th></tr></thead><tbody>{products.map((p,i)=><tr key={p.id}><td><span className="bi-rank">{String(i+1).padStart(2,'0')}</span></td><td><strong>{p.name}</strong></td><td>{p.category}</td><td><strong>{p.units}</strong></td><td><div className="bi-share"><i style={{width:`${p.units/Math.max(1,data.summary.units)*100}%`}}/></div>{(p.units/Math.max(1,data.summary.units)*100).toFixed(1)}%</td><td>{p.unpricedUnits?'Incomplete snapshot':money(p.value)}</td></tr>)}</tbody></table></div>:<Empty text={data.products.length?'No items match these filters.':'Item rankings start with the first completed order. No automatic discount recommendations are made.'}/>}</section>
 <footer className="bi-footnote"><span>Source: FOND app orders only. Completed value is not proof of payment; use Finance for receipts. Categories reflect the current menu. {data.unpricedUnits>0?`${data.unpricedUnits} legacy units have no stored item value; current prices are never substituted.`:'Item values use stored purchase prices.'}</span><span>Updated {new Date(data.generatedAt).toLocaleTimeString('en-ZA',{timeZone:'Africa/Johannesburg',hour:'2-digit',minute:'2-digit'})} SAST</span></footer>
 </>}
 </div>;
}
