 'use client';
import {useEffect,useState} from 'react';
import {AdminPanel} from './admin-panel';
import './team-portal.css';
type Identity={name:string;role:string;areas:Record<string,boolean>};
export function TeamPortal(){const [user,setUser]=useState<Identity|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fond,setFond]=useState(false);
 async function load(){try{const r=await fetch('/api/team/session',{cache:'no-store'});if(!r.ok&&r.status!==401)throw new Error();setUser(r.ok?await r.json():null);}catch{setError('Unable to load your workspace. Please check your connection and try again.');}finally{setLoading(false);}}useEffect(()=>{void load();},[]);
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/team/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});const b=await r.json();if(!r.ok)throw new Error(b.message);const next=new URLSearchParams(location.search).get('next');if(next==='/hub/manage'&&(b.areas.gym||b.areas.padel)||next==='/hub/functions'&&b.areas.functions){location.assign(next!);return;}await load();}catch(e){setError(e instanceof Error?e.message:'Unable to sign in.');}finally{setBusy(false);}}
 async function logout(){try{const r=await fetch('/api/team/session',{method:'DELETE'});if(!r.ok)throw new Error();setUser(null);setFond(false);setError('');}catch{setError('Unable to sign out. Please try again.');}}
 if(loading)return <p role="status">Loading team workspace…</p>;
 return <div className="team-portal"><header className="team-portal-head"><a href="/hub"><img src="/hub-assets/hub-logo-stacked.svg" alt="Midpoint Hub" width="90" height="72"/></a><span>TEAM WORKSPACE</span>{user&&<button onClick={logout}>Sign out</button>}</header>{error&&<p role="alert">{error}</p>}{!user?<form className="team-login" onSubmit={login}><h1>Welcome to your Hub.</h1><p>One sign-in for your team. Your role opens the areas you manage.</p><label>Team username<input name="username" autoComplete="username" required maxLength={100}/></label><label>Password<input name="password" type="password" autoComplete="current-password" required maxLength={128}/></label><label>Authenticator or recovery code<input name="twoFactorCode" autoComplete="one-time-code"/><small>If enabled on your account.</small></label><button disabled={busy}>{busy?'Signing in…':'Sign in'}</button><a href="/hub">Back to Midpoint Hub</a></form>:fond&&user.areas.fond?<><button className="team-back" onClick={()=>setFond(false)}>All workspaces</button><AdminPanel onLogout={logout}/></>:<main className="team-home"><p>WELCOME BACK, {user.name}</p><h1>Your team workspace.</h1><p>Choose an area to manage.</p><div className="team-areas">{user.areas.fond&&<button onClick={()=>setFond(true)}><strong>FOND</strong><span>Menu, orders, customers, reports and team settings</span></button>}{user.areas.gym&&<a href="/hub/manage"><strong>Gym</strong><span>Membership requests, classes and events</span></a>}{user.areas.padel&&<a href="/hub/manage?service=padel"><strong>Padel</strong><span>Membership requests, events and court booking link</span></a>}{user.areas.functions&&<a href="/hub/functions"><strong>Functions</strong><span>Enquiries, booking dates and calendar</span></a>}{user.areas.staff&&<a href="/staff"><strong>FOND order queue</strong><span>Prepare, dispatch and complete orders</span></a>}</div></main>}</div>;
}

