import {ArrowRight,CalendarDays,Coffee,Dumbbell,LayoutGrid,Settings2,ShoppingBag,Volleyball} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
type Identity={name:string;role:string;areas:Record<string,boolean>};
type Area={title:string;description:string;icon:LucideIcon;image?:string;href?:string;workspace?:'fond'|'operations';};
export function TeamWorkspaceHome({user,onOpen}:{user:Identity;onOpen:(workspace:'fond'|'operations')=>void}){
 const areas:Area[]=[...(user.areas.fond?[{title:'Operations',description:'Team access, security and shared administration.',icon:Settings2,workspace:'operations' as const},{title:'FOND',description:'Menu, orders and the everyday running of FOND.',icon:Coffee,image:'/hub-assets/tile-fond-3.webp',workspace:'fond' as const}]:[]),...(user.areas.gym?[{title:'Gym',description:'Membership requests, training times and classes.',icon:Dumbbell,image:'/hub-assets/tile-gym-3.webp',href:'/hub/manage'}]:[]),...(user.areas.padel?[{title:'Padel',description:'Court booking links, events and membership requests.',icon:Volleyball,image:'/hub-assets/tile-padel-2.webp',href:'/hub/manage?service=padel'}]:[]),...(user.areas.functions?[{title:'Functions',description:'Guest enquiries, booking dates and the calendar.',icon:CalendarDays,image:'/hub-assets/midpoint-amenities.jpg',href:'/hub/functions'}]:[])];
 const role=({'super-admin':'Super admin',owner:'Owner',manager:'Manager',staff:'Staff',gym:'Gym team',padel:'Padel team',functions:'Functions team'} as Record<string,string>)[user.role]??'Team member';
 const initials=user.name.split(/\s+/).filter(Boolean).slice(0,2).map(n=>n[0]).join('');
 function content(area:Area){const Icon=area.icon;return <><div className="team-area-art">{area.image?<img src={area.image} alt="" width="600" height="320"/>:<><span className="team-operation-pattern"/><Settings2 size={42} strokeWidth={1.3}/><span className="team-art-caption">MIDPOINT / OPERATIONS</span></>}<span className="team-area-icon"><Icon size={20}/></span></div><div className="team-area-copy"><strong>{area.title}</strong><span>{area.description}</span><div className="team-area-open">Open workspace <ArrowRight size={18}/></div></div></>}
 return <main className="team-home"><aside className="team-home-rail"><div className="team-overview-label"><LayoutGrid size={18}/> Workspace overview</div><nav aria-label="Team workspaces">{areas.map(a=>{const Icon=a.icon;return a.href?<a key={a.title} href={a.href}><Icon size={18}/>{a.title}<ArrowRight size={14}/></a>:<button key={a.title} onClick={()=>onOpen(a.workspace!)}><Icon size={18}/>{a.title}<ArrowRight size={14}/></button>})}{user.areas.staff&&<a href="/staff"><ShoppingBag size={18}/>Order queue<ArrowRight size={14}/></a>}</nav><div className="team-identity"><span className="team-avatar">{initials}</span><div><strong>{user.name}</strong><span>{role}</span></div></div><a className="team-public-link" href="/hub">View Midpoint app <ArrowRight size={15}/></a></aside><div className="team-overview"><section className="team-overview-intro"><div><p className="team-kicker">MIDPOINT / TEAM</p><h1>Your team workspace.</h1><p>Welcome back, {user.name.split(' ')[0]}. Everything you manage, in one place.</p></div><span className="team-access-badge"><LayoutGrid size={15}/>{areas.length} workspaces</span></section><div className="team-section-heading"><h2>Your workspaces</h2><span>Choose an area to get started</span></div><div className="team-areas">{areas.map(a=>a.href?<a key={a.title} href={a.href} className="team-area-card" aria-label={a.title+' workspace'}>{content(a)}</a>:<button key={a.title} onClick={()=>onOpen(a.workspace!)} className={'team-area-card'+(a.workspace==='operations'?' team-area-operations':'')} aria-label={a.title+' workspace'}>{content(a)}</button>)}</div>{user.areas.staff&&<a href="/staff" className="team-queue"><span className="team-queue-icon"><ShoppingBag size={23}/></span><div><strong>FOND order queue</strong><span>Prepare, dispatch and complete orders.</span></div><span className="team-queue-action">Open queue <ArrowRight size={18}/></span></a>}</div></main>;
}
