// Local-only practice launcher. Never uses an existing database or real provider.
import {mkdtempSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
import {randomBytes,randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
import {getDb} from '../src/lib/db';
import {signUp} from '../src/lib/auth';
import {memberCard} from '../src/lib/counter-rewards';
import {getAvailableMenu} from '../src/lib/menu-store';
import {saveDocument,DEFAULT_SETTINGS} from '../src/lib/management';
import {saveProviderSecret} from '../src/lib/provider-secrets';
const directory=mkdtempSync(resolve('.coffee-practice-'));
process.env.FOND_DB_PATH=resolve(directory,'practice.sqlite');
process.env.FOND_CREDENTIALS_KEY=randomBytes(32).toString('hex');
process.env.FOND_PUBLIC_URL='http://127.0.0.1:3101';
delete process.env.FOND_HOST;
process.env.FOND_PRACTICE='true';
process.env.FOND_ADMIN_CODE='practice-admin';
process.env.FOND_STAFF_CODE='practice-staff';
process.env.FOND_COOKIE_SECURE='false';
for(const key of Object.keys(process.env))if(/^(YOCO_|TWILIO_|RESEND_|SMTP_)/.test(key))delete process.env[key];
const db=getDb();
saveDocument('trading',{...DEFAULT_SETTINGS,enforceHours:false,allowTestPayments:true,onlinePaymentsEnabled:false},'practice');
saveProviderSecret('yoco-secret','sk_test_practice_only','practice');saveProviderSecret('yoco-webhook','whsec_practice_only','practice');saveProviderSecret('yoco-pos-key','practice-business-key-not-real','practice');
saveDocument('yoco-pos',{enabled:false,environment:'sandbox',locationId:'practice',eftMappingVerified:false},'practice');
const variants=getAvailableMenu().filter(m=>m.category==='Coffee').map(m=>({id:m.id,name:m.name}));
db.prepare('UPDATE counter_reward_settings SET enabled=1,variants_json=? WHERE id=1').run(JSON.stringify(variants));
const u=signUp('coffee@example.test','CoffeePractice29!').user;
db.prepare('UPDATE users SET email_verified_at=? WHERE id=?').run(new Date().toISOString(),u.id);memberCard(u.id);
db.prepare('INSERT INTO counter_reward_sales (id,environment,yoco_id,order_number,sale_date,location_id,user_id,batch,quantity,credited,snapshot_json,actor,created_at,checked_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),'test','practice-starting-card','PRACTICE-START',new Date().toISOString().slice(0,10),'practice',u.id,'initial',9,9,'{}','practice-fixture',new Date().toISOString(),new Date().toISOString());
console.log('PRACTICE ONLY: http://127.0.0.1:3101/practice — separate database; external providers blocked.');
const child=spawn(process.execPath,['--import',pathToFileURL(resolve('scripts/coffee-practice-provider.mjs')).href,resolve('node_modules/next/dist/bin/next'),'start','--hostname','127.0.0.1','--port','3101'],{stdio:'inherit',env:{...process.env,NODE_OPTIONS:''}});
for(const signal of ['SIGINT','SIGTERM'] as const)process.on(signal,()=>child.kill(signal));
child.on('exit',code=>process.exit(code??0));
